Tgridneva first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #105
Opened 2023-10-09 18:07 UTC by TomaGridneva

дз 7 лекция

2023-10-09 18:10 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_1.py
дз 1

2023-10-09 18:11 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_2.py
2

2023-10-09 18:11 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
3

2023-10-09 20:20 UTC, IlyaOrlov requested changes
Супер! Но есть небольшие замечания.

2023-10-09 20:20 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_2.py
> +class Pupil:
Pupil по заданию является разновидностью Man. Поэтому тут стоит применить наследование.

2023-10-09 20:20 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +        self.cash = cash
cash стоит сделать защищённым атрибутом.

2023-10-09 20:20 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +            self.cash -= amount
Если это онлайн-платёж, странно, что кэш в банкомате уменьшается;)

2023-10-09 20:20 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +    print(f"Supported Operations: {atm.get_supported_operations()}")
Хотелось бы ещё увидеть демонстрацию полиморфизма, через вызов всех созданных методов у всех банкоматов.

2023-10-10 07:25 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_2.py
> +class Pupil:
изменено

2023-10-10 07:31 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +            self.cash -= amount
Поменяла на "баланс"

2023-10-10 07:32 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    print(f"Supported Operations: {atm.get_supported_operations()}")
сделано

2023-10-10 07:32 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +        self.cash = cash
сделаю

2023-10-10 10:14 UTC, AChertova commented on Practice/tgridneva/practice 7_2.py
> +        self.name = name
Класс Man надо полностью скопировать из предыдущего задания. Смысл в том, что класс Pupil очень похож на класс Man, но имеет свои особенности. Наша задача как раз и связать их между собой. У Pupil должен быть свой метод solve_task (который есть и у Man), он дополнен ожиданием времени для ответа (ваши строки 12-13). А сам ответ стоит напрямую позаимствовать у Man через вызов super()

2023-10-10 10:19 UTC, AChertova commented on Practice/tgridneva/practice 7_3.py
> +        super().__init__(balance)
В принципе init и так наследуется сам собой, если мы и не пропишем его у наследника. Такая запись была бы актуальна, если бы мы хотели дополнить init этого банкомата новыми параметрами.

2023-10-10 10:22 UTC, AChertova commented on Practice/tgridneva/practice 7_3.py
> +            self.cash -= amount
Все таки, думаю, что баланс тоже у банкомата, а не у пользователя банка. Думаю, Илья намекает, что этот параметр просто не должен измениться) Ну и слова online мне тут все таки не хватает))

2023-10-10 13:47 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +            self.cash -= amount
Да, если имеется в виду баланс клиента... то получается, что он один на всех клиентов) Если речь идёт о количестве наличных в банкомате, то его не нужно уменьшать при онлайн-платеже.

2023-10-12 12:33 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +            self.cash -= amount
Тогда я вернула назад и просто вывожу информацию о совершенном платеже

2023-10-12 12:38 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_2.py
> +        self.name = name
исправлено

2023-10-12 12:39 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
добюавила

2023-10-13 11:25 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +        super().__init__(balance)
Да. Т.к. `__init__` у OnlineATM не отличается от `__init__` у ATM, в дочернем классе этот метод переопределять не нужно (т.е. стр.21-22 можно просто удалить).

2023-10-13 11:26 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
Но, видимо, ещё не закоммитили?)

2023-10-13 11:26 UTC, IlyaOrlov requested changes
Осталась пара мелочей.

2023-10-14 09:19 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
да, забыла)

2023-10-14 09:21 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +        super().__init__(balance)
исправлено

2023-10-15 20:34 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
что -нибудь нужно еще изменить?

2023-10-15 20:35 UTC, TomaGridneva reviewed
удалила

2023-10-16 07:37 UTC, IlyaOrlov commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
Так ничего же не изменилось! make_payment в родительском классе так и отсутствует, isinstance присутствует. Вы же сами можете видеть, что дошло до гитхаба, а что не дошло: https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/105/files

2023-10-16 15:38 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
Вроде дошло?

2023-10-16 18:23 UTC, IlyaOrlov requested changes
Видимо, я кривовато объяснил)
make_payment должен присутствовать в обоих классах (и в OnlineATM, и в ATM), но у родительского класса ATM этот метод должен быть пустым (заглушкой).

2023-10-17 21:44 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +        return ["Withdraw Cash", "Deposit Cash", " Make Payment"]
исправила

2023-10-17 21:46 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +        print(f"Made a payment of {amount}")
исправлено

2023-10-18 08:57 UTC, IlyaOrlov requested changes
Не убрали `if isinstance(atm, OnlineATM)` из задачи 7.3 - то, ради чего и был весь сыр-бор с добавлением make_payment в родительский класс.
+ новые замечания по новому коду.

2023-10-18 08:57 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +        self.paragraphs = self.text.split(self.paragraph_symbol)
Так Вы получите в памяти кроме исходного текста ещё и список. Вместо этого надо посимвольно читать исходный текст, накапливая прочитанные символы в некий промежуточный буфер (это уже может быть список), и, если встретится символ параграфа, возвращать то, что есть в буфере (см. запись прошлого занятия примерно на отметке 2ч30мин.)

2023-10-18 08:57 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_4.py
В задаче требовалось использовать возможности библиотеки itertools

2023-10-19 14:59 UTC, TomaGridneva commented on Practice/tgridneva/practice 7_3.py
> +    if isinstance(atm, OnlineATM):
исправила

2023-10-19 15:45 UTC, TomaGridneva commented on Practice/tgridneva/Практика 8_4.py
добавила

2023-10-19 18:22 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +        self._buffer = []
self._buffer нам не нужен, а вот, символ параграфа ('\n') надо передавать в `__init__` в качестве параметра.

2023-10-19 18:23 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +                self._buffer.append(char)
Почему бы нам не складывать здесь всё сразу в paragraph?

2023-10-19 18:24 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +                    paragraphs.append(paragraph)
Опять мы копим всю информацию в дополнительном списке. Не надо этого делать! Набрали данные в paragraph и 
```python
if char == '\n':
    return paragaraph
```

2023-10-19 18:25 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +        return paragraphs
А где исключение StopIteration?

2023-10-19 18:26 UTC, IlyaOrlov commented on Practice/tgridneva/8_4-3.py
> +for combination in result:
Вопрос на понимание.
Если мы всё равно распечатываем result по частям, почему бы не вернуть в generate_password_combinations() просто itertools.permutations(password) ?

2023-10-21 07:55 UTC, TomaGridneva commented on Practice/tgridneva/8_4-3.py
> +for combination in result:
по факту тут нет необходимости создавать список combinations, я могу просто вернуть итератор itertools.permutations(password) из функции  generate_password_combinations() и теперь будет генерация паролей по только когда это нужно. переделать код?

2023-10-21 07:55 UTC, TomaGridneva commented on Practice/tgridneva/Практика 8_1.py
> +        return paragraphs
добавила

2023-10-21 07:55 UTC, TomaGridneva commented on Practice/tgridneva/Практика 8_1.py
> +                    paragraphs.append(paragraph)
исправила

2023-10-21 07:55 UTC, TomaGridneva commented on Practice/tgridneva/Практика 8_1.py
> +                self._buffer.append(char)
исправила

2023-10-21 07:56 UTC, TomaGridneva commented on Practice/tgridneva/Практика 8_1.py
> +        self._buffer = []
удалила

2023-10-21 08:08 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 8_1.py
> +        return paragraphs
где?

2023-10-21 09:51 UTC, IlyaOrlov commented on Practice/tgridneva/8_4-3.py
> +for combination in result:
ОК. Можно не переделывать. Достаточно понимания.

2023-10-21 09:52 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-21 09:52 UTC, merged