modul7
IlyaOrlov/PythonCourse2.0_September23 pull request #106
Opened 2023-10-09 22:08 UTC by RemoSet

2023-10-10 10:07 UTC, AChertova commented on Practice/amarinin/Modul_7/modul7_lesson7_2.py
> +        print("\nI`m not ready yet")
А смысл наследования тогда? Давайте вызовем в 23 строке функцию родителя через super) ожидание тоже можно покороче записать, но, в принципе, эффектно, интригует, мне понравилось) думаю, что оставим)

2023-10-10 20:28 UTC, RemoSet commented on Practice/amarinin/Modul_7/modul7_lesson7_2.py
> +        print("\nI`m not ready yet")
Исправил. Если бы в родительском классе функция занимала строчек 10-20-ть....  возможно сообразил бы ).

2023-10-11 10:25 UTC, AChertova commented on Practice/amarinin/Modul_7/modul7_lesson7_2.py
> +    def solve_task(self):
А куда декоратор исчез?

2023-10-11 20:11 UTC, IlyaOrlov commented on Practice/amarinin/Modul_7/modul7_lesson7_2.py
> +        print("\nI`m not ready yet")
Хорошее замечание насчёт функции в 10-20 строчек! Согласен, но всё руки не доходят доработать задание, чтоб потребность в переиспользовании родительского метода стала более очевидной)

2023-10-11 20:24 UTC, IlyaOrlov commented on Practice/amarinin/Modul_7/modul7_lesson7_2.py
> +    def solve_task(self):
Догадываюсь, чему он мешал) Поэтому добавлю небольшое разъяснение... Для вызова родительского статического метода из дочернего статического приходится применять слегка экзотический синтаксис: super(Pupil, Pupil).solve_task()

2023-10-11 20:34 UTC, RemoSet commented on Practice/amarinin/Modul_7/modul7_lesson7_1.py
> +        self.name = name
Э... "принимает имя в конструкторе". Тут как понял, но похоже не правильно. Но ведь как ни крути, все в конце концов становится доступным. Недоступен вне класса... и  в конструкторе ). Запутался )))

2023-10-11 20:35 UTC, RemoSet commented on Practice/amarinin/Modul_7/modul7_lesson7_1.py
> +        self.name = name
Очевидно, это что бы не прописывать имя при инициализации экземпляра?

2023-10-11 20:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_7/modul7_lesson7_1.py
> +        self.name = name
Нет) Это намёк сделать name защищённым (self._name = name), если не предполагается, что к нему должны обраться через man.name, например.

2023-10-12 08:08 UTC, IlyaOrlov requested changes
Осталось обозначить атрибут name, как защищенный (_name).

2023-10-13 11:41 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-13 11:41 UTC, merged