Домашнее задание к лекции 7
IlyaOrlov/PythonCourse2.0_September23 pull request #107
Opened 2023-10-10 11:07 UTC by Ekaterinka11

Направляю на проверку дз к 7 лекции

2023-10-10 11:51 UTC, AChertova commented on Practice/Kashintseva/task7_2.py
> +        print("I'm ready")
А сам ответ стоит напрямую позаимствовать у Man через вызов super(). Pupil все таки тот же Man, он тоже не готов)

2023-10-10 11:54 UTC, AChertova commented on Practice/Kashintseva/task7_3.py
> +        self._sum -= sum_minus
А если вдруг sum_minus окажется больше суммы в банкомате? Для начала метод должен сравнить эти величины.

2023-10-10 11:56 UTC, AChertova commented on Practice/Kashintseva/task7_3.py
> +        self._sum -= sum_pay
Я так предполагаю, что это онлайн-платежи? Слово online в названии метода было бы не лишним) И тут надо подумать, что мы подразумеваем под sum - сумма реальных денег в банкомате. При онлайн-переводе она не должна измениться. Можно просто вывести информацию на print)

2023-10-10 12:00 UTC, AChertova commented on Practice/Kashintseva/task7_3.py
> +class Bankomat(Bank):
Все таки задача подразумевает что есть "родитель" - классический банкомат, и "наследник" банкомат, поддерживающий дополнительно онлайн-переводы. Давайте придерживаться этой концепции.

2023-10-11 05:54 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_2.py
> +        super().__init__(name)
Поняла, поправила.

2023-10-11 05:54 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_2.py
> +        print("I'm ready")
Исправила.

2023-10-11 06:10 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_3.py
> +        self._sum -= sum_minus
Сделано)

2023-10-11 06:33 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_3.py
> +class Bankomat(Bank):
Поправила.

2023-10-11 06:52 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_3.py
> +        print("Ошибка ввода!")
Скорректировала.

2023-10-11 09:40 UTC, AChertova commented on Practice/Kashintseva/task7_2.py
> +        time.sleep(random.randint(3, 6))
Все хорошо, только 15 и 16 строки поменять местами. А то он сначала не готов, а потом ждет)) Должно быть наоборот

2023-10-11 09:44 UTC, AChertova commented on Practice/Kashintseva/task7_3.py
> +        self._sum -= sum_pay
Это как Вы посчитаете нужным) Я бы вывела какую-нибудь строчку "Онлайн-платеж совершен" и был бы статический метод. Оставим, как есть сейчас, пожалуй)

2023-10-11 10:24 UTC, AChertova commented on Practice/Kashintseva/task7_2.py
> +    def solve_task(self):
И тут метод все еще статический

2023-10-11 15:59 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_2.py
> +        time.sleep(random.randint(3, 6))
Ой, точно)

2023-10-11 15:59 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_2.py
> +    def solve_task(self):
Поправила.

2023-10-11 16:11 UTC, AChertova commented on Practice/Kashintseva/task7_2.py
> +    def solve_task(self):
Последний момент. У наследника метод уже не будет статическим, потому что внутри super негласно вызывается self) уберем декоратор здесь и передадим в функцию self

2023-10-11 16:19 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_2.py
> +    def solve_task(self):
Исправила, поняла.

2023-10-11 20:53 UTC, IlyaOrlov requested changes
Есть один важный момент, связанный с принципами ООП, который Вашим решением очень ярко иллюстрируется. Если детально его разобрать, то можно будет уверенно говорить, что понимание ООП достигнуто)

2023-10-11 20:53 UTC, IlyaOrlov commented on Practice/Kashintseva/task7_3.py
> +    op = input(f"Выберите операцию 1 (пополнить) или 2 (снять наличные): ")
А вот здесь и в стр.53 принципиальный момент! Внешнему алгоритму не стоит вникать в то, какие операции поддерживает выбранные банкомат. Достаточно того, что он знает, какой банкомат выбран. А всю информацию о допустимых операциях надо брать из самого банкомата. 
Иначе при добавлении новых типов банкоматов, или добавлении новых функций в существующие банкоматы придётся каждый раз переписывать основной алгоритм.
В идеале основной код должен остаться таким:
```python
lst = [b1, b2, b3]
choice = input(f"Выберите банкомат {i for i, _ in enumerate(lst, 1)}: ")
b = lst[int(choice) - 1]
ops = b.operat()  # лучше, чтоб здесь вернулся список из методов, например [b.plus_money, b.minus_money]
i = input("Выберите операцию {i for i, _ in enumerate(ops , 1)}: ")
ops[int(i) - 1]()  # вызов соответствующего метода
```
Но пока пусть хотя бы информация об операциях будет инкапсулирована в банкомате.

2023-10-12 11:50 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_3.py
> +    op = input(f"Выберите операцию 1 (пополнить) или 2 (снять наличные): ")
Ох, как бы до этого додуматься самой))
Не знаю, верно ли я скорректировала. Направила очередную попытку.

2023-10-13 09:01 UTC, Ekaterinka11 commented on Practice/Kashintseva/task7_3.py
> +    op = input(f"Выберите операцию 1 (пополнить) или 2 (снять наличные): ")
После лекции мне стал понятен основной код и то, что не хватает квадратных скобок.
Скорректировала итог.

2023-10-13 11:49 UTC, IlyaOrlov approved these changes
Класс!!! Минимум конкретики, максимум абстракции. Как итог, имеем универсальный основной код, к которому легко подцепить любой новый тип банкомата.
И ещё плюсом принципы [SOLID](https://habr.com/ru/companies/productivity_inside/articles/505430/) соблюдены!!!
Отлично! Замечаний нет!

2023-10-13 11:49 UTC, merged