Седьмая лекция.
IlyaOrlov/PythonCourse2.0_September23 pull request #109
Opened 2023-10-11 12:39 UTC by mtvtanic

2023-10-11 20:27 UTC, IlyaOrlov requested changes
Хорошо. Но есть несколько нюансов.

2023-10-11 20:27 UTC, IlyaOrlov commented on Practice/ermakova/control7.2.py
> +    def solve_task(self):
self стоит убрать.
Понимаю, чем обосновано его появление) Для вызова родительского статического метода из дочернего статического приходится применять слегка экзотический синтаксис: `super(Pupil, Pupil).solve_task()`

2023-10-11 20:27 UTC, IlyaOrlov commented on Practice/ermakova/control7.3.py
> +                self._cash += money
Наверное, здесь -=

2023-10-11 20:27 UTC, IlyaOrlov commented on Practice/ermakova/control7.3.py
> +                self._cash += summa
Если это онлайн-платёж, на кэше банкомата операция, вроде как, сказываться не должна.

2023-10-11 21:40 UTC, mtvtanic commented on Practice/ermakova/control7.2.py
> +    def solve_task(self):
Исправила)! спасибо !

2023-10-11 21:41 UTC, mtvtanic commented on Practice/ermakova/control7.3.py
> +                self._cash += money
Извините, конечно минус)!

2023-10-11 21:41 UTC, mtvtanic commented on Practice/ermakova/control7.3.py
> +                self._cash += summa
Разумеется. Совсем заучилась) Спасибо!

2023-10-12 07:59 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-12 07:59 UTC, merged