Afedotov first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #11
Opened 2023-08-24 19:06 UTC by fedotov89

Домашняя работа № 1 прилагается

2023-08-28 18:43 UTC, IlyaOrlov requested changes
Всё хорошо. Только один вопрос)

2023-08-28 18:43 UTC, IlyaOrlov commented on Practice/AFedotov/practice1.py
> +print(f"Echo: {a}")
Как убрать "кирпичи" в конце файлов?:)

2023-08-29 04:00 UTC, fedotov89 commented on Practice/AFedotov/practice1.py
> +print(f"Echo: {a}")
С помощью пустой строки в конце кода. Добавил её.

2023-08-29 11:52 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-08-29 11:52 UTC, merged