Домашнее задание 7 лекция
IlyaOrlov/PythonCourse2.0_September23 pull request #110
Opened 2023-10-12 14:34 UTC by lvladimirova

Первая попытка

2023-10-12 16:51 UTC, AChertova commented on Practice/lvladimirova/Lecture_11/7_2.py
> +        self.name = name
Почему тут атрибут не закрыли?)

2023-10-12 16:53 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_2.py
> +        self.name = name
Ощибочка вышла, простите) Честно, на втором часе от банкоматов стало подташнивать))

2023-10-12 16:53 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_2.py
> +        self.name = name
Ошибочка вышла, простите)

2023-10-12 16:53 UTC, AChertova commented on Practice/lvladimirova/Lecture_11/7_2.py
> +        time.sleep(random.randint(3, 6))
Наверное сначала замер, а потом ответил? :)

2023-10-12 16:55 UTC, AChertova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +MAX_BALANS = 5000  # Максимальная величина ден.средств в банкомате
А почему решили вынести эту величину вне класса?

2023-10-12 16:58 UTC, AChertova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +            return
А что возвращаем?

2023-10-12 17:07 UTC, AChertova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +    def __init__(self, name, balans):
Поскольку init есть у родителя, он автоматически наследуется как любой другой метод) такую запись мы бы применили, если бы хотели, например, добавить новые параметры для наследника

2023-10-12 17:17 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +    def __init__(self, name, balans):
Да, я уже переделала у себя.  Просто почему-то сначала не получалось использовать self.name в функции онлайн оплаты. Возможно, это мои кудрявые ручки))

2023-10-12 17:27 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +MAX_BALANS = 5000  # Максимальная величина ден.средств в банкомате
Больше себе для наглядности, когда код писала)) сейчас засуну:)

2023-10-12 17:37 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +            return
Заработалась, всё написала - и print, и return. Как в "Джентльменах удачи" - чем больше сдадим, тем лучше :)

2023-10-13 11:38 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_11/7_3.py
> +            return
Как я понял, чтоб следующий код по увеличению баланса не вызывался. Нагляднее, думаю, было бы через else:
```python
    def deposit(self, amount):
        if (self._balans + amount) > self._max_balans:
            print(f"Переполнение! {self.name} не может принять {amount} руб.")
        else:
            self._balans += amount
            print(f"{self.name}. Внесение {amount} руб.")
```
Всегда лучше, когда у функции одна точка входа и одна точка выхода. Её так легче контролировать.

2023-10-13 11:38 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_11/7_3.py
> +    def balans(self, new_balans):
Сдаётся мне, что этот сеттер нигде не используется. Нужен ли он?

2023-10-13 11:39 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_11/7_3.py
> +    Bank1 = Bankomat('Первый банкомат', 5000, 1000)
Имена экземпляров (как и обычные переменные) должны быть в snake_case строчными буквами)

2023-10-13 11:40 UTC, IlyaOrlov requested changes
Есть ещё вопросы по мелочи.

2023-10-13 12:39 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +            return
Согласна! Исправила

2023-10-13 12:42 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_11/7_3.py
> +    Bank1 = Bankomat('Первый банкомат', 5000, 1000)
Ну это я на классы пересмотрела :) извините)

2023-10-13 12:51 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_11/7_3.py
> +            return
return остался

2023-10-13 12:56 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-13 12:56 UTC, merged