Д\з по лекции №7 (1,2 задачи)
IlyaOrlov/PythonCourse2.0_September23 pull request #111
Opened 2023-10-13 20:46 UTC by nsa3108

2023-10-14 09:10 UTC, IlyaOrlov requested changes
ОК, но есть вопрос.

2023-10-14 09:10 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_7_task1.py
> +def shoot():
Зачем нужны функции shoot, walk, choosetank? И не должны ли они быть методами танка?

2023-10-15 13:52 UTC, nsa3108 reviewed
выложила новый вариант первого задания

2023-10-15 18:11 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_7_task1.py
> +    nikname: object
Не могу не задать вопрос: почему nickname сделан ещё и атрибутом класса, и аннотация типов (это как раз запись вида `: object`) применена именно к нему?

2023-10-15 19:40 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_7_task1.py
> +    nikname: object
честно не знаю ответ на это вопрос, гугл не помог, но решила оставить, так как pycharm добавил автоматом при alt+enter

2023-10-16 07:34 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_7_task1.py
> +    nikname: object
Понятно. Криминала тут, на самом деле, нет. Видимо, PyCharm просто решил прописать в классе используемые атрибуты с аннотациями типов. В нашем случае особой пользы от этого нет, т.к. все необходимые атрибуты у нас и так прописаны в `__init__`. Более того, наличие одинакового атрибута и в классе, и в `__init__` может вызвать недоумение. Да и аннотации типов надо либо применять ко всем атрибутам и методам, либо нигде не писать.
Так что я бы порекомендовал от этой "подсказки" PyCharm отказаться, и убрать эту строку.

2023-10-22 20:41 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_7_task1.py
> +    nikname: object
спасибо за разъяснения, убрала

2023-10-22 21:35 UTC, IlyaOrlov requested changes
Замечание не по заданию!

2023-10-22 21:35 UTC, IlyaOrlov commented on Tasks/pep8task.py
Этот файл не надо править! Он один на всех!

2023-10-23 11:31 UTC, nsa3108 commented on Tasks/pep8task.py
удалила

2023-10-23 19:52 UTC, IlyaOrlov commented on Tasks/pep8task.py
К сожалению не могу на него не обращать внимание, т.к. если я приму этот пулл реквест, то этот файл удалится и в main. По-хорошему, Вам нужно скопировать этот файл на свой бранч в точности из main, закоммитить и запушить. Тогда его упоминание пропадёт из пулл реквеста. Его не надо было удалять, надо было просто отменить изменения.
Сейчас вернуть файл можно в три действия (см. картинки ниже):
![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/b314a574-4d7e-4694-8029-7ca2db24dcb3)

![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/1619b5f0-772e-437f-bf88-36c0af05f4b2)

![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/0fff2aaa-653b-4b98-84b2-0cb233e7a381)

Если не получится - пишите.

2023-10-24 09:40 UTC, nsa3108 commented on Tasks/pep8task.py
Илья, добрый день, все сделала по вашей инструкции, pep8task появился на main, как отменить изменения? или вообще ничего не надо мне делать, если вы замержите с ним?

2023-10-24 14:21 UTC, IlyaOrlov commented on Tasks/pep8task.py
Добрый день!
Файл вернулся, но он всё же не совсем такой, как на main.
Видите, тут [Tasks/pep8task.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/111/files#diff-19e199dad7977d4a580e34ca864e97962221c7676231ed21dafe0e3df9fb6146) показаны отличия от main? Надо эти отличия убрать (так же, у себя на компьютере, а потом закоммитить и запушить).

2023-10-24 21:32 UTC, nsa3108 commented on Tasks/pep8task.py
Илья, я сначала я попыталась это сделать в pycharm - но незакоммитилась новая версия ( сначала попыталась в taske файл pep8task закоммитить - не получилось, потом его скопировала в новый файл и его козаммитить и запушить - тоже не то получилось), потом я сделала прямо на гитхабе и закоммитила, но это явно что-то не то получилось. Можно это как-то исправить с вашей стороны, а то я как бы чего не напортила. 
Как я вижу алгоритм исправления:
1. нужно найти у себя в папке на Pycharme файл с моими исправлениями, но я  его не вижу
2. исправить его до первоначальной версии ( вашей) 
3. закоммитить и запушить
То есть сделать так, чтобы он был идентичный вашему первоначальному образцу ( без моих исправлений).
Правильный ход моих мыслей?
Теперь понять бы, где его можно корректно исправить и чтобы он при коммите не ругался (Push of the current branch "nskorokhodova_first_branch" was rejected. Remote changes need to be merged before pushing.  In this case merge is highly recommended, because there are non-pushed merge commits. Rebasing them can lead to problems.)

2023-10-25 08:08 UTC, IlyaOrlov commented on Tasks/pep8task.py
1. Сначала сделайте git pull origin nskorokhodova_first_branch (будут конфликты, которые можно решить, выбрав Accept Theirs).
2. Затем git pull origin main, чтоб подтянуть последние изменения с главной ветки.
3. А затем... записал видео, как поправить файл

https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/ac4b5bea-5b2d-4de3-bdaa-084f6ef312b7

4. А теперь закоммитить и запушить (если шаги 1 и 2 выполнены верно, то проблем с гитом тут не будет).

2023-10-25 11:10 UTC, nsa3108 commented on Tasks/pep8task.py
Илья, сделала все по инструкции, первый раз не хотел файл пушится, повторила еще раз все сначала, все прошло, но по факту вижу два файла, один в task, другой в моей папке Practice

2023-10-25 20:09 UTC, IlyaOrlov commented on Tasks/pep8task.py
Ну почти) Ещё одно отличие осталось (видимо, в исходном файле в этой строке ещё пробелов понаставлено):

![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/18687ed9-eaf2-41c6-a9e1-7ca605e56ebd)

Файл, который в Вашей папке, можете удалить, можете оставить) Он ни на кого не повлияет.

2023-10-26 14:57 UTC, nsa3108 commented on Tasks/pep8task.py
![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/142823163/894f83a6-92ad-4b26-a552-da191dfbe0df)

2023-10-26 14:59 UTC, nsa3108 commented on Tasks/pep8task.py
пытаюсь проделать все то же самое и исправить 38 строку, но не получается...

2023-10-26 15:23 UTC, IlyaOrlov commented on Tasks/pep8task.py
ОК. Пусть так в main записывается)

2023-10-26 15:24 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-26 15:24 UTC, merged