Achernov first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #116
Opened 2023-10-16 12:37 UTC by chernovandreey

2023-10-16 13:03 UTC, IlyaOrlov requested changes
Есть замечания по мелочи.

2023-10-16 13:03 UTC, IlyaOrlov commented on Practice/achernov/module_7/task_2.py
> +        if self.weight < other.weight:
Можно проще: `return self.weight < other.weight`
Так мы явно сводим задачу сравнения уток к задаче сравнения чисел, которую интерпретатор знает, как решать.

2023-10-16 13:03 UTC, IlyaOrlov commented on Practice/achernov/module_7/task_2.py
> +    def __lt__(self, other):
И ещё магический метод `__gt__` тоже нужно реализовать. Для программы особой необходимости в этом нет (т.к. есть `__lt__`), но это нужно, чтоб лучше запомнилось, что такой метод существует.

2023-10-17 14:34 UTC, IlyaOrlov requested changes
Небольшое замечание по новому заданию.

2023-10-17 14:34 UTC, IlyaOrlov commented on Practice/achernov/module_8/task_2.py
> +        sleep(randint(3, 6))
После того, как Pupil "поспал", он всё равно должен сказать, что не готов. Т.е. тут ещё надо вывести то же, что говорит Man. Лучше так: `super(Pupil, Pupil).solve_task()`

2023-10-20 11:19 UTC, AChertova commented
Вы подтянули много лишних файлов. Нужно сделать git pull origin main и git push, чтоб в пулл реквесте остались только ваши файлы.

2023-10-20 11:26 UTC, chernovandreey commented
Ой, хз как так вышло
Исправлю

2023-10-20 11:27 UTC, chernovandreey commented
В консоли намудрил видимо

2023-10-20 13:31 UTC, IlyaOrlov commented on Practice/achernov/module_8/task_3.py
> +            self._money -= sbp
Money - это чьи деньги? Клиента или банкомата? Если банкомата, то при безналичной оплате их количество уменьшаться не должно.

2023-10-20 14:00 UTC, chernovandreey commented on Practice/achernov/module_8/task_3.py
> +            self._money -= sbp
В таком случае лучше добавить ещё атрибут класса для баланса доступных на счету банка, чтоб наличные оставались без изменений?

2023-10-20 14:36 UTC, IlyaOrlov commented on Practice/achernov/module_8/task_3.py
> +            self._money -= sbp
Если реализовывать поддержку счета клиента, то, по-хорошему, надо для разных клиентов разные счета заводить, запрашивать у пользователя какие-то данные для сопоставления текущего клиента с его счётом, который надо уменьшать/увеличивать (и это лучше делать с использованием базы данных, работу с которой мы пройдем только в прикладной части). Поэтому для упрощения предлагаю рассматривать _money просто, как количество наличных в банкомате, и не менять их количество при онлайн-операции.

2023-10-22 21:32 UTC, IlyaOrlov requested changes
Последний штрих.

2023-10-22 21:32 UTC, IlyaOrlov commented on Practice/achernov/module_8/task_3.py
> +        if sbp <= self._money:
Да и проверка эта тоже ни к чему, раз мы решили, что `self._money:` - это количество денег в банкомате.

2023-10-26 15:26 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-26 15:26 UTC, merged