My first commit. Домашнее задание 1.
IlyaOrlov/PythonCourse2.0_September23 pull request #12
Opened 2023-08-25 06:46 UTC by TroshinMike

Практика по 1 и 2 уроку.

2023-08-25 16:05 UTC, Tetrackon submitted a review, later dismissed

2023-08-25 16:05 UTC, Tetrackon commented on Practice/mtroshin/lesson_2.2.py
> +print("Средний расход бензина:", result, "(литров на 1 км)")
Это конечно не было ошибкой, но почему бы и не уточнить?) Правда заменять f-строку, на обычную было не обязательно :)

print(f"Средний расход бензина: {result} (литров на 1 км)")

Вот так тоже сработало бы.

2023-08-28 18:42 UTC, IlyaOrlov requested changes
Ещё парочка замечаний.

2023-08-28 18:42 UTC, IlyaOrlov commented on Practice/mtroshin/task_pytest.py
> +import pytest
Это задание, наверное, необязательно отправлять в main.

2023-08-28 18:42 UTC, IlyaOrlov commented on Practice/mtroshin/Lesson_2.py
> +print(f"Площадь круга: {result}")
В этом и остальных файлах: стоит убрать "кирпич" в конце, добавив пустую строку.

2023-08-31 18:57 UTC, merged