задание 2 по лекции 7
IlyaOrlov/PythonCourse2.0_September23 pull request #124
Opened 2023-10-19 12:32 UTC by yilya21q

2023-10-19 13:05 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-10-19 13:05 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +class Pupil:
У Pupil потерялся родитель!

2023-10-19 13:05 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +    thinking_time = random.randint(3, 6)
Стр.10-11 не должны висеть в воздухе. Их требуется реализовать в методе solve_task, унаследованном от родителя и переопределенном.

2023-10-22 12:12 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +class Pupil:
Внесла изменения

2023-10-22 12:12 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +    thinking_time = random.randint(3, 6)
скорреткировала

2023-10-22 21:16 UTC, IlyaOrlov requested changes
Ещё есть, что исправить.

2023-10-22 21:16 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +    def solve_task(self):
Зачем здесь self? Этот метод, очевидно, должен быть статическим.

2023-10-22 21:16 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +    def solve_task():
Раз метод не использует ни self, ни cls, его надо сделать статическим - повесить декоратор `@staticmethod`.

2023-10-22 21:16 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +        print("I'm not ready yet")
Лучше здесь вызвать родительский метод, чтоб подчеркнуть наследование этой возможности: `super(Pupil, Pupil).solve_task()`

2023-10-23 09:26 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +    def solve_task(self):
Если я уберу self, код будет обращаться к атрибуту thinking_time и вызывать методы time.sleep(), super().solve_task())?

2023-10-23 09:27 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +    def solve_task():
Исправила

2023-10-23 09:27 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +        print("I'm not ready yet")
исправила

2023-10-23 19:38 UTC, IlyaOrlov commented on Practice/platonova/lec_7.2.py
> +    def solve_task(self):
thinking_time не является ни атрибутом класса, ни атрибутом экземпляра. Это обычная локальная переменная. self никак не используется внутри этого метода solve_task(), поэтому, если вы уберете его из списка аргументов, в работе метода ничего не поменяется. Только на этот solve_task тоже надо повесить декоратор staticmethod.

2023-10-23 19:41 UTC, IlyaOrlov requested changes
Осталось доразбираться с solve_task в Pupil.

2023-10-24 03:05 UTC, yilya21q commented on Practice/platonova/lec_7.2.py
> +    def solve_task(self):
Внесла изменения

2023-10-24 14:16 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-24 14:16 UTC, merged