Mtroshin first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #126
Opened 2023-10-19 20:45 UTC by TroshinMike

Домашнее задание Лекция 7. ООП.

2023-10-20 11:01 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +class tank:
Классы мы называем в CamelCase - с большой буквы

2023-10-20 11:02 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +
Между классом и основным кодов должны быть 2 строки, у Вас одна

2023-10-20 11:03 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +    boekomplekt = 41
В идеале использовать английский для названий переменных

2023-10-20 11:05 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +    def colors(self):
Раз мы повесили декоратор классового метода, то внутри скобок должен стоять не self, а cls

2023-10-20 11:07 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        return self.name
А вот это имело бы смысл, если бы в init атрибуты были закрыты для пользователя. Давайте закроем имя и вес в строках 5-6

2023-10-20 11:12 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        return self.weight() != other.weight()
С 25 строки () - скобки у веса лишние

2023-10-20 11:15 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        newduck = Duck
Раз тут мы создаем экземпляр утки, то надо передать ее имя и исходный показатель веса

2023-10-20 13:29 UTC, IlyaOrlov requested changes
Хорошо, но надо исправить указанные замечания.

2023-10-21 15:15 UTC, TroshinMike commented on Practice/mtroshin/Lecture_7/1.py
> +        self.id = id
:)) хорошо!)

2023-10-22 08:03 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +        self.point = self.point + point
Можно использовать += , если мы хотим увеличить число на значение

2023-10-22 08:03 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +
И все равно осталась одна строка между классом и основным кодом

2023-10-22 08:04 UTC, AChertova commented on Practice/mtroshin/Lecture_7/1.py
> +    def shoot (self):
Между функциями тоже нужна пустая строка

2023-10-22 08:06 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        return self.name
Внутри def name и def weight теперь тоже должны оказаться закрытые атрибуты

2023-10-22 08:17 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        return self.name
И во всех последующих методах мы должны обращаться именно к закрытым атрибутам через _. Сейчас мы вызываем методы, а они нужны только для представления пользователю информации об этих закрытых атрибутах

2023-10-22 08:18 UTC, AChertova commented on Practice/mtroshin/Lecture_7/2.py
> +        return f'<Duck name={self.name()} weight={self.weight()} color={self.color}>'
И раз здесь мы не вызываем функцию, а обращаемся к атрибуту, то и () - опять же не нужны

2023-10-22 08:21 UTC, AChertova commented on Practice/mtroshin/Lecture_7/3.py
> +
Между импортами и классом 2 пустые строки. Если что, PyCharm сам подсвечивает такие ошибки светлой волнистой линией

2023-10-22 08:21 UTC, AChertova commented on Practice/mtroshin/Lecture_7/3.py
> +
А вот между функциями должна быть одна строка

2023-10-22 08:27 UTC, AChertova commented on Practice/mtroshin/Lecture_8/1.py
> +    def solve_task(self):
Хорошо бы повесить декоратор @staticmethod, тогда можем убрать из скобок self, который здесь не используем. Этот же декоратор не забыть добавить в следующем задании к функциям у Man и Pupil. Но тогда 14 строку надо будет заменить на несколько специфический вызов super(Pupil, Pupil).solve_task()

2023-10-22 08:31 UTC, AChertova commented on Practice/mtroshin/Lecture_8/3.py
> +        if amount <= self.balance:
Везде внутри класса мы должны вызывать self.__balance, обращаясь именно к закрытому приватному атрибуту, а не функции, возвращающей значение баланса (стр.5-7). Кстати, в строке 11 только одно подчеркивание

2023-10-22 08:35 UTC, AChertova commented on Practice/mtroshin/Lecture_8/3.py
> +
Между классами должно быть 2 строки

2023-10-22 08:40 UTC, AChertova commented on Practice/mtroshin/Lecture_8/3.py
> +            return print("Недостаточно средств.")
По идее онлайн-операции на наличие денег в банкомате никакого влияния не должны оказывать) уменьшаться должен счет клиента, о котором тут мы не должны говорить) и если уж вы сделали атрибут баланса приватным (с двойным подчеркиванием), то наследники уже к нему обращаться не могут

2023-10-22 08:54 UTC, AChertova commented on Practice/mtroshin/Lecture_8/3.py
> +    print(f"Тип банкомата: {atm},\nбаланс: {atm.balance}\nПоддерживаемые операции: {atm.info()}\n")
Тут мы печатаем  {atm} и нам выводится "служебная" информация об объекте подобного вида: <__main__.OnlineATM object at 0x00000195640D0690>. Чтобы мы контролировали информацию, выводящуюся при вызове print на экземпляр, лучше добавить в родительский класс магический метод repr

2023-10-22 12:31 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/1.py
> +    def solve_task(self):
Логика вот этого специфического вызова super(Pupil, Pupil).solve_task() - не понятна(: не могли бы Вы, пожалуйста, объяснить

2023-10-22 12:41 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/3.py
> +        if amount <= self.balance:
Если везде (где одно подчеркивание) сделать с двумя подчеркиваниями, то выходит ошибка при обращении к cash_machines[1].online_pay(200) . Вызвать закрытый класс из под дочернего класса не получается(

2023-10-22 13:56 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/3.py
> +            return print("Недостаточно средств.")
Точно! Спасибо, теперь пазл сложился)

2023-10-22 21:23 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/1.py
> +    def solve_task(self):
Стоит пересмотреть видеозапись 12-го занятия (примерно 22-я минута). Там мы это подробно разбирали.

2023-10-22 21:28 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    @property
Не хватает пустой строки сверху.

2023-10-22 21:30 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    print(f"{atm}")
А может, в этом же цикле и все остальные методы банкоматов повызывать? Тестировать, так тестировать.

2023-10-23 10:07 UTC, AChertova commented on Practice/mtroshin/Lecture_8/1.py
> +    def solve_task(self):
В двух словах - чтобы мы могли оставить метод у наследника статическим, иначе не сработает

2023-10-25 09:09 UTC, TroshinMike commented on Practice/mtroshin/Lecture_7/1.py
> +
После описания методов класса? Добавил)

2023-10-25 20:39 UTC, IlyaOrlov requested changes
Ещё осталась пара замечаний. 
И просьба - не резолвить замечания самому (только исправлять и отвечать на них), иначе не очень удобно проверять.
Т.е. логика такая (замечание резолвит тот, кто его оставил): 
1. Мне что-то не понравилось - я оставил замечание.
2. Вы исправили замечание, или объяснили, почему не будете исправлять.
3. Если исправление/ответ меня устроили - я резолвлю замечание (отмечаю, как исправленное), если не устроили - продолжаю дискуссию.

2023-10-25 20:39 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_7/2.py
А где примеры использования этой утки?

2023-10-25 21:20 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/3.py
> +    print(f"{atm}")
Не пойму, как сделать. Если добавляю методы, с параметрами которые, к примеру:  print(f"{atm}\n {atm.deposit(11)}")  то выводится в месте такого параметра - None (:

2023-10-25 21:31 UTC, TroshinMike commented on Practice/mtroshin/Lecture_7/2.py
добавил)

2023-10-26 09:10 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    print(f"{atm}")
Вот! Потому что функция deposit() у Вас что возвращает? Правильно: то, что возвращает функция print(), т.е. всегда None. Та же проблема и с withdraw().
Во-первых, надо разделить return и print. Никакого смысла совмещать их в одном выражении нет.
Во-вторых, если deposit() и withdraw() и так умеют печатать результат на экране, зачем их в print здесь подставлять. Можно просто вызвать: 
```python
print(atm)
atm.deposit(11)
atm.withdraw(12)
atm.online_pay(200)  # ;)
```

2023-10-26 10:40 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/3.py
> +    print(f"{atm}")
Понял, спасибо большое:)

2023-10-26 14:09 UTC, IlyaOrlov requested changes
Ещё один небольшой нюанс предусмотреть.

2023-10-26 14:09 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    if type(atm).__name__ == 'OnlineATM':
Замечательно! А теперь, чтоб не пришлось делать эту проверку на OnlineATM, предлагаю добавить в класс ATM тоже метод online_pay, но этакий вырожденный вариант:
```python
    def online_pay(self, amount):
        pass
```

2023-10-26 14:39 UTC, TroshinMike commented on Practice/mtroshin/Lecture_8/3.py
> +    if type(atm).__name__ == 'OnlineATM':
Попробовал - в таком случае выводится None (: Сделал через: return ""

2023-10-26 15:19 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    if type(atm).__name__ == 'OnlineATM':
Здесь ничего плохо в выводе None нет. Метод в ATM же добавлен только для общего интерфейса. None показывает, что данный метод в данном классе на самом деле не поддерживается.

2023-10-26 15:19 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-26 15:20 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_8/3.py
> +    if type(atm).__name__ == 'OnlineATM':
Но это уже непринципиально)

2023-10-26 15:20 UTC, merged