modul10
IlyaOrlov/PythonCourse2.0_September23 pull request #127
Opened 2023-10-20 12:20 UTC by RemoSet

2023-10-20 13:39 UTC, IlyaOrlov requested changes
Хорошо. Но можно ещё улучшить.

2023-10-20 13:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_10/modul10_lesson9_1.py
> +    print(list(set(re.findall(r'git\s[a-z]*\s-{1,2}\w+\s\w*\.*\w*', line))))
Неплохо!
Возможно, одним шаблоном всё не охватить. Можно подготовить несколько шаблонов, обходить файл в цикле for, применяя разные шаблоны к каждой строке и результат складывать в отдельный список.
Кстати, findall - удачное решение!

2023-10-20 13:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_10/modul10_lesson9_1.py
> +    line = read_api(r"C:\Users\vogel\PycharmProjects\PythonCourse2.0_September23\Practice\README.md")
Относительный путь к README.md будет звучать, как "на две папки выше". 
"На одну папку выше" записывается, как `".."`
"На две" - `r"..\.."`
И добавляем имя файла: `r"..\..\README.md"`
Относительный путь лучше абсолютного, т.к. он меньше зависит от конкретного компьютера.

2023-10-20 19:49 UTC, IlyaOrlov requested changes
Ещё пара комментариев по мелочи

2023-10-20 19:49 UTC, IlyaOrlov commented on Practice/amarinin/Modul_10/modul10_lesson9_2.py
> +        if start.isoweekday() in (1, 2, 3, 4, 5):
Проверить start.isoweekday() < 6 как-то проще и быстрее, чем сравнивать результат этого метода с каждым элементом кортежа.

2023-10-20 19:49 UTC, IlyaOrlov commented on Practice/amarinin/Modul_10/modul10_lesson9_2.py
> +        start = start + dt.timedelta(days=1)
+=

2023-10-20 22:09 UTC, RemoSet commented on Practice/amarinin/Modul_10/modul10_lesson9_2.py
> +        if start.isoweekday() in (1, 2, 3, 4, 5):
Это, что бы я не забывал про такое сравнение в кортеже. Тут вдруг захотелось так написать, по тому что вдруг вспомнил, что так то же можно )))))

2023-10-20 22:12 UTC, RemoSet commented on Practice/amarinin/Modul_10/modul10_lesson9_2.py
> +        start = start + dt.timedelta(days=1)
Да, пока не вошло в привычку, бывает пропускаю. И когда по привычке так расписываешь, длинно, оно кажется как то надежнее ))). Понимаю, привычки нужно менять, но кто то пьет кофе с сахаром, а кто то без.

2023-10-21 09:54 UTC, IlyaOrlov approved these changes
Отлично! Принципиальных замечаний нет. Решение для 9.1 можно при необходимости усовершенствовать, если идеи будут.

2023-10-21 09:54 UTC, merged