Лекция 9, задание 4
IlyaOrlov/PythonCourse2.0_September23 pull request #133
Opened 2023-10-23 11:50 UTC by lvladimirova

Не уверена, что всё правильно поняла, но как смогла, строго не судите :) 4 задание в 9 лекции

2023-10-23 20:03 UTC, IlyaOrlov requested changes
Хорошо, только код надо немного иначе по файлам разнести.

2023-10-24 06:03 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_4/ser.py
> +from kod import People
Согласна, что-то даже в голову такое не пришло. Исправила

2023-10-24 06:32 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_3.py
А вот с этим заданием я в край запуталась в папках, файлах и буквах. Каша в голове полная, так что буду очень рада, если сможете мне прям разжевать))

2023-10-24 11:35 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
> +sys.path = os.path.join(os.getcwd(), "Proba")
Ох! А зачем это в sys.path?
sys.path - это пути, в которых интерпретатор ищет импортированные (через import) модули.

2023-10-24 11:40 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
> +                if (os.path.isdir(full_path)) and (os.path.getmtime(full_path) < time.time() - 120):
А что для папок не getctime() используете?
getctime() - это как раз время создания папки, а getmtime() - время последнего изменения папки.

2023-10-24 11:46 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
Так у Вас почти всё верно написано (кроме использования sys.path).
В общем случае у нас система папок многоуровневая: в папке лежат файлы и папки, во вложенных папках тоже лежат файлы и папки и т.д.
os.walk - это итератор, который обходит всю эту древовидную структуру по уровням (можно даже назвать их ярусами): root - это текущая папка (фактически, текущий ярус), dirs - папки на текущем ярусе, files - файлы на текущем ярусе. Поудаляли, что могли, идём на следующий ярус (os.walk возвращает всё те же данные, но уже для одной из подпапок).

2023-10-24 13:40 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_3.py
Просто мне прям очень трудно со всем этим многообразием букв, чтобы ни в чём не запутаться. В общем, файлы - это прям вообще не моё :)

2023-10-24 13:40 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_3.py
> +sys.path = os.path.join(os.getcwd(), "Proba")
Уже вчера наудалялась, надолго хватит :) Вроде поправила код

2023-10-24 15:03 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
> +sys.path = r'C:\Users\Admin\PycharmProjects\PythonCourse2.0_September23\Practice\lvladimirova\Lecture_14\Proba'
Вообще не надо трогать ни sys.path, ни модуль sys в этом задании!!!
Можете завести переменную `path_to_file = r'C:\Users\Admin\PycharmProjects\PythonCourse2.0_September23\Practice\lvladimirova\Lecture_14\Proba'` и с ней работать.
А sys.path используется исключительно для управления импортами!

2023-10-24 15:07 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
Не аргумент! У Вас был код и с гораздо большим количеством букв:)
Ну а чтоб не запутаться с длинными путями к файлам, лучше использовать относительные пути.
Заведите в своей папке подпапку Proba и передайте её в функцию: 
```python
while True:
    delete_files_and_folders(r".\Proba")
```

2023-10-24 18:21 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_3.py
Поправила. Вопрос - путь к файлу тоже сделать относительным?

2023-10-24 18:42 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_14/9_3.py
Лучше, да)
Сейчас странная ситуация: в path_to_file Вы записываете один путь, а в функцию передаёте другой.
Тогда уж надо записать относительный путь в path_to_file (path_to_file = r".\Proba") и передать его в функцию: delete_files_and_folders(path_to_file) 
На практике относительные пути всегда предпочтительнее. Т.к. если скрипт с папкой Proba скопировать на другой компьютер, то путь `".\Proba"` будет там актуален, а вот путь `'C:\Users\Admin\PycharmProjects\PythonCourse2.0_September23\Practice\lvladimirova\Lecture_14\Proba'` - вряд ли)

2023-10-24 19:07 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_14/9_3.py
Абсолютно согласна)

2023-10-24 19:36 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-24 19:37 UTC, merged