Homework lecture 9(task9_1,task9_2, task9_3, task9_4)
IlyaOrlov/PythonCourse2.0_September23 pull request #137
Opened 2023-10-24 13:18 UTC by JulMakarova

Комментарии.
task9_1: Как сделать это одним регулярным выражением так и не поняла.
task9_2: Ох, усложнила себе задачу с праздниками, не зная о существовании библиотеки holidays, но в любом случае опыт)

2023-10-24 14:48 UTC, IlyaOrlov requested changes
Замечательно! Но есть кое-что, что стоит оптимизировать.

2023-10-24 14:48 UTC, IlyaOrlov commented on Practice/julmakarova/task9_2.py
> +        if i_date.weekday() in range(0, 5) and not(i_date in holidays):
Лучше i_date.weekday() < 5, т.к. это одна проверка, а in range(0, 5) предполагает в худшем случае 5 проверок.
Также, лучше смотрится `i_date not in holidays`

2023-10-24 14:48 UTC, IlyaOrlov commented on Practice/julmakarova/task9_2.py
> +holidays = [dt.date(2023, 2, 23), dt.date(2023, 3, 8),
holidays - глобальная переменная. Использовать (а тем более менять) такие переменные в функциях НЕ принято. Потому что становится сложно отследить, где и как переменная меняется по ходу работы программы. Например, если я просто построчно буду смотреть основной код, я никогда не догадаюсь, что функция add_long_holiday, оказывается, меняет holidays. Чтоб об этом узнать, мне надо зайти в функцию add_long_holiday.
Можно сделать так...
holidays (лучше, кстати, сделать это множеством, а ещё лучше frozenset) делаем константой (называем большими буквами HOLIDAYS) и выносим наверх файла под импорты (см. [PEP8](https://peps.python.org/pep-0008/#constants)) - это базовые праздничные дни.
add_long_holiday меняем так, чтоб она принимала HOLIDAYS и строила из них новый набор праздничных дней: 
```python
holidays = add_long_holiday(dt.date(2023, 1, 1), 8, HOLIDAYS)
holidays = add_long_holiday(dt.date(2023, 5, 1), 9, holidays)
```
Ну и не забываем передать holidays в качестве параметра в рабочую функцию:
```python
work_days(d1, d2, holidays)
```
Будет очень красиво и изящно, если всю работу с holidays (в т.ч. HOLIDAYS) упаковать в класс;)

2023-10-24 14:48 UTC, IlyaOrlov commented on Practice/julmakarova/task9_1.py
> +    all_text = f.read()
Считывая всё содержимое файла через f.read() в оперативную память, мы очень рискуем, т.к. файл может оказаться очень большим. В общем случае, лучше идти и анализировать файл построчно.

2023-10-24 14:58 UTC, IlyaOrlov commented
> Комментарии. task9_1: Как сделать это одним регулярным выражением так и не поняла. task9_2: Ох, усложнила себе задачу с праздниками, не зная о существовании библиотеки holidays, но в любом случае опыт)

task9_1: Скажу честно, как получить идеальный результат одним выражением, не знаю) Есть +/- хорошие варианты, но и к ним можно придраться. Поэтому использование нескольких выражений считаю вполне приемлемым. 
task9_2: Используя внешнюю библиотеку holidays, Вы добавили бы лишнюю зависимость в свой программный код. Представьте, что Вы реализовали с помощью этой библиотеки какой-нибудь производственный календарь общего пользования (как здесь https://www.consultant.ru/law/ref/calendar/proizvodstvennye/2023/). И внезапно нас осчастливили ещё одним государственным праздничным днём. Чтоб отразить это в производственном календаре, придётся ждать, пока автор библиотеки holidays (если он ещё не забил на своё детище), выкатит очередное обновление. Когда это будет - неизвестно. Поэтому своя реализация в данном случае надёжней.

2023-10-25 10:52 UTC, JulMakarova commented on Practice/julmakarova/task9_2.py
> +        if i_date.weekday() in range(0, 5) and not(i_date in holidays):
Спасибо за замечание, и правда не задумалась об этом (хотя мысль про <5 была, но решила, что разницы во времени выполнения не будет). Исправила.

2023-10-25 10:54 UTC, JulMakarova commented on Practice/julmakarova/task9_2.py
> +holidays = [dt.date(2023, 2, 23), dt.date(2023, 3, 8),
Да, изначально не понравилось,что информация про holidays разбросана по всему коду, но решила, что создание класса под нее будет излишним. Теперь поняла, что лучше бы сделала класс) Исправила.

2023-10-25 10:54 UTC, JulMakarova commented on Practice/julmakarova/task9_1.py
> +    all_text = f.read()
Поняла, спасибо. Исправила)

2023-10-25 20:03 UTC, IlyaOrlov requested changes
Всё супер! Но есть ещё предложения по оптимизации.

2023-10-25 20:03 UTC, IlyaOrlov commented on Practice/julmakarova/task9_1.py
> +        l1 = re.findall(r"(git c.{5,7} [^\"]*)", line)
Паттерны поиска стоит скомпилировать перед циклом для ускорения.
Ну и т.к. findall в случае неудачи просто возвращает пустой список, можно чуть упростить код:
```python
p1 = re.compile(r"(git c.{5,7} [^\"]*)")
p2 = re.compile(r"(git \w{3,5} [^()\"1]*)")
for line in f:
    lst += re.findall(p1, line) + re.findall(p2, line)
```
Не проверял, но, наверное, сработает)

2023-10-26 05:49 UTC, JulMakarova commented on Practice/julmakarova/task9_2.py
> +    def set_hol(self):
Действительно, отличное решение) Спасибо,буду знать.
Изначально думала, что к атрибуту _set_hol все обращения будут исключительно через сеттер и геттер. Думала, что получится даже уйти от метода add_holiday и реализовать это через сеттер, но спасибо Pycharm-у, который подсказал, что сеттер должен быть исключительно в виде def set_hol(self, new_set), что больше параметров передаваться не должно.
В итоге получилось совсем уйти и от сеттера и от геттера)

2023-10-26 05:53 UTC, JulMakarova commented on Practice/julmakarova/task9_2.py
> +        self._set_hol = Holidays.HOLIDAYS
Реализовала "размораживание" только в методе add_holiday решив, что пусть остается frosenset-ом до первого вызова метода, которого в принципе  может и не быть, чтобы у пользователя не было соблазна изменить его в других местах:)

2023-10-26 06:01 UTC, JulMakarova commented on Practice/julmakarova/task9_1.py
> +        l1 = re.findall(r"(git c.{5,7} [^\"]*)", line)
Ага, так лучше)
Хотела как раз уточнить про совмещение регулярных выражений, можно ли как-то записать их в одной группе.
В презентации есть: 
(re) | Группирует регулярные выражения и запоминает найденный текст.
Но работать с этим не пробовала. Записала себе в список "Разобрать", который регулярно пополняется))

2023-10-26 08:00 UTC, IlyaOrlov commented on Practice/julmakarova/task9_1.py
> +        l1 = re.findall(r"(git c.{5,7} [^\"]*)", line)
Записать несколько регулярных выражений в одной группе не получится (ну или во всяком случае мне о таких возможностях неизвестно).
"(re) | Группирует регулярные выражения и запоминает найденный текст." - это имеется в виду, что регулярные выражения в скобках ищутся, как отдельные **подвыражения**. Как в примере из лекции: 
```python
line = "Cats are smarter than dogs"
res = re.findall(r'(.*) are (.*?) .*', line, re.M|re.I)
```
И на выходе, если в строке нашёлся весь паттерн, можем ещё увидеть, что конкретно совпало с регулярными выражениями в скобках: `[('Cats', 'smarter')]`: `'Cats'` - это `(.*)`, `'smarter'` - это `(.*?)`.

2023-10-26 08:02 UTC, IlyaOrlov commented on Practice/julmakarova/task9_2.py
> +        self._set_hol = Holidays.HOLIDAYS
Так и подумал) Да, тоже корректная логика.

2023-10-26 08:02 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-26 08:02 UTC, merged