Домашнее задание к 9 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #138
Opened 2023-10-25 13:53 UTC by Ekaterinka11

Прошу проверить дз к 9 лекции. Очень сомнительно получилось. Особенно в 3 задании что-то не то, но пока нет мыслей, как исправить.

2023-10-25 20:21 UTC, IlyaOrlov requested changes
В целом, хорошо. Но есть некоторые замечания.

2023-10-25 20:21 UTC, IlyaOrlov commented on Practice/Kashintseva/task9_1.py
> +        com = re.findall(r'(git\s\w*)', line)
Паттерн поиска стоит скомпилировать перед циклом для ускорения. Ну и моржовый оператор сделал бы этот код чуть изящней)

2023-10-25 20:21 UTC, IlyaOrlov commented on Practice/Kashintseva/task9_4.py
> +
Пустой строки не хватает.

2023-10-28 06:21 UTC, Ekaterinka11 commented on Practice/Kashintseva/task9_1.py
> +        com = re.findall(r'(git\s\w*)', line)
Сделала, поняла.

2023-10-28 06:21 UTC, Ekaterinka11 commented on Practice/Kashintseva/task9_4.py
> +
поправила

2023-10-28 06:21 UTC, Ekaterinka11 commented on Practice/Kashintseva/task9_4.py
> +
поправила

2023-10-28 06:22 UTC, Ekaterinka11 commented on Practice/Kashintseva/task9_3.py
> +                if time.time() - os.path.getctime(path) > 60:
Рекурсивно вызываем, чтобы понять, нет ли там внутри файлов? Правильно понимаю?

2023-10-28 13:29 UTC, IlyaOrlov commented on Practice/Kashintseva/task9_3.py
> +                if time.time() - os.path.getctime(path) > 60:
Да. Верно.

2023-10-28 13:29 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-28 13:30 UTC, merged