Девятая лекция. Задание 1, 3
IlyaOrlov/PythonCourse2.0_September23 pull request #139
Opened 2023-10-25 18:35 UTC by mtvtanic

1 задание, методом тыка в основном насчет поиска и символов) не знаю вообще то, что надо было или нет) пока очень тяжело тут
3 задание вообще темный лес. Что получилось, что нет. Не понимаю. Вроде ничего не удалилось, но больше не получается

2023-10-25 20:30 UTC, IlyaOrlov requested changes
Есть замечание по заданию 1.
А что вызывает вопросы в 3-м задании? С помощью os.walk обходим дерево папок по уровням (это называется обход в ширину) и проверяем files и dirs на каждом уровне.

2023-10-25 20:30 UTC, IlyaOrlov commented on Practice/ermakova/control9.1.py
> +        x = (re.findall(r'git\s+[a-z]+[^а-я()"]*', line, re.I))
Паттерн поиска надо скомпилировать перед циклом. Также непонятно, зачем тут скобки и переменная **x**. В остальном, всё ОК. Только к line перед поиском стоит применить rstrip('\n'), иначе лишние символы в итоговый список попадают.

2023-10-25 20:58 UTC, mtvtanic commented on Practice/ermakova/control9.1.py
> +        x = (re.findall(r'git\s+[a-z]+[^а-я()"]*', line, re.I))
Поняла, сейчас поправлю) Спасибо!

2023-10-25 21:10 UTC, mtvtanic commented on Practice/ermakova/control9.1.py
> +        x = (re.findall(r'git\s+[a-z]+[^а-я()"]*', line, re.I))
В  3 задании, искала везде конечно решения, смотрела эти библиотеки. Делала по шаблону. Непонятно мне почти все, когда файлы((( Пока для меня тяжко с ними, легко прочитать, написать. Но всё остальное, пути, прочтения определенные. Вообще библиотеки, связанные с ними. Обойти, пройти, пыталась вникнуть. Особенно к контрольной. Очень тяжело. Больше им внимания хотелось уделить( Уж извините, что здесь высказалась) Спасибо за все!

2023-10-25 21:18 UTC, mtvtanic commented
> Есть замечание по заданию 1. А что вызывает вопросы в 3-м задании? С помощью os.walk обходим дерево папок по уровням (это называется обход в ширину) и проверяем files и dirs на каждом уровне.

2023-10-25 21:41 UTC, mtvtanic commented
Я что-то тут наделала, пока отвечала на комментарии. Надеюсь поправила правильно. О ужас))) Посмотрите, пожалуйста, что поправила. Первый раз так вышло(((

2023-10-26 09:04 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-26 09:04 UTC, merged