домашнее задание
IlyaOrlov/PythonCourse2.0_September23 pull request #14
Opened 2023-08-26 10:05 UTC by yilya21q

2023-08-27 08:15 UTC, Tetrackon commented on Practice/platonova/task3.py
> +print(int(a)+int(b))
По pep8, символы математических операций, нужно выделять пробелами. Тоже самое касается "="

2023-08-28 08:59 UTC, yilya21q commented on Practice/platonova/task3.py
> +print(int(a)+int(b))
Спасибо, исправила

2023-08-28 18:38 UTC, IlyaOrlov requested changes
Ещё есть, что поправить.

2023-08-28 18:38 UTC, IlyaOrlov commented on Practice/platonova/task1.py
> +a = input ("Введите а: ")
Здесь и в остальных файлах: не должно быть пробелов между именем функции и открывающейся скобкой ([PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call%3A))

2023-08-29 12:54 UTC, yilya21q commented on Practice/platonova/task1.py
> +a = input ("Введите а: ")
Спасибо, исправила

2023-08-29 14:01 UTC, IlyaOrlov requested changes
Ещё кое-где надо подправить.

2023-08-29 14:01 UTC, IlyaOrlov commented on Practice/platonova/task3.py
> +print(int (a)+int (b))
Вот здесь ещё надо подправить!

2023-08-30 03:12 UTC, yilya21q commented on Practice/platonova/task3.py
> +print(int (a)+int (b))
Исправила, спасибо

2023-08-30 08:47 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-08-30 08:47 UTC, merged