Задание к 8 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #141
Opened 2023-10-27 19:07 UTC by nsa3108

2023-10-27 19:53 UTC, IlyaOrlov requested changes
Есть существенные замечания по [Practice_lec_8_task3.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/141/files#diff-b6ac2d061fa5d4c217431e19a467a1e1f4752de66c322a71acf93ae542da8bed)

2023-10-27 19:53 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
Почему cashwithdrawal и deposit выглядят как методы экземпляра, но определены вне класса, как обычные функции? И где примеры с их использованием?

2023-10-27 19:53 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.__amount = amount
Вопрос на понимание. Почему здесь выбран именно закрытый доступ, а не защищённый?

2023-10-27 19:53 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +    def online_pay(self, amount):
Демонстрацию работы этого метода тоже хотелось бы увидеть.

2023-11-03 18:06 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.__amount = amount
потому что служит для обращения только внутри класса, а не для еще дочерних классов

2023-11-03 18:10 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_8_task3.py
Это ошибка

2023-11-04 12:05 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.__amount = amount
ОК. Если amount - это количество наличных в банкомате, то логично. Дочерний класс - Online - конечно, своих методов для работы с наличными иметь не будет. Потому и доступ к amount ему не нужен.

2023-11-04 12:13 UTC, IlyaOrlov requested changes
Оставил одно замечание.
Ну и вообще, странно, что в банкомате - один счёт на всех пользователей (как я понял, это всё-таки счёт, а не количество наличных), но раз задача учебная, можно и так)

2023-11-04 12:13 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +    if "Онлайн-платежи" in atm.supported_operations:
Так всё же "Онлайн-платежи" или "Платежи онлайн"?
На самом деле, можно добавить в родительский класс Bankomat вырожденный метод:
```python
def make_online_payment(self, amount):
    pass
```
Т.е. у класса Bankomat этот метод для порядка тоже будет (хотя он и ничего не делает). Тогда проверка в стр.50 уже будет не нужна.

2023-11-06 16:06 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +    if "Онлайн-платежи" in atm.supported_operations:
Исправила онлайн платежи,  добавила вырожденный метод

2023-11-06 19:13 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        if "Онлайн платежи" in self.supported_operations:
Предлагаю завести константу где-нибудь в классе:
```python
class Bankomat:
    ONLINE_PAYMENT = "Онлайн платежи"
```
и везде в коде использовать именно её:
```python
class Online(Bankomat):
    def __init__(self, balance):
        super().__init__(balance)
        self.supported_operations = [Bankomat.ONLINE_PAYMENT]

    def make_online_payment(self, amount):
        if Bankomat.ONLINE_PAYMENT in self.supported_operations:
```
Это позволит связать код в стр.30 и 33 не только логически, но и синтаксически,  а также предотвратить возможные ошибки в написании вида операции и обеспечить возможность её централизованного переименования.

2023-11-06 21:16 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.supported_operations = Bankomat.ONLINE_PAYMENT
Без квадратных скобок здесь будет ошибка в стр.35

2023-11-07 17:46 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.supported_operations = Bankomat.ONLINE_PAYMENT
Илья, скобкт добавила и подгрузила исправленный код, но не понимаю, почему в 35 строке будет ошибка если не будет скобок

2023-11-08 09:23 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.supported_operations = Bankomat.ONLINE_PAYMENT
Будет логическая ошибка. Строка 35 выглядит так:
```python
if Bankomat.ONLINE_PAYMENT in self.supported_operations:
```
Без скобок мы ищем "Онлайн платежи" in "Онлайн платежи", т.е. строку в такой же строке.
Со скобками мы ищем "Онлайн платежи" in ["Онлайн платежи"], т.е. строку в списке строк (желаемую операцию в списке желаемых операций).

2023-11-08 09:24 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-08 09:24 UTC, merged

2023-11-08 11:58 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_8_task3.py
> +        self.supported_operations = Bankomat.ONLINE_PAYMENT
Поняла, спасибо за разъяснение