Экзамен, непринятые задания
IlyaOrlov/PythonCourse2.0_September23 pull request #146
Opened 2023-10-30 17:30 UTC by lvladimirova

2023-10-30 19:24 UTC, IlyaOrlov requested changes
Есть замечание по [task5.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/146/files#diff-50b966e1b3184d7ee6bbab0623270a145fddc2e250b171c530efe3eba1be6846)

2023-10-30 19:24 UTC, IlyaOrlov commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
А что делать, если source_file окажется папкой? Надо же эту папку тоже копировать! А где у нас функция для копирования папок? А вот она - в стр.16:)

2023-10-30 19:29 UTC, lvladimirova commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
То есть, я правильно понимаю, что надо ещё и для папок создать копирование? :)

2023-10-30 20:02 UTC, IlyaOrlov commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
Да. И для этого достаточно добавить буквально пару строк;)

2023-10-30 20:42 UTC, lvladimirova commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
Попробовала что-то наисправлять

2023-10-31 12:50 UTC, lvladimirova commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
Чем больше исправляю, тем меньше понимаю. Наверное, чего-то опять не то

2023-10-31 17:02 UTC, IlyaOrlov commented on Practice/lvladimirova/Exam2/task5_1.py
Это решение не использует функцию copy_file, как того требовало задание!

2023-10-31 17:04 UTC, IlyaOrlov commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
```python
if os.path.isfile(source_file):
    copy_file(source_file, destination_file)
else:
    copy_dir(source_file, destination_file)
```

2023-10-31 17:11 UTC, lvladimirova commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
Как всё сложное стало простым! Вот теперь я кажется поняла рекурсию. Функция вызывает сама себя, но уже с другим аргументом. Как бы зацикливание, но со сменой аргумента

2023-10-31 18:36 UTC, IlyaOrlov commented on Practice/lvladimirova/Exam2/task5.py
> +            if os.path.isfile(source_file):
Именно так)

2023-10-31 18:36 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-31 18:36 UTC, merged