Ssharygina first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #147
Opened 2023-10-30 21:20 UTC by SvetlanaSharygina

Практические задания из 6, 7 и 8 лекции

2023-10-31 12:32 UTC, IlyaOrlov requested changes
Хорошо. Но есть небольшие замечания.

2023-10-31 12:32 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina8.1.py
> +        else:
Всё хорошо, но ещё стоит предусмотреть случай, когда в тексте вообще нет символа параграфа.
Т.е. если мы дошли до конца текста, но в **par** ещё что-то осталось накопленное, надо сначала сделать **return par**, а уже только на следующем вызове выбрасывать StopIteration.

2023-10-31 12:32 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina8.3.py
> +        self.stop = time.time()
Нужно ли stop делать атрибутом? Ведь эта переменная нужна нам тут для разового использования.

2023-10-31 12:32 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina8.3.py
> +        self.start = time.time()
Должен ли атрибут start быть доступен вне класса? Или всё же стоит сделать его защищённым?

2023-10-31 12:33 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina8.4.py
> +lst1 = itertools.chain([1, 2, 3], [4, 5], [6, 7])
Здесь и ниже можно чуть проще:
```python
print(list(itertools.chain([1, 2, 3], [4, 5], [6, 7])))
```
или хотя бы:
```python
lst1 = list(itertools.chain([1, 2, 3], [4, 5], [6, 7]))
print(lst1)
```

2023-10-31 21:17 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina8.1.py
> +        else:
Исправила

2023-10-31 21:17 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina8.3.py
> +        self.stop = time.time()
Исправила

2023-10-31 21:17 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina8.3.py
> +        self.start = time.time()
Исправила

2023-10-31 21:17 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina8.4.py
> +lst1 = itertools.chain([1, 2, 3], [4, 5], [6, 7])
Исправила

2023-10-31 21:21 UTC, SvetlanaSharygina commented
Все исправлено, надеюсь!

2023-11-01 17:08 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-01 17:09 UTC, merged