Ermakova first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #148
Opened 2023-10-30 21:54 UTC by mtvtanic

4 задание поняла и вроде получилось.
5 задание по логике поняла, но как будто ничего не получилось.
И еще у меня не подгружается изменения с main в pycharm. Раньше такого не было. Ошибку выдает. Не знаю правильно ли здесь отобразятся.

2023-10-31 12:37 UTC, IlyaOrlov requested changes
Хорошо, но есть замечания.

2023-10-31 12:37 UTC, IlyaOrlov commented on Practice/ermakova/exam/exam2.5.py
> +                    os.makedirs(source_dir)
Зачем при копировании создавать исходную папку? Если её нет, то и копировать нечего.

2023-10-31 12:37 UTC, IlyaOrlov commented on Practice/ermakova/exam/exam2.5.py
> +                        for file in files:
А как быть с подпапками? Их же тоже надо копировать.

2023-10-31 17:31 UTC, mtvtanic commented on Practice/ermakova/exam/exam2.5.py
> +                        for file in files:
Как то так получилось

2023-10-31 18:41 UTC, IlyaOrlov commented on Practice/ermakova/exam/exam2.5.py
> +                    copydir(s1, d2)
Здесь рекурсия будет лишней, потому что os.walk уже рекурсивно обходит все папки и подпапки. 
Поэтому здесь будет достаточно просто создать папку d2, а заполнится она на следующих итерациях цикла `for super_dirs, dirs, files in os.walk(source_dir):`

2023-10-31 19:46 UTC, mtvtanic commented on Practice/ermakova/exam/exam2.5.py
> +                    copydir(s1, d2)
То есть вместо, copydir(s1,d2),  я пишу os.makedir(d2)? все остальное остается? Или вообще второй цикл for не нужен....

2023-10-31 19:55 UTC, mtvtanic commented on Practice/ermakova/exam/exam2.5.py
> +                    copydir(s1, d2)
Очень надеюсь, что правильно поняла!!))) спасибо, просвещаете. Как были очень тяжко файлы, так и остались(

2023-11-01 16:29 UTC, IlyaOrlov requested changes
Хорошо, но есть один сомнительный момент.

2023-11-01 16:29 UTC, IlyaOrlov commented on Practice/ermakova/exam/exam2.5.py
> +                os.makedirs(d2)
Только первой super_dirs будет как раз source_dir. Соответственно, d2 - это будет destination_dir.
Поэтому os.makedirs(destination_dir) в стр.20 вроде как не особо нужен.

2023-11-01 17:54 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-01 17:54 UTC, merged