modul11
IlyaOrlov/PythonCourse2.0_September23 pull request #149
Opened 2023-10-31 22:55 UTC by RemoSet

2023-11-01 17:02 UTC, IlyaOrlov requested changes
Хорошо, но есть некоторые замечания.

2023-11-01 17:02 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +    thread1 = threading.Thread(target=find_primes_step_1, args=(3, 10000))
Не удобней ли все потоки сразу в список сложить? Чтоб одним циклом их все стартовать, а другим джойнить.
Тот же вопрос по процессам.

2023-11-01 17:02 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
Ожидаются также выводы и ответы на вопросы в задании. Можно представить в виде комментариев.

2023-11-01 21:00 UTC, RemoSet commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +    thread1 = threading.Thread(target=find_primes_step_1, args=(3, 10000))
да, я уже пересмотрел видео с лекцией ), исправлю

2023-11-01 21:01 UTC, RemoSet commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +                lst_prime.append(num)
О! вчера что то не соображалось (

2023-11-02 14:51 UTC, RemoSet commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +                lst_prime.append(num)
да.. for и else..  пока по привычке else связывается в основном с if и еще немножко с другим

2023-11-03 11:07 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +#  и непредсказуемости результата. появляется ассинхронность.
Про асинхронность не совсем верно. Асинхронность имеет место уже по факту использования потоков или процессов. Здесь больше подходит слово рассинхронизация или несогласованность.

2023-11-03 11:10 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +    str(tim).ljust(5, "0")
Так, конечно, тоже можно. Но, мне кажется, было бы элегантней решить проблему выравнивания (и даже округления) средствами f-строк: https://www.geeksforgeeks.org/string-alignment-in-python-f-string/

2023-11-03 11:10 UTC, IlyaOrlov reviewed
А кто в итоге самый быстрый, и почему?

2023-11-04 18:42 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +    Хотя конечно, тут еще и с памятью нужно разобраться...
Рассуждения верные. Аналогия изящная. А по факту, конкретно в Вашем эксперименте какое из решений преуспело?)

2023-11-05 19:34 UTC, RemoSet commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +#  и непредсказуемости результата. появляется ассинхронность.
несогласованность...

2023-11-06 18:32 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_2.py
> +    print(f"N:{os.getpid() : < 8}{d[0] + d[1]}") if str(type(d[0])) == str(type(d[1])) \
str вокруг type необязательно использовать.

2023-11-06 18:34 UTC, IlyaOrlov commented on Practice/amarinin/Modul_9+/modul9+_1.py
> +    if __name__ == "__main__":
Эта строка кажется лишней.

2023-11-06 18:38 UTC, IlyaOrlov commented on Practice/amarinin/Modul_9+/modul9+_1.py
> +        print(new_lst1 := [int(x) * int(x) for x in [i for i in lst if i.isdecimal()] if int(x) % 5 == 0])
Здесь повторяется int(x). К нему и стоит применить "моржа":) Например, так:
`print([x * x for i in lst if i.isdecimal() and (x := int(i)) % 5 == 0])`

2023-11-06 18:40 UTC, IlyaOrlov commented on Practice/amarinin/Modul_9+/modul9+_2.py
> +    чем то похоже на телеграмм бот? а мы такой будем писать?
Мы не будем. Но там всё просто) Есть видео - https://drive.google.com/file/d/1Ak98Xk2u8iBsy6muEJtzynyfLR7oQM-a/view?usp=drive_link

2023-11-06 18:43 UTC, IlyaOrlov commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +       Эх, многословие какое то :( .. а если будет принт каждого значения... такой... прииииинт...
Вот-вот, результат принта и хотелось бы увидеть) Чтоб самому код не запускать)

2023-11-06 19:11 UTC, RemoSet commented on Practice/amarinin/Modul_9+/modul9+_1.py
> +    if __name__ == "__main__":
:) всегда делаю копию и работаю в копии. а то потом вспоминай что там было. в оригинале. конечно, гит есть, но...
Если копия лучше-копирую ее в оригинал... да, немножко запутанно, зато надежно )

2023-11-06 19:12 UTC, RemoSet commented on Practice/amarinin/Modul_9+/modul9+_1.py
> +        print(new_lst1 := [int(x) * int(x) for x in [i for i in lst if i.isdecimal()] if int(x) % 5 == 0])
да, красиво....

2023-11-06 19:12 UTC, RemoSet commented on Practice/amarinin/Modul_9+/modul9+_2.py
> +    чем то похоже на телеграмм бот? а мы такой будем писать?
Круто! уже скачал )

2023-11-06 19:13 UTC, RemoSet commented on Practice/amarinin/Modul_11/modul11_lesson10_1.py
> +       Эх, многословие какое то :( .. а если будет принт каждого значения... такой... прииииинт...
))) запущу, на ночь.

2023-11-08 09:29 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-08 09:29 UTC, merged