Домашнее задание 1
IlyaOrlov/PythonCourse2.0_September23 pull request #15
Opened 2023-08-26 15:04 UTC by Ekaterinka11

2023-08-27 08:11 UTC, Tetrackon submitted a review, later dismissed
Всё хорошо, но есть небольшие замечания.

2023-08-27 08:11 UTC, Tetrackon commented on Practice/Kashintseva/task2.py
> +name=input("Введите имя: ")
По Pep8, "=" нужно выделять пробелами.

2023-08-27 08:11 UTC, Tetrackon commented on Practice/Kashintseva/task3.py
> +print(int(a)+int(b))
Символы математических действий, также надо выделять пробелами

2023-08-27 12:32 UTC, Ekaterinka11 commented on Practice/Kashintseva/task2.py
> +name=input("Введите имя: ")
Исправила

2023-08-27 12:36 UTC, Ekaterinka11 commented on Practice/Kashintseva/task3.py
> +print(int(a)+int(b))
Исправила

2023-08-28 18:36 UTC, IlyaOrlov requested changes
Оставил ещё комментарий.

2023-08-28 18:36 UTC, IlyaOrlov commented on Practice/Kashintseva/task1.py
> +a=input("Введите a: ")
Здесь ещё осталось пробелы вокруг = поставить.

2023-08-28 18:56 UTC, Ekaterinka11 commented on Practice/Kashintseva/task1.py
> +a=input("Введите a: ")
Исправила

2023-08-28 19:53 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-08-28 19:54 UTC, merged