Задания 1, 3 к лекции 10
IlyaOrlov/PythonCourse2.0_September23 pull request #152
Opened 2023-11-02 06:03 UTC by lvladimirova

В голове слегка каша, но к вопросам "Что будет, если 'забыть' выполнить start или join для процессов и для потоков?" можно сказать, что процесс - это по сути запущенная программа, а поток является частью этой программы. Соответственно, если забыть выполнить start для потока, то данный поток останется в исходном состоянии и не начнёт выполнение, а если забыть выполнить join для потока, то он не будет дожидаться своего завершения и код для потока будет продолжать работу.  Насколько я понимаю, это всё можно применить и к процессу

2023-11-02 08:47 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-11-02 08:47 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_1.py
> +        t.join()
На лекции говорилось, почему не стоит join и start объединять в одном цикле!

2023-11-02 08:47 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_1.py
> +        p.join()
На лекции говорилось, почему не стоит join и start объединять в одном цикле! Это так же справедливо и для процессов.

2023-11-02 08:47 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
В задании говорилось про параллельный запуск функции. Возможно ли это через процессы в Python?

2023-11-02 08:48 UTC, IlyaOrlov commented
> если забыть выполнить join для потока, то он не будет дожидаться своего завершения и код для потока будет продолжать работу

"если забыть выполнить join для потока, то он не будет дожидаться своего завершения и код для потока будет продолжать работу" - сам поток не будет дожидаться своего завершения?

2023-11-02 09:14 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Я так понимаю, что через multiprocessing

2023-11-02 09:39 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Угу

2023-11-02 09:50 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Осталось разобраться, как реализовать :)

2023-11-02 09:51 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_17/10_1.py
> +        t.join()
Сейчас поправила, просто пошла лёгким путём, было красиво и просто :)

2023-11-02 12:26 UTC, lvladimirova commented
> > если забыть выполнить join для потока, то он не будет дожидаться своего завершения и код для потока будет продолжать работу
> 
> "если забыть выполнить join для потока, то он не будет дожидаться своего завершения и код для потока будет продолжать работу" - сам поток не будет дожидаться своего завершения?

Опечаталась. Если забыть выполнить join для потока, то главный поток не будет ждать завершения дочернего потока и может "вклиниться" ещё один поток

2023-11-02 20:29 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Можно было и multiprocessing.Process три раза создать/стартовать, но через Poll даже красивей:)

2023-11-02 20:31 UTC, IlyaOrlov requested changes
Замечаний нет. Только вопрос по [10_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/152/files#diff-288c8425bb964e5d1375e9eeba2a27124bb5985c9c4ec529d4785658118ebe39):
Кто в итоге победил и почему?)

2023-11-03 05:00 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Ну в лекции было написано, что как раз объект Pool используется для создания нескольких процессов, выполняющих одну функцию, но с разными аргументами. Грех было не попробовать :) Один вопрос остался - когда применяется pool.starmap и как его использовать?

2023-11-03 05:57 UTC, lvladimirova commented
> Замечаний нет. Только вопрос по [10_1.py]: Кто в итоге победил и почему?)
Побеждает последовательное выполнение задачи, поскольку при CPU-bound задачах, требующих вычислений и не связанных с вводом-выводом данных потоки не дают преимущества

2023-11-03 11:17 UTC, IlyaOrlov commented
> > Замечаний нет. Только вопрос по [10_1.py]: Кто в итоге победил и почему?)
> > Побеждает последовательное выполнение задачи, поскольку при CPU-bound задачах, требующих вычислений и не связанных с вводом-выводом данных потоки не дают преимущества

Хорошо. А процессы почему не победили?

2023-11-03 11:22 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
pool.starmap используется почти так же, как и pool.map, только для target-функций с более, чем одним аргументом. Например: 
```python
from multiprocessing import Pool


def add_function(a, b):
    if isinstance(a, int) and isinstance(b, int):
        return a + b

    if isinstance(a, str) and isinstance(b, str):
        return f'{a} {b}'

    if isinstance(a, list) and isinstance(b, list):
        return a + b


if __name__ == '__main__':
    my_args = [(1, 2), ("good", "day"), ([1, 2, 3], [4, 5, 6])]
    pool = Pool(processes=4)
    result = pool.starmap(add_function, my_args)
    print(f"Конечный результат: {result}")
```

2023-11-03 17:04 UTC, lvladimirova commented
> > > Замечаний нет. Только вопрос по [10_1.py]: Кто в итоге победил и почему?)
> > > Побеждает последовательное выполнение задачи, поскольку при CPU-bound задачах, требующих вычислений и не связанных с вводом-выводом данных потоки не дают преимущества
> 
> Хорошо. А процессы почему не победили?

Процессы не победили потому, что их создание и управление требует больше ресурсов (времени и памяти) по сравнению с потоками

2023-11-03 17:54 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_17/10_2.py
> +with ThreadPoolExecutor() as executor:
Спасибо огромное! Оказывается, ларчик просто открывался :) А я что-то сразу не уловила разницу

2023-11-03 17:58 UTC, IlyaOrlov approved these changes
Отлично!

2023-11-03 17:58 UTC, merged