Задание 10 (1 и 2 часть) к 10 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #153
Opened 2023-11-02 09:40 UTC by Ekaterinka11

Прошу проверить часть 1 задания к 10 лекции

2023-11-02 10:29 UTC, Ekaterinka11 commented
Попробовала сделать 3 задание. Смущает фраза в задании, что каждый поток хранит "приватные данные, доступные ему самому".  Получается, каждый поток хранит разные данные? Как можно указать данные, чтобы каждый поток мог брать отдельную их часть?

2023-11-02 20:09 UTC, IlyaOrlov requested changes
Хорошо, но есть вопросы.

2023-11-02 20:09 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_1.py
> +            if i % x == 0:
Если i % x == 0, то дальнейшие x не стоит даже проверять: i - уже не простое число. Можно сразу делать break. А в стр.13 вместо `if d < 1:` просто написать else к циклу for.

2023-11-02 20:09 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_2.py
> +def find_primes(start=3, end=None):
Проще было find_primes один раз в отдельном файле написать и импортировать во все остальные файлы.

2023-11-02 20:09 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_2.py
> +pr1.start()
Удобней было бы все потоки в один список собрать и работать с ним через циклы for.

2023-11-02 20:09 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_2.py
> +# определенного потока, а во время его работы может добавить результат другого потока.
"а во время его работы может добавить результат другого потока." - эту фразу не очень понял. Кто и к чему может добавить результат другого потока?

2023-11-02 20:26 UTC, IlyaOrlov commented
> Попробовала сделать 3 задание. Смущает фраза в задании, что каждый поток хранит "приватные данные, доступные ему самому". Получается, каждый поток хранит разные данные? Как можно указать данные, чтобы каждый поток мог брать отдельную их часть?

На самом деле, всё, что является локальной переменной в потоке - это всё его приватные данные. 
Ещё вариант - создать глобальную переменную `local = threading.local()` и воспользоваться ей внутри потока:
```python
def hold(data):
    local.value = data
    print(f'Имя потока: {threading.current_thread().name}, хранит данные: {local.value}')
```
У каждого потока, в т.ч. у главного, эта local будет своя. Для проверки можно вывести в самом конце главного потока print(local.__dict__), чтоб увидеть, что в главном потоке у local никакой value не появилось.

2023-11-05 13:54 UTC, Ekaterinka11 commented on Practice/Kashintseva/task10_1_1.py
> +            if i % x == 0:
Поняла, поправила.

2023-11-05 13:54 UTC, Ekaterinka11 commented on Practice/Kashintseva/task10_1_2.py
> +def find_primes(start=3, end=None):
Сделано.

2023-11-05 13:55 UTC, Ekaterinka11 commented on Practice/Kashintseva/task10_1_2.py
> +pr1.start()
Исправила

2023-11-05 14:02 UTC, Ekaterinka11 commented on Practice/Kashintseva/task10_1_2.py
> +# определенного потока, а во время его работы может добавить результат другого потока.
Здесь ошиблась. Скорректировала ответ. 
Главный поток может не дождаться завершения дочерних потоков. То есть он может завершится, а поток еще будет выполняться.

2023-11-06 14:44 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_2.py
> +# определенного потока, а во время его работы может добавить результат другого потока.
На самом деле с завершением главного потока завершается и весь процесс (вся программа). Поэтому дочерние потоки тоже завершатся, хотя и принудительно.

2023-11-06 14:46 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_1_3.py
> +# Соответственно, лучше данную задачу выполнять последовательно.
Согласен, но, судя по полученному времени выполнения, процессы всё-таки побеждают? 4.51 против 5.54:)

2023-11-06 14:46 UTC, IlyaOrlov commented on Practice/Kashintseva/task10_2.py
> +    if isinstance(a, str) and isinstance(b, str):
В стр.8  и 10 лучше elif, чтоб не выполнять лишних проверок.

2023-11-06 14:47 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-06 14:47 UTC, merged