Tgridneva first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #154
Opened 2023-11-02 12:47 UTC by TomaGridneva

задания к 10 лекции

2023-11-02 20:37 UTC, IlyaOrlov requested changes
Есть замечания и вопросы.

2023-11-02 20:37 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_1.py
> +thread1.start()
Не проще ли все потоки в список сложить, чтоб их потом через циклы for потом организованно запускать и джойнить?
То же самое справедливо и для процессов.

2023-11-02 20:37 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_1.py
> +process1 = multiprocessing.Process(target=find_primes, args=(3, 10000))
А у Вас какая операционная система, что процессы без `if __name__ == "__main__":` запускаются?

2023-11-02 20:37 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +def add_lists(a, b):
Нужна одна функция, умеющая работать со всеми приведенными типами аргументов, а не три!

2023-11-02 20:37 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
Какое же из приведённых в этом файле решений подойдёт для параллельного запуска функции с различными наборами аргументов?

2023-11-02 20:37 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_1.py
Ожидаются ответы на вопросы к заданию и выводы о скорости работы каждого из решений.

2023-11-06 10:36 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
> +def add_lists(a, b):
переписала код

2023-11-06 10:38 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
второе решение с многопоточностью. тут можно запустить функцию с разными аргументами и получать ответ в произвольном порядке

2023-11-06 10:39 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_1.py
> +process1 = multiprocessing.Process(target=find_primes, args=(3, 10000))
ios

2023-11-06 18:52 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
Тут потоки записывают результат в один общий список без мьютексов!!! Это хорошо, что GIL есть, а то в этом списке неизвестно что бы оказалось. Представьте, что несколько человек начнут одновременно общий документ по сети редактировать! Тогда уж надо потокобезопасную очередь использовать для хранения общего результата.
А ещё лучше использовать пул с методом map. Причём, пул процессов!

2023-11-06 18:52 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
Увы и ах! Параллелизм в Python через потоки нереализуем, поэтому, чтоб удовлетворить требование задачи о параллельности, надо использовать процессы.

2023-11-06 18:57 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_1.py
> +process1 = multiprocessing.Process(target=find_primes, args=(3, 10000))
Понятно) Но всё равно рекомендую привыкать к использованию `if __name__ == "__main__":`. Т.к. на macOS уже сделали запуск процессов по умолчанию через spawn. То же ждёт и ios - https://peps.python.org/pep-0730/

2023-11-15 05:12 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_1.py
> +process1 = multiprocessing.Process(target=find_primes, args=(3, 10000))
хорошо, учту

2023-11-15 05:12 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
поняла

2023-11-15 05:30 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_1.py
> +thread1.start()
переписала код

2023-11-15 05:33 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_1.py
Выводы:
1.распараллеливание по потокам не дает преимущества во времени в задачах CPU- bound (происходит это по причине GIL - глобальной блокировки интерпретатора (каждый из потоков полностью "захватывает" процессор для своего выполнения) 
2.распараллеливание по процессам также не дало преимуществ в данной задаче, поскольку расходы на создание процессов не "окупились", объемы вычислений не достаточно велики для вычисления в разных процессах.При добавлении еще одного порядка (не 10 тысяч, а 100 и т.д.), разница становится ощутима (время выполнения последовательного кода практически в 2 раза превышает время выполнения кода по процессам

2023-11-15 05:38 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
вроде бы поняла вас и поменяла

2023-11-15 16:43 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
ThreadPool - это всё равно пул потоков! А пул процессов - это Pool из библиотеки multiprocessing. В лекции есть пример, как этот пул создать, и как ему через map функцию для вычислений передать.

2023-11-15 16:45 UTC, IlyaOrlov commented on Practice/tgridneva/практика 11.py
> +
Код клиента надо всё-таки в отдельный файл вынести!

2023-11-15 16:48 UTC, IlyaOrlov commented on Practice/tgridneva/практика 11.py
> +    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Здесь и в клиенте с сокетом лучше работать через менеджер контекста:
```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server_socket :
```
тогда .close() у этого сокета вызывать не нужно.
Аналогично и с client_socket в стр. 22:
```python
client_socket, client_address = server_socket.accept()
with client_socket:
    print(f'Connection established with {client_address[0]}:{client_address[1]}')
    handle_client(client_socket)
```

2023-11-15 16:49 UTC, IlyaOrlov requested changes
Остались некоторые замечания и добавились новые.

2023-11-15 19:29 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
попробовать использовать ProcessPoolExecutor?

2023-11-15 19:43 UTC, TomaGridneva commented on Practice/tgridneva/практика 11.py
> +
изначально объединила только для гита, переделала в 2 разных файла

2023-11-15 19:43 UTC, TomaGridneva commented on Practice/tgridneva/практика 11.py
> +    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
исправила

2023-11-15 20:08 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
Просто Pool:
```python
from multiprocessing import Pool


if __name__ == '__main__':
    with Pool(processes=3) as pool:
        res = pool.map(process_arguments, argument_sets)
        print(res)
```

2023-11-15 20:15 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
Хотя и для ProcessPoolExecutor есть аналогичный интерфейс. Главное, не через потоки и не через пул потоков.

2023-11-15 20:16 UTC, IlyaOrlov commented on Practice/tgridneva/практика 12.py
> +        columns = [column[0] for column in cursor.description]
Чтоб не заморачиваться с columns, нужно перед вызовом cursor.execute написать cursor.row_factory = sqlite3.Row, и вытаскивать значения, как dict(row) for row in cursor.fetchall()

2023-11-16 09:03 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
> +    thread = threading.Thread(target=lambda: results.append(add_arguments(*args)))
поменяла

2023-11-16 09:07 UTC, TomaGridneva commented on Practice/tgridneva/практика 12.py
> +        columns = [column[0] for column in cursor.description]
поменяла

2023-11-16 19:34 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +def add_all(d):
А что переписали функцию? С ней-то никаких проблем не было.

2023-11-16 19:35 UTC, IlyaOrlov commented on Practice/tgridneva/Практика 10_2.py
> +    pool = Pool(processes=4)
Лучше всё-таки работать с пулом через менеджер контекста:
```python
    with Pool(processes=4) as pool:
        pool.map(add_all, data)
```
чтоб пул корректно закрылся.

2023-11-16 19:37 UTC, IlyaOrlov commented on Practice/tgridneva/практика 12.py
> +        self.connection.row_factory = sqlite3.Row
Если устанавливаете row_factory для всего connection, а не для курсора, имеет смысл это выполнить сразу после создания connection в `__init__`.

2023-11-19 13:14 UTC, TomaGridneva commented on Practice/tgridneva/Практика 10_2.py
> +    pool = Pool(processes=4)
переписала

2023-11-19 13:19 UTC, TomaGridneva commented on Practice/tgridneva/практика 12.py
> +        self.connection.row_factory = sqlite3.Row
испраивоа

2023-11-19 14:24 UTC, IlyaOrlov approved these changes
Отлично. Замечаний нет.

2023-11-19 14:24 UTC, merged