Mtroshin first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #155
Opened 2023-11-02 21:18 UTC by TroshinMike

2023-11-03 11:16 UTC, IlyaOrlov requested changes
Хорошо. Только несколько комментариев по мелочи.

2023-11-03 11:16 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/1.py
> +with (open("README.md", 'r', encoding="UTF-8")) as source_file:
Внешние скобки лишние.

2023-11-03 11:16 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/1.py
> +res = re.findall(search_str, s)
Безопасней всё-таки не считывать сразу всё содержимое файла, а читать и анализировать его содержимое построчно.

2023-11-03 11:16 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/3.py
> +    for (path, dirs, files) in os.walk('3_folder'):
Наверное, здесь предполагалось указать переменную folder?
И в скобки path, dirs, files брать не обязательно.

2023-11-03 11:16 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_7/1.py
> +    def shoot (self):
Лишний пробел перед скобкой.

2023-11-04 19:09 UTC, TroshinMike commented
Какие-то конфликты пошли после пуша правки по 7 лекции..(

2023-11-04 20:28 UTC, IlyaOrlov requested changes
Есть ещё небольшое предложение по оптимизации.
А чтоб конфликты ушли, надо подтянуть изменения из main (Git->Pull->origin main), разрешить все конфликты локально (можно выбрать в открывшемся окне кнопку Accept Yours) и сделать Git->Push.

2023-11-04 20:28 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Удобней было бы не завязываться на counts, а просто записать в файл список humans целиком (pickle.dump(humans), file) и считать его так же, целиком.

2023-11-06 12:31 UTC, TroshinMike commented
>А чтоб конфликты ушли, надо подтянуть изменения из main (Git->Pull->origin main), разрешить все конфликты локально (можно выбрать в открывшемся окне кнопку Accept Yours) и сделать Git->Push.

Спасибо, сперва не получалось, но после удаления нескольких тестовых файлов - сработало:)

2023-11-06 12:32 UTC, TroshinMike commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Не получается так сделать. Сейчас сделаю новый коммит, в котором это выдает ошибки уже...Видимо какой-то нюанс там)

2023-11-06 19:04 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/4.py
> +            pickle.dumps(humans, file)
pickle.dump**s** - это, чтоб строку получить, а для записи в файл надо pickle.dump(humans, file)

2023-11-06 19:05 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Надо dump вместо dumps:)

2023-11-07 22:09 UTC, TroshinMike commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
В таком случае работает! НО добавляется вот так:( 
 [<__main__.Human object at 0x00000170E15D7FD0>, <__main__.Human object at 0x00000170E15F2450>, <__main__.Human object at 0x00000170E15F1F10>, <__main__.Human object at 0x00000170E15F24D0>, <__main__.Human object at 0x00000170E15F1F90>]

2023-11-08 09:33 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Не добавляется, а представляется при выводе на экран)
За представление экземпляра отвечает магический метод `__repr__`. Добавьте такой метод в Human (вместо print_info), и всё красиво напечатается:
```python
    def __repr__(self):
        return f"Name: {self.name}, Surname: {self.surname}, Age: {self.age}, City: {self.city}, Country: {self.country}"
```

2023-11-08 19:16 UTC, TroshinMike commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Но и сохранялось в дамп такое представление неполное, да?
Внес правки, да, теперь все ок) Спасибо! :)

2023-11-08 20:15 UTC, IlyaOrlov commented on Practice/mtroshin/Module 10/4.py
> +        while i < counts:
Нет. Сохранялся весь список экземпляров целиком.
Если даже без всяких дампов Вы просто вызовете print(humans) - напечатается то же самое: набор классов и адресов. Python не знаете, как представлять на экране объекты пользовательских типов данных (классы), чтоб  было удобно пользователю (это вообще достаточно субъективный момент). Поэтому он использует самый универсальный подход - печатать то, что точно есть у каждого объекта: класс и адрес.

2023-11-08 20:16 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-08 20:16 UTC, merged