Ssharygina first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #156
Opened 2023-11-03 08:45 UTC by SvetlanaSharygina

Практические задания из лекции 9

2023-11-03 11:27 UTC, IlyaOrlov requested changes
Есть пара комментариев по мелочи.

2023-11-03 11:27 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina9.1.py
> +    line = g_com(r"C:\Users\user\PycharmProjects\PythonCourse2.0_September23\Practice\README.md")
Лучше указывать относительный путь (r"..\README.md"), т.к. вероятность, что этот путь будет актуален и на другой машине, выше, чем у абсолютного пути (r"C:\Users\user\PycharmProjects\PythonCourse2.0_September23\Practice\README.md").

2023-11-03 11:27 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina9.1.py
> +    print(list(set(re.findall(r'git\s[a-z]*\s-{1,2}\w+\s\w*\.*\w*', line))))
Безопасней всё-таки анализировать файл построчно, не считывая его в память целиком.

2023-11-06 11:05 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina9.1.py
> +    line = g_com(r"C:\Users\user\PycharmProjects\PythonCourse2.0_September23\Practice\README.md")
Исправлено

2023-11-06 11:05 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina9.1.py
> +    print(list(set(re.findall(r'git\s[a-z]*\s-{1,2}\w+\s\w*\.*\w*', line))))
Исправлено

2023-11-06 19:01 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-06 19:01 UTC, merged