Модуль 10.
IlyaOrlov/PythonCourse2.0_September23 pull request #158
Opened 2023-11-03 11:12 UTC by mtvtanic

2023-11-03 11:36 UTC, IlyaOrlov requested changes
Хорошо. Но есть пара вопросов.

2023-11-03 11:36 UTC, IlyaOrlov commented on Practice/ermakova/control10.1.py
> +    for i in range(start, end + 1, 2):
Почему здесь шаг 2 и чем обусловлена отдельная проверка `if (i > 10) and (i % 10 == 5)`? Просто интересно)

2023-11-03 11:36 UTC, IlyaOrlov commented on Practice/ermakova/control10.2.py
> +        if isinstance(arg, str):
Наверное, здесь и ниже стоит использовать elif, чтоб избежать лишних проверок.

2023-11-03 12:36 UTC, mtvtanic commented on Practice/ermakova/control10.1.py
> +    for i in range(start, end + 1, 2):
Здесь проверяется только те числа, которые заканчиваются на 1, 3, 7 или 9 (так как остальные очевидно делятся на 2 или 5). Шаг два, потому что четные числа точно делятся на 2)а до 10, там даже это рассматривать не надо)

2023-11-03 12:36 UTC, mtvtanic commented on Practice/ermakova/control10.2.py
> +        if isinstance(arg, str):
Спасибо, сейчас поправлю!

2023-11-03 15:25 UTC, IlyaOrlov commented on Practice/ermakova/control10.1.py
> +    for i in range(start, end + 1, 2):
ОК. Если проверять числа, начиная с 3, то способ работает, т.к. lst постепенно накапливает простые делители. Но для диапазонов 10001-20000, 20001-30000, т.к. lst изначально пустой, в него попадают и непростые числа, например, 10001, 10003, и т.д.
Также, в общем случае нет гарантий, что start - это всегда нечётное число.

2023-11-03 15:25 UTC, IlyaOrlov commented on Practice/ermakova/control10.1.py
> +            if j * j - 1 > i:
Код в стр. 12-14 на результат не влияет.

2023-11-04 16:21 UTC, mtvtanic commented on Practice/ermakova/control10.1.py
> +    for i in range(start, end + 1, 2):
Поняла) Жаль, понравилось это решение. проверяла как раз на первом диапазоне) Сейчас, конечно, поняла, в чем проблема, спасибо! Попробую стандартно через корень!

2023-11-04 17:22 UTC, mtvtanic commented on Practice/ermakova/control10.1.py
> +    for i in range(start, end + 1, 2):
Вроде получилось, добавила вывод каждого с новой строки,, чтобы было наглядней.

2023-11-04 18:36 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-04 18:36 UTC, merged