Задание к 8 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #160
Opened 2023-11-05 07:13 UTC by yilya21q

2023-11-06 14:40 UTC, IlyaOrlov requested changes
Есть существенное замечание по итератору!

2023-11-06 14:40 UTC, IlyaOrlov commented on Practice/platonova/lec_8.1.py
> +        self.paragraphs = text.split(paragraph_separator)
Сразу формируя в памяти помимо исходного текста ещё и список соответствующего размера, мы нивелируем весь смысл итератора. Вместо этого надо читать в `__next__` исходный текст (text) посимвольно, накапливая прочитанные символы во вспомогательной переменной (буфере) и возвращая этот буфер всякий раз, когда встретится символ параграфа.

2023-11-10 04:33 UTC, yilya21q commented on Practice/platonova/lec_8.1.py
> +        self.paragraphs = text.split(paragraph_separator)
Скорректировала

2023-11-10 08:06 UTC, IlyaOrlov requested changes
Ещё пара комментариев по мелочи.

2023-11-10 08:06 UTC, IlyaOrlov commented on Practice/platonova/lec_8.1.py
> +        raise StopIteration()
Скобки в конце необязательны.

2023-11-10 08:06 UTC, IlyaOrlov commented on Practice/platonova/lec_8.1.py
> +                self.buffer = ''
buffer не нужно делать атрибутом экземпляра. Достаточно локальной переменной (без self). Нам же этот буфер нужен только на время работы `__next__`, а при следующем вызове `__next__` мы снова этот буфер с нуля формируем.

2023-11-13 10:44 UTC, yilya21q commented on Practice/platonova/lec_8.1.py
> +        raise StopIteration()
Исправила

2023-11-13 10:44 UTC, yilya21q commented on Practice/platonova/lec_8.1.py
> +                self.buffer = ''
Исправила

2023-11-13 19:55 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-13 19:55 UTC, merged