Модуль 11. Второе задание.
IlyaOrlov/PythonCourse2.0_September23 pull request #166
Opened 2023-11-09 12:48 UTC by mtvtanic

Попробовала через классы.

2023-11-09 20:00 UTC, IlyaOrlov requested changes
Супер! Оставил только пару комментариев.

2023-11-09 20:00 UTC, IlyaOrlov commented on Practice/ermakova/control11.2server.py
> +        print('Closed connection from {}'.format(self._address))
Понимаю, что в лекциях с этим тоже не всё гладко, но лучше использовать какой-то один стиль в файле: либо format, либо f-строку.

2023-11-09 20:00 UTC, IlyaOrlov commented on Practice/ermakova/control11.2client.py
> +        time.sleep(5)
Этот sleep же для эксперимента, как в лекции?

2023-11-09 20:12 UTC, mtvtanic commented on Practice/ermakova/control11.2client.py
> +        time.sleep(5)
Ну да) изменила настройки при запуске клиента, чтобы посмотреть как и сколько одновременно запуститься. Не надо, убрать лучше?

2023-11-09 20:15 UTC, IlyaOrlov commented on Practice/ermakova/control11.2client.py
> +        time.sleep(5)
Можно закомментировать и добавить пояснение (тоже комментарием)

2023-11-09 20:36 UTC, mtvtanic commented on Practice/ermakova/control11.2client.py
> +        time.sleep(5)
Я так поняла,здесь ведь это роли не играет(ожидание) потому что мы вводим вручную данные) и бесконечный цикл True пока не закончим сами. Так что тут можно сколько угодно клиентов в очередь подключить? Пробовала изначально просто много сделать подряд.

2023-11-10 07:42 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-11-10 07:42 UTC, merged