modul12_lesson11_3
IlyaOrlov/PythonCourse2.0_September23 pull request #167
Opened 2023-11-09 14:34 UTC by RemoSet

2023-11-09 20:06 UTC, IlyaOrlov requested changes
Есть предложение по оптимизации.

2023-11-09 20:06 UTC, IlyaOrlov commented on Practice/amarinin/Modul_12/modul12_lesson11_3.py
> +    supp = (x for i in web_page.split() if len(x := re.findall(r'href="http.?://.*"', i)))
Разделять web_page на отдельные слова - это большой список получится! Лучше findall сразу к web_page применить, только паттерн уточнить. А то, что найдётся (это всяко малая часть), уже дополнительно обработать.

2023-11-10 08:01 UTC, IlyaOrlov requested changes
Всё супер! Только один нюанс остался.

2023-11-10 08:01 UTC, IlyaOrlov commented on Practice/amarinin/Modul_12/modul12_lesson11_3.py
> +    supp = (re.findall(r'href="(h.*?)"', web_page))
Внешние скобки лишние. Увы, но так ни кортеж, ни генератор из списка, возвращённого findall, не получится (нужно списковое выражение). Да и не нужны они, т.к. список уже свою память занял.

2023-11-10 08:19 UTC, RemoSet commented on Practice/amarinin/Modul_12/modul12_lesson11_3.py
> +    supp = (re.findall(r'href="(h.*?)"', web_page))
Старые привычки.. типа масло маслом не испортишь ))). Ну, привычнее что то в скобки собирать и там уж куда то запуливать. А то, что в памяти уже что то выделено и туда все сваливается... это другая картина мира )).
Скобки уберу. Заскобивал разными скобками, а вот совсем их убрать.. не случилось )

2023-11-13 19:50 UTC, IlyaOrlov commented on Practice/amarinin/Modul_13/modul13_lesson12_1.py
> +        name_table = "CREATE TABLE " + input("Имя таблицы : ").lower().strip()
Понятно, что в случае с созданием таблицы подстановку имени в запрос через execute сделать не получится. Но оно и некритично, т.к. запрос на создание таблицы делается, как правило, под конкретную таблицу.
На практике такое динамическое формирование запроса на создание таблицы не только избыточно, но и опасно, ибо неизвестно, что там пользователь может ввести, а схема данных - это фундамент всей БД.
Можно этот код оставить, как свидетельство полёта мысли, но в реальном проекте лучше не применять.

2023-11-13 19:52 UTC, IlyaOrlov commented on Practice/amarinin/Modul_13/modul13_lesson12_1.py
> +        schema = f"INSERT INTO {table_name} ({', '.join(column_names[1:])}) VALUES ({', '.join(values_column)})"
Ну а здесь точно не следует формировать запрос через конкатенацию. Иначе получаем уязвимость к SQL-инъекциям.

2023-11-13 19:53 UTC, IlyaOrlov commented on Practice/amarinin/Modul_13/modul13_lesson12_1.py
> +        schema = f"SELECT {fields} from {table_name}"
Уязвимость для SQL-инъекций.

2023-11-13 19:53 UTC, IlyaOrlov commented on Practice/amarinin/Modul_13/modul13_lesson12_1.py
> +    with f:
`with MySqlManager("my_data.db") as f:`

2023-11-15 16:32 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-15 16:32 UTC, merged