+ ДЗ по параллельному программированию (лекция 10)
IlyaOrlov/PythonCourse2.0_September23 pull request #168
Opened 2023-11-09 20:17 UTC by TroshinMike

2023-11-10 07:52 UTC, IlyaOrlov requested changes
Хорошо, но есть замечания.

2023-11-10 07:52 UTC, IlyaOrlov commented on Practice/mtroshin/Module_12/1.py
> +if __name__ == '__main__':
Код в строках 25-43 будет запускаться во всех дочерних процессах! Т.е. каждый процесс будет искать простые числа не только в своём диапазоне, но и во всех остальных, да ещё и по нескольку раз, да ещё и с применением потоков! У процессов при таком раскладе вообще шансов нет)
Надо этот код тоже под `if __name__ == "__main__"` поместить.

2023-11-10 07:52 UTC, IlyaOrlov commented on Practice/mtroshin/Module_12/1.py
> +thr1 = threading.Thread(target=find_primes, args=(10000, 1))
Не удобней ли все потоки сложить в список, а потом просто по этому списку пробегаться, вызывая start или join? Если понадобится добавить ещё потоков, достаточно будет их добавить только в этот список.
То же самое справедливо и для процессов.

2023-11-15 11:20 UTC, IlyaOrlov requested changes
ОК. А по оставшемуся [вопросу ](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/168#discussion_r1389033795)что скажете?

2023-11-16 09:35 UTC, TroshinMike commented on Practice/mtroshin/Module_12/1.py
> +thr1 = threading.Thread(target=find_primes, args=(10000, 1))
Упустил сперва этот вопрос. Просто было проще написать топорно:) для текущей задачи) Сейчас попробую через список)

2023-11-16 19:49 UTC, IlyaOrlov requested changes
Алекс-Юстасу: Есть небольшие замечания по новому коду:)

2023-11-16 19:49 UTC, IlyaOrlov commented on Practice/mtroshin/Module_13/1_client.py
> +s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
С сокетом лучше работать через менеджер контекста:
```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
```
Тогда s.close() писать не нужно, и сокет закроется корректно, даже если возникнут какие-либо исключения.

То же самое справедливо и для серверного кода.

2023-11-16 19:49 UTC, IlyaOrlov commented on Practice/mtroshin/Module_13/1_server.py
> +    conn, addr = s.accept()
Здесь лучше написать так:
```python
conn, addr = s.accept()
with conn:
```
и conn.close() убрать.

2023-11-16 19:49 UTC, IlyaOrlov commented on Practice/mtroshin/Module_13/1_server.py
> +        text = re.sub(item, dict_code[item], text)
Да тут и text.replace сойдёт. Но это непринципиально.

2023-11-21 08:20 UTC, IlyaOrlov reviewed
Краткость - сестра таланта👍 По [Module_15.txt](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/168/files/5b1ea0d4fd98d227468809c6cd4e78d2f2b9806a..6a7cbe1d66b8d72908e4ec12172131e79bb7ba58#diff-d3707b96055cd3b1905cdf38f1eaeb6a3b18358745d7546d9b43376c1bc6a193) замечаний нет.

2023-11-22 10:19 UTC, IlyaOrlov reviewed
По [Module_14.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/168/files#diff-4095970941ec663a0f8d60dcc1af345163149826fa5c8fa39f5aabae75824d09) замечаний нет.

2023-11-22 16:29 UTC, IlyaOrlov commented on Practice/mtroshin/exam/10.py
> +    if not nums[i-k] % 10 == 0:
Лучше `if nums[i-k] % 10 !=0:`

2023-11-22 16:37 UTC, TroshinMike commented on Practice/mtroshin/Module_13/1_server.py
> +        text = re.sub(item, dict_code[item], text)
Спасибо за все правки! Внес :)

2023-11-22 16:40 UTC, TroshinMike commented on Practice/mtroshin/exam/10.py
> +    if not nums[i-k] % 10 == 0:
Исправил:)

2023-11-22 20:44 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-22 20:44 UTC, merged