домашнее задание 1
IlyaOrlov/PythonCourse2.0_September23 pull request #17
Opened 2023-08-28 09:10 UTC by TomaGridneva

2023-08-28 09:54 UTC, Tetrackon requested changes
Одна ошибка, которую надо поправить, и два комментария, с которыми нужно просто ознакомиться.

2023-08-28 09:54 UTC, Tetrackon commented on Practice/tgridneva/3pt.py
> +print(int(a) +int(b))
Математические операции принято выделять с обеих сторон пробелами, по pep8. Добавьте пробел после "+"

2023-08-28 09:54 UTC, Tetrackon commented on Practice/tgridneva/ecto.py
> +
Ого!) Сразу с циклом))) В принципе, задание состояло в том что нужно вывести то что ввёл пользователь, дополнив его чем-то своим (конкретно словом Echo), так что Вы могли остановиться на второй строчке. Цикл был не нужен, но почему бы и нет?)))

2023-08-31 07:53 UTC, Tetrackon requested changes
Всё хорошо, но есть небольшие замечания.

2023-08-31 07:53 UTC, Tetrackon commented on Practice/tgridneva/pcactice 2 lec(2).py
> +result = int(diff) / int(distance)
Результатом сложения, вычитания и умножения целых чисел - будет всегда целое число. Поэтому преобразовывать diff в int не нужно.

2023-08-31 07:53 UTC, Tetrackon commented on Practice/tgridneva/practice 2 lec(3).py
> +        # def generatename(self, seed=time()):
Случайно захватили функцию в комментарий

2023-08-31 07:53 UTC, Tetrackon commented on Practice/tgridneva/practice 2 lec(3).py
> +    shuffler = Shuffler()
Это не функция, это переменная, которой присваивается экземпляр класса :) Но тут Вы почти правы. Переменные принято называть со строчных букв, если это не константы.

2023-08-31 09:12 UTC, IlyaOrlov requested changes
Ещё небольшой комментарий

2023-08-31 09:12 UTC, IlyaOrlov commented on Practice/tgridneva/practice 2 lec(3).py
> +        def generatename(self, seed=time()):
Комментарий удалили, но функция съехала вправо.

2023-08-31 19:43 UTC, IlyaOrlov requested changes
Добавил новые небольшие замечания.

2023-08-31 19:43 UTC, IlyaOrlov commented on Practice/tgridneva/practice 3(1).py
> +sideA = int(input("Длина: "))
Названия переменных sideA и sideB лучше поменять на side_a и side_b, чтоб соответствовало [PEP8](https://peps.python.org/pep-0008/#descriptive-naming-styles:~:text=Function%20names%20should,as%20function%20names.).

2023-08-31 19:43 UTC, IlyaOrlov commented on Practice/tgridneva/practice 3(2).py
> +V = s / t
Большая V тоже не особо соответствует [PEP8](https://peps.python.org/pep-0008/#descriptive-naming-styles:~:text=Function%20names%20should,as%20function%20names.).

2023-08-31 19:43 UTC, IlyaOrlov commented on Practice/tgridneva/practice 3(2).py
> +print("Средняя скорость: ",V)
А что не форматная строка? С ней же, вроде, аккуратней получается.

2023-09-04 09:45 UTC, merged