Домашнее задание 1 к 11 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #170
Opened 2023-11-10 12:18 UTC by Ekaterinka11

Попробовала 1 задание сделать 2 способами.

2023-11-10 14:34 UTC, IlyaOrlov requested changes
Супер! Вариант с классами, конечно, изящней и перспективней.
Только пару вопросов оставил.

2023-11-10 14:34 UTC, IlyaOrlov commented on Practice/Kashintseva/task11_1_client2.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
А что здесь от менеджера контекста отказались?
`with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as self._socket:`

2023-11-10 14:34 UTC, IlyaOrlov commented on Practice/Kashintseva/task11_1_serv2.py
> +                        c1 += sh[i] + " "
Может слова для отправки обратно тоже через запятую собирать? А то границы переведенных слов неоднозначными могут получиться, как, например, в случае с Нижним Новгородом.

2023-11-11 06:27 UTC, Ekaterinka11 commented on Practice/Kashintseva/task11_1_client2.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Хотела, но забыла. Поправила, спасибо!

2023-11-11 06:35 UTC, Ekaterinka11 commented on Practice/Kashintseva/task11_1_serv2.py
> +                        c1 += sh[i] + " "
Согласна. Поправила на запятую.

2023-11-11 19:57 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-11 19:57 UTC, merged