Homework lecture 11(task11_2_user/server/client)
IlyaOrlov/PythonCourse2.0_September23 pull request #172
Opened 2023-11-11 10:54 UTC by JulMakarova

2023-11-11 20:17 UTC, IlyaOrlov requested changes
Хорошо. Есть пара предложений по оптимизации.

2023-11-11 20:17 UTC, IlyaOrlov commented on Practice/julmakarova/task11_2_server.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Здесь мы не можем работать с сокетом через менеджер контекста, т.к. закрываться он должен в другом методе. Но если вдруг случится какое-то непредусмотренное исключение, программа аварийно закроется, метод stop() не вызовется, то сокет останется неосвобождённым. Что же делать?
Когда происходит удаление объекта (явно, через механизм подсчёта ссылок или сборщиком мусора), вызывается метод `__del__` (деструктор объекта), если он определён, какое бы исключение ни произошло. Мы можем определить этом метод и продублировать в нём закрытие сокета:
```python
def __del__(self):
    self._socket.close()
```
Данное решение можно применять во всех ситуациях, когда занятие и освобождение ресурса выполняются в разных методах объекта. Это называется [идиомой RAII](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D0%B0_%D0%B5%D1%81%D1%82%D1%8C_%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F).

2023-11-12 18:38 UTC, JulMakarova commented on Practice/julmakarova/task11_2_client.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Исправила.

2023-11-12 18:39 UTC, JulMakarova commented on Practice/julmakarova/task11_2_server.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Спасибо за замечание, об этом действительно не задумывалась, теперь буду знать)

2023-11-12 20:10 UTC, IlyaOrlov commented on Practice/julmakarova/task11_2_client.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Только лучше сразу:
```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as self._socket:
```
То же самое, но короче и без доп. переменной.

2023-11-13 10:21 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-13 10:21 UTC, merged

2023-11-13 10:23 UTC, JulMakarova commented on Practice/julmakarova/task11_2_client.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Думала, что в таком случае в атрибут экземпляра _socket не запишется созданный сокет. Была уверена, что переменная после as используется лишь как псевдоним для обращения к сокету в данном менеджере контекста.
Буду знать,спасибо)