Лекция 11 задание 2
IlyaOrlov/PythonCourse2.0_September23 pull request #173
Opened 2023-11-12 04:54 UTC by lvladimirova

Попробовала сделать 2 задание для интереса. В процессе решения столкнулась с ошибкой "EOFError: Ran out of input". Начиталась про её решение через байтовые строки и метод b''.join(), который объединяет все элементы списка `data` в одну байтовую строку. Вроде как всё заработало

2023-11-12 18:23 UTC, IlyaOrlov requested changes
Хорошо. Но есть вопросы и предложения.

2023-11-12 18:23 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
В чём смысл цикла здесь, если мы возвращаем первый же message?
Как вариант, эту функцию можно генератором сделать, чтоб вытаскивать данные по сети порционно, если их размер превышает размер буфера (4096)?

2023-11-12 18:23 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_19/task_11_2/server.py
> +        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Здесь и в сокете клиента мы не можем работать с сокетом через менеджер контекста, т.к. закрываться он должен в другом методе (stop или disconnect). Но если вдруг случится какое-то непредусмотренное исключение, программа аварийно закроется, метод stop() или disconnect() не вызовутся, и сокет останется неосвобождённым. Что делать?
Когда происходит удаление объекта (явно, через механизм подсчёта ссылок или сборщиком мусора), вызывается метод `__del__` (деструктор объекта), если он определён, какое бы исключение ни произошло. Мы можем определить этом метод и продублировать в нём закрытие сокета:
```python
def __del__(self):
    self._socket.close()
```
Данное решение можно применять во всех ситуациях, когда занятие и освобождение ресурса выполняются в разных методах объекта. Это называется [идиомой RAII](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D0%B0_%D0%B5%D1%81%D1%82%D1%8C_%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F).

2023-11-12 18:23 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_19/task_11_2/server.py
> +                    message = f'Добро пожаловать, {user.name}! Ваш возраст - {user.age}'
user используется и для хранения только что полученных по сети данных пользователя, и для хранения данных очередного пользователя в списке connected_users (в цикле выше). Если будет передано несколько пользователей, данные какого user здесь должны вывестись?

2023-11-13 09:07 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/server.py
> +                    message = f'Добро пожаловать, {user.name}! Ваш возраст - {user.age}'
Сама уже запуталась в user - ах :) изменила название переменной для хранения только что полученных данных пользователя

2023-11-13 17:01 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Окончательно запуталась, как вывести сообщение от сервера для клиента. Убрала вообще от греха подальше. Пока идей нет, как выйти из этой ситуации :(

2023-11-13 17:39 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Всё, доисправлялась до того, что код вообще перестал работать :(

2023-11-13 20:07 UTC, IlyaOrlov requested changes
А файл [server.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/173/files#diff-bb689b8d644ea04ce767c56ed6f4efa5c62f34d3e28630c8550f190336fde478) уже неактуален? Может, его тогда как-то удалить/закомментировать/обозначить?

2023-11-13 20:10 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Так надо просто отправить ответ с сервера, а в клиенте его получить) Давайте только определимся, с каким кодом сервера работаем, и какая ошибка сейчас возникает?

2023-11-14 07:39 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Давайте начнём всё сначала :) С первого сервера. В клиентском приложении был код:
    def receive_message(self):
        data = []
        while True:
            x = self._socket.recv(4096)
            if not x:
                break
            data.append(x)
            message = pickle.loads(b''.join(data))
            return message

Мне интересно, можно ли как-то более красиво сделать? И я не могу сделать его через генератор и yield :(

2023-11-14 08:15 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Всё, откатила назад. Теперь спасайте, пожалуйста :)

2023-11-14 11:03 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Так всё ж работает, только receive_message стоит переписать покороче:
```python
    def receive_message(self):
        data = self._socket.recv(4096)
        message = pickle.loads(data)
        return message
```
Ну или можно реализовать отправку и получение данных в одном методе клиента. Иначе говоря, инкапсулировать детали протокола обмена информацией в классе MyClient. Чтоб основной код не мог управлять последовательностью отправки и приёма данных, вызывая send и receive, как ему хочется.

2023-11-14 13:08 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_19/task_11_2/klient.py
> +        while True:
Спасибо большое! Поправила :)

2023-11-14 17:36 UTC, lvladimirova commented
Как смогла сделала ещё 1 задание из 12 лекции. Строго не судите :)

2023-11-14 19:52 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_21/12_1.py
> +        self.cursor.execute('''
Тройные кавычки `'''` принято использовать только для документирования модулей, функций и классов (так называемые [docstrings](https://peps.python.org/pep-0257/)).

2023-11-14 19:54 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_21/12_1.py
> +        self.cursor.execute(query, params)
Если перед вызовом execute написать `self.cursor.row_factory = sqlite3.Row`, то можно columns отдельно не вытаскивать а писать сразу `data = [dict(row) for row in self.cursor.fetchall()]`

2023-11-14 19:57 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_21/12_1.py
> +                    write_result_json = db.write("INSERT INTO users (name, age) VALUES (?, ?)", input_data, age)
Если age ввели неправильно, что же мы тут в БД записываем? Видимо, строки 55-56 поехали вправо при копирования.
Кстати, не проще ли было проверять age через isdecimal(), чем с отловом исключений заморачиваться?

2023-11-15 05:41 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_21/12_1.py
> +                    write_result_json = db.write("INSERT INTO users (name, age) VALUES (?, ?)", input_data, age)
Это не строки поехали, это я сама :) Просто вчера написала код, а потом случайно затёрла его и всё заново переделывала :)

2023-11-15 05:42 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_21/12_1.py
> +        self.cursor.execute(query, params)
Интересная штука, поправила

2023-11-15 16:38 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-15 16:38 UTC, merged