Домашнее задание 1 к 12 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #181
Opened 2023-11-15 17:13 UTC by Ekaterinka11

Попробовала сделать 1 задание. Не понимаю, почему выдает ошибку "sqlite3.ProgrammingError: You did not supply a value for binding parameter :child_id.", хотя данный параметр предлагается ввести в основном коде.

2023-11-15 18:09 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания.

2023-11-15 18:09 UTC, IlyaOrlov commented on Practice/Kashintseva/task12_1.py
> +                             {'сhild_id': child_id, 'new_height': new_height})
Похоже, в 'сhild_id' закралась русская буква 'с' :) Отсюда и проблема "You did not supply a value for binding parameter :child_id."

2023-11-16 07:27 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +        return bool(cur.fetchone())
Поняла, спасибо. Добавила.

2023-11-16 07:27 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +            return json.dumps(dict(row))
Поправила.

2023-11-16 07:28 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +                             {'сhild_id': child_id, 'new_height': new_height})
Вооот оно что...спасибо!)

2023-11-16 07:48 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +                             {'сhild_id': child_id, 'new_height': new_height})
А как мне исправить кодировку у json формата? Слова на русском форматируются в другую кодировку. Хотелось бы это исправить.

2023-11-16 19:26 UTC, IlyaOrlov commented on Practice/Kashintseva/task12_1.py
> +                             {'сhild_id': child_id, 'new_height': new_height})
json.dumps(inf, ensure_ascii=False)

2023-11-16 19:30 UTC, IlyaOrlov commented on Practice/Kashintseva/task12_1.py
> +            return json.dumps(dict(row))
Нет! Вместо этого
```python
        for row in cur.fetchall():
            inf = dict(row)
            return json.dumps(inf)
```
должно быть либо так:
```python
       return json.dumps([dict(row) for row in cur.fetchall()])  # формируем список из извлекаемых записей
```
либо так:
```python
       return json.dumps(dict(cur.fetchone()))  # вытаскиваем ровно одну запись
```

2023-11-17 06:15 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +            return json.dumps(dict(row))
Извините...
Сначала поставила cur.fetchone(), т.к. мой конкретный запрос предполагает выведение одной строки, потом исправила на cur.fetchall(), чтобы был код универсальнее, но список не учла.

2023-11-17 06:15 UTC, Ekaterinka11 commented on Practice/Kashintseva/task12_1.py
> +                             {'сhild_id': child_id, 'new_height': new_height})
Спасибо большое.

2023-11-17 09:52 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-17 09:53 UTC, merged