Lvladimirova first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #185
Opened 2023-11-19 13:18 UTC by lvladimirova

Попробовала сделать 2 задание из 13 лекции. Единственное, пока не очень пойму, почему ищется только один раз и выкидывает ошибку, для следующего поиска надо переименовывать папку в Монго. Хотя, наверное, понимаю в подсознании - что пытается подключиться к подключённому. Или что-то типа того

2023-11-19 14:17 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +conn = me.connect('firms')
Это к основному коду относится.

2023-11-19 14:21 UTC, IlyaOrlov commented
> Попробовала сделать 2 задание из 13 лекции. Единственное, пока не очень пойму, почему ищется только один раз и выкидывает ошибку, для следующего поиска надо переименовывать папку в Монго. Хотя, наверное, понимаю в подсознании - что пытается подключиться к подключённому. Или что-то типа того

Так у Вас inn установлен, как уникальный атрибут, а при каждом запуске скрипта Вы выполняете add_company с одним и тем же inn. Как вариант, можно сделать добавление компании (а также,  ввод атрибутов этой компании) через отдельный input от пользователя.

2023-11-19 16:15 UTC, lvladimirova commented
> > Попробовала сделать 2 задание из 13 лекции. Единственное, пока не очень пойму, почему ищется только один раз и выкидывает ошибку, для следующего поиска надо переименовывать папку в Монго. Хотя, наверное, понимаю в подсознании - что пытается подключиться к подключённому. Или что-то типа того
> 
> Так у Вас inn установлен, как уникальный атрибут, а при каждом запуске скрипта Вы выполняете add_company с одним и тем же inn. Как вариант, можно сделать добавление компании (а также, ввод атрибутов этой компании) через отдельный input от пользователя.

Попробовала исправить код. Надеюсь, более-менее получилось

2023-11-19 17:52 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +def search_company(inn):
Определение функции всё-таки стоит вынести к блоку определений функций и классов. А основной код (строки 19-38 занести под `if __name__ == "__main__":`). 
Новый материал не отменяет старых правил!

2023-11-19 17:52 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +    Firms.objects.delete()
Так можно уже не удалять все объекты.

2023-11-19 17:54 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +    company.save()
Хорошо бы сюда ещё повесить try...except, чтоб отлавливать исключения, когда пользователь ввёл уже существующий inn. Если исключение случилось, пишем, что компания с таким inn уже существует, и заходим на новую итерацию цикла.

2023-11-19 17:55 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Здесь используется format, в другом месте - f-строка. Всё-таки стоит придерживаться единого стиля, по крайней мере, в одном файле (f-строка предпочтительней).

2023-11-19 17:56 UTC, IlyaOrlov requested changes
Хорошо. Но ещё есть небольшие замечания и предложения по оптимизации.

2023-11-20 07:00 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +    Firms.objects.delete()
Это я тренировалась по лекции :)  Забыла удалить

2023-11-20 07:01 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Не доглядела

2023-11-20 08:02 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Списывание - это только первый шаг работы над кодом. А дальше идёт анализ, адаптация и оптимизация:)

2023-11-20 08:05 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Что смогла - поправила, пока не придумаю, как и куда лучше try..except повесить

2023-11-20 08:12 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Так прямо на company.save() можно вешать. Именно в этом месте данные в БД отправляются.

2023-11-20 08:12 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Так-то замечаний нет. Но если ещё try..except добавите, будет круто!

2023-11-20 08:25 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Где-то я наошибалась

2023-11-20 12:50 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        if inn_input == "0":
Имеет смысл поставить эту проверку раньше `if Firms.objects(inn=inn_input).count() > 0:`

2023-11-20 12:51 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Почему Вы так считаете?

2023-11-20 14:59 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_22/13_2_1.py
> +        return ("<Firms(inn='{}', "
Нормально всё, Монго отключился у меня просто :) Не выдержал давления

2023-11-20 19:14 UTC, merged