Практическое задание 1 из лекций 12 и 13
IlyaOrlov/PythonCourse2.0_September23 pull request #188
Opened 2023-11-20 15:36 UTC by SvetlanaSharygina

Практическое задание 1 из лекций 12 и 13

2023-11-20 19:27 UTC, IlyaOrlov requested changes
Хорошо. Но есть пара замечаний.

2023-11-20 19:27 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina12.1.py
> +        db.insert()
Согласно заданию, строки SQL запросов должны передаваться "на вход класса-обертки", т.е. как параметры в методы select и insert.

2023-11-20 19:27 UTC, IlyaOrlov commented on Practice/ssharygina/ssharygina13.1.txt
ОК. Только реляционность данных - это немного про другое. Это про то, насколько сложны взаимосвязи между сущностями предметной области. По сути, здесь надо ответить на вопрос: можно ли представить сущности предметной области в виде простого списка словарей или словаря словарей? Если можно, и если с этим удобно будет работать (чтоб отвечать на пользовательские запросы), то степень реляционности данных можно считать малой и использовать NoSQL.

2023-11-21 07:10 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina12.1.py
> +        db.insert()
исправила

2023-11-21 07:10 UTC, SvetlanaSharygina commented on Practice/ssharygina/ssharygina13.1.txt
исправила

2023-11-21 08:24 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-11-21 08:24 UTC, merged