Create task1
IlyaOrlov/PythonCourse2.0_September23 pull request #19
Opened 2023-08-28 14:52 UTC by Ar87tem123456789101112

Всё хорошо.

2023-08-28 18:30 UTC, IlyaOrlov requested changes
Одно небольшое замечание. Ну и в название файла надо добавить .py

2023-08-30 13:01 UTC, Ar87tem123456789101112 commented
принял. Все файлы заменены на "py"

2023-08-30 14:18 UTC, IlyaOrlov commented
> принял. Все файлы заменены на "py"

ОК. Но сюда изменения не дошли. Вы выполнили Git->Commit и Git->Push?

2023-08-31 08:50 UTC, Ar87tem123456789101112 commented
должно прийти.

2023-08-31 09:10 UTC, Ar87tem123456789101112 commented
Прошу прощения, туплю. Сейчас всё норма должно быть.

2023-08-31 09:22 UTC, Ar87tem123456789101112 commented
странно. Эти команды делал Git->Commit и Git->Push и только что выполнил.

2023-08-31 13:45 UTC, closed without merging