Modul14
IlyaOrlov/PythonCourse2.0_September23 pull request #191
Opened 2023-11-22 19:56 UTC by RemoSet

2023-11-22 21:00 UTC, IlyaOrlov requested changes
Замечательно! Хотя есть пара вопросов:)

2023-11-22 21:00 UTC, IlyaOrlov commented on Practice/amarinin/Modul_14/lesson14_1_tests.py
> +        for v, s in {1000: 'M', 900: 'CM', 500: 'D', 400: 'CD', 100: 'C',
Неужели не захотелось поэкспериментировать с параметризацией? Или посчитали, что незачем усложнять простую задачу?:)

2023-11-22 21:33 UTC, RemoSet commented on Practice/amarinin/Modul_14/lesson14_1_roma.py
> +        return e
Бился с assertRaise... )))  а время уходит. Добью.

2023-11-25 09:38 UTC, IlyaOrlov approved these changes
Отлично! Изящно: что с assertRaises, что с параметризацией. Замечаний нет.

2023-11-25 09:38 UTC, merged