домашнее задание 1-3
IlyaOrlov/PythonCourse2.0_September23 pull request #2
Opened 2023-08-24 17:37 UTC by olechka7437

2023-08-24 18:18 UTC, IlyaOrlov requested changes
Есть, что подправить;)

2023-08-24 18:18 UTC, IlyaOrlov commented on Practice/O_Orlova/Task2.py
> +name=input("Введите имя: ")
Вокруг знака "=" нужны пробелы с обеих сторон согласно [PEP8](https://peps.python.org/pep-0008/#:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side%3A%20assignment%20(%3D)%2C%20augmented%20assignment%20(%2B%3D%2C%20%2D%3D%20etc.)%2C%20comparisons%20(%3D%3D%2C%20%3C%2C%20%3E%2C%20!%3D%2C%20%3C%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20in%2C%20not%20in%2C%20is%2C%20is%20not)%2C%20Booleans%20(and%2C%20or%2C%20not).)

2023-08-25 10:46 UTC, olechka7437 commented on Practice/O_Orlova/Task2.py
> +name=input("Введите имя: ")
все исправила, отправила Вам на согласование

2023-08-25 11:06 UTC, IlyaOrlov approved these changes
Отлично! Согласовано)

2023-08-25 11:06 UTC, merged