домашнее задание 1-3: исправление 1
IlyaOrlov/PythonCourse2.0_September23 pull request #21
Opened 2023-08-28 15:11 UTC by olechka7437

2023-08-28 18:20 UTC, IlyaOrlov requested changes
Хорошо. Но есть небольшое замечание.

2023-08-28 18:20 UTC, IlyaOrlov commented on Practice/O_Orlova/Task4.py
> +print(f"Echo, {a}" )
Лишний пробел между кавычкой и скобкой!
Строго говоря, по заданию требовалось двоеточие после **Echo:** На самом деле, просто уточняю, что внутри кавычек может быть любой знак (необязательно запятая). Вот если бы кавычек не было... 
Ну и "кирпич" в конце файла.

2023-08-29 12:06 UTC, IlyaOrlov requested changes
Хорошо. Но есть вопросы!

2023-08-29 12:06 UTC, IlyaOrlov commented on Practice/O_Orlova/pep8task.py
> +import sys
Ожидаются комментарии по найденным ошибкам.

2023-08-29 12:06 UTC, IlyaOrlov commented on Practice/O_Orlova/Tasks_lec3-4/Task_5.py
> +
Что как много пустых строк в конце файла?)

2023-08-29 19:48 UTC, olechka7437 commented on Practice/O_Orlova/Tasks_lec3-4/Task_6.py
> +result = int(diff) / int(distance)         # явно указываем интерпретатору, что надо складывать как числа
принято-сделано

2023-08-29 19:48 UTC, olechka7437 commented on Practice/O_Orlova/pep8task.py
> +import sys
добавила,что нашла

2023-08-29 19:53 UTC, olechka7437 commented on Practice/O_Orlova/Tasks_lec3-4/Task_5.py
> +
это все маленькие ручки сына "помогают"  иногда

2023-08-30 08:41 UTC, IlyaOrlov commented on Practice/O_Orlova/Tasks_lec3-4/Task_5.py
> +def square(r):
О, это называется [парное программирование](https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5):)

2023-08-30 08:41 UTC, IlyaOrlov commented on Practice/O_Orlova/Tasks_lec3-4/Task_5.py
> +
О, это называется парное программирование:)

2023-08-30 08:44 UTC, IlyaOrlov requested changes
Всё супер! Остались мелочи.

2023-08-30 08:44 UTC, IlyaOrlov commented on Practice/O_Orlova/Tasks_lec3-4/Task_5.py
> +radius = input("Введите радиус: ")
После определения функции тоже должно быть две пустые строки (т.е. их надо добавить перед стр.6)

2023-08-30 08:44 UTC, IlyaOrlov commented on Practice/O_Orlova/pep8task.py
> +        for path, hashname in mp3s:  # название класса по
Что за название класса?

2023-08-30 08:44 UTC, IlyaOrlov commented on Practice/O_Orlova/Tasks_lec3-4/Task_6.py
> +result = diff / int(distance)         # явно указываем интерпретатору, что надо складывать как число
Только, наверное, делить:)

2023-09-03 20:30 UTC, olechka7437 commented on Practice/O_Orlova/Tasks_lec3-4/Task_6.py
> +result = diff / int(distance)         # явно указываем интерпретатору, что надо складывать как число
вы правы)

2023-09-04 09:39 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-04 09:39 UTC, merged