Домашнее задание 2
IlyaOrlov/PythonCourse2.0_September23 pull request #25
Opened 2023-08-30 07:47 UTC by lvladimirova

2023-08-30 08:32 UTC, IlyaOrlov requested changes
Всё супер! Одно небольшое уточнение.

2023-08-30 08:32 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture 2/pep8task.py
> +# Определение функции отделяется двумя пустыми строками
А вот здесь есть нюанс ([PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Method%20definitions%20inside%20a%20class%20are%20surrounded%20by%20a%20single%20blank%20line.)): функции, определённые внутри класса, называются методами, и для них установлено отделение как раз одной пустой строкой сверху и снизу. То, что эта функция находится внутри класса, можно определить по отступам слева.
Этот комментарий и комментарии в стр.13, 26, 38 стоит убрать.
А вот комментарий в стр.55 - верный!

2023-08-31 18:59 UTC, IlyaOrlov requested changes
Один комментарий ещё некорректный остался.

2023-08-31 18:59 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture 2/pep8task.py
> +          f = open(output, 'r')  # Не задано значение переменной output
Оно задаётся в стр.14, как у аргумента функции.

2023-09-01 07:26 UTC, lvladimirova commented on Practice/lvladimirova/Lecture 2/pep8task.py
> +          f = open(output, 'r')  # Не задано значение переменной output
Исправила. Надеюсь, больше ничего не напутала

2023-09-01 09:22 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-01 09:22 UTC, merged