Amarinin branch
IlyaOrlov/PythonCourse2.0_September23 pull request #29
Opened 2023-08-30 17:57 UTC by RemoSet

2023-08-30 20:50 UTC, IlyaOrlov requested changes
Хорошо. Оставил несколько небольших замечаний.

2023-08-30 20:50 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modui2_lesson2_2.py
> +end = input("Топлива осталось (литров): ") # литры из литров - это правильно.
В стр.13, 14, 17 между кодом и началом комментария (#) должно быть минимум два пробела согласно [PEP8](https://peps.python.org/pep-0008/#inline-comments:~:text=Inline%20comments%20should%20be%20separated%20by%20at%20least%20two%20spaces%20from%20the%20statement.). PyCharm, как правило, подсказывает этот нюанс.

2023-08-30 20:50 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_1.py
> +def square(r):
Перед определением функции тоже должно быть две пустых строки, а не одна.

2023-08-30 20:50 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +# пробельная строка лишняя
Почему лишняя? Наоборот, def main - это отдельная функция. Перед ней тоже должно быть две пустых строки.

2023-08-30 20:50 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +# где def где for  и почему в разных местах, пока не понимаю )
А из-за чего это непонимание? Из-за того, что с отступами что-то не так: то ли вложенный код, то ли нет. Можно так и написать: некорректные отступы.

2023-08-31 21:47 UTC, RemoSet commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +# где def где for  и почему в разных местах, пока не понимаю )
спасибо, учел

2023-09-01 09:06 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modui2_lesson2_2.py
> +    # вроде одна пробельная строчка допускается для разделения блоков по смыслу, логике и для красоты.
Вполне. Но злоупотреблять не стоит, иначе код может растянутся на весь экран.

2023-09-01 09:07 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modui2_lesson2_2.py
> +    # вроде одна пробельная строчка допускается для разделения блоков по смыслу, логике и для красоты.
В частности, после `if __name__ == "__main__":`, как правило, пустую строку не добавляют.

2023-09-01 09:20 UTC, IlyaOrlov requested changes
Хорошо. Есть небольшие замечания. 
И ещё субъективное мнение: пустая строка после `if __name__ == "__main__":` смотрится странно.

2023-09-01 09:20 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +        mp3s = []  # цвет не хороший, вроде функция должна чего то возвращать
А какая функция? На самом деле, большинство проблем в блоке кода от стр.15 до стр.26 связано с тебе, что отступы неправильные: весь этот код относится к функции rename, но вложенность указана неверно. Из-за этого PyCharm тоже теряется и не знает, как, вообще, весь этот код понимать.
Поэтому стоит отмечать только те ошибки в этом файле, в которых Вы уверены.

2023-09-01 11:20 UTC, RemoSet commented on Practice/amarinin/Modul_2/modui2_lesson2_2.py
> +    # вроде одна пробельная строчка допускается для разделения блоков по смыслу, логике и для красоты.
Ага, все понял, не буду ее ставить и уберу там где поставил )

2023-09-01 11:22 UTC, RemoSet commented on Practice/amarinin/Modul_3/modul3_lesson3_4.py
> +    word =input("Введите слово, содержащее буквы 'A' : ")
да! лопухнулся ). с вариантами латинским и русским шрифтами подумаю)

2023-09-01 11:23 UTC, RemoSet commented on Practice/amarinin/Modul_3/modul3_lesson3_5.py
> +    polindrom = (word == revers_word)
не учел (

2023-09-01 11:24 UTC, RemoSet commented
Радует, что процесс э..... пошёл )). Как то потихонечку структурируется.

2023-09-01 15:13 UTC, IlyaOrlov requested changes
Супер! Остались вопросы по pep8task.py (надо комментарии скорректировать) и одно предложение по оптимизации (в задаче про палиндром).

2023-09-01 15:13 UTC, IlyaOrlov commented on Practice/amarinin/Modul_3/modul3_lesson3_5.py
> +    polindrom = (word.lower() == revers_word.lower())
А если применить lower() сразу в строке 2 (т.е. `word = input("Введите слово : ").lower()`), то не придётся вызывать этот метод дважды;)

2023-09-01 15:13 UTC, IlyaOrlov commented on Practice/amarinin/Modul_3/modul3_lesson3_4.py
> +    replaze_word = word.replace(chr(65), "*").replace(chr(1040), "*")
Оригинально:) Сначала я хотел написать, что так непонятно, какой символ мы заменяем. Но подумал и решил, что зато так видно, что это два replace() для замены разных символов.

2023-09-01 16:16 UTC, RemoSet commented on Practice/amarinin/Modul_3/modul3_lesson3_5.py
> +    polindrom = (word.lower() == revers_word.lower())
Я бы сказал, что так мы теряем введенное слово, первоначальное, со всеми особенностями, а вдруг оно еще где то понадобиться? )
Пока теряюсь в "эргономике" кода, вариантов много, а какой лучше не могу решить, не могу да же сказать, в чем эта "эргономика" выражается (. Но если исходить из того, что два вызова функции это хуже, чем один вызов,
и программа решает конкретную задачу, а не ту которая могла бы быть теоретически, то да, полностью согласен ))

2023-09-01 16:28 UTC, RemoSet commented on Practice/amarinin/Modul_3/modul3_lesson3_4.py
> +    replaze_word = word.replace(chr(65), "*").replace(chr(1040), "*")
О! Я горд ))

2023-09-02 11:37 UTC, IlyaOrlov commented on Practice/amarinin/Modul_3/modul3_lesson3_5.py
> +    polindrom = (word.lower() == revers_word.lower())
Если б можно было точно предугадывать все изменения, которые ещё потребуется делать в программе, опыт программирования не был бы в такой цене, да и вообще, за нас бы уже весь код нейросети писали:)
Пока что стоит ориентироваться на правило "Меньше кода - меньше ошибок". Конечно же, с учетом понятности и избежания лишних действий (чтоб не терять в производительности). Про понятность мы уже начали говорить, а про производительность ещё будем.

2023-09-02 11:43 UTC, IlyaOrlov requested changes
Всё супер! Осталась пара нюансов по pep8task.py

2023-09-02 11:43 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +          f = open(output, 'r')  # не хватает двух пробелов перед 'f'
А вот здесь и в стр.25 - не всё так однозначно. Можно внести этот код под цикл (тогда он будет выполняться на каждой итерации цикла), можно вынести (тогда он будет выполняться один раз после цикла). На самом деле, лучше вынести (сдвинуть на два пробела влево). Но чтоб сделать такой вывод, надо понять, что такое циклы, и что тут за self.map. Пока же можно только сказать, что имеющиеся отступы тут некорректны (ни то, ни сё).

2023-09-02 11:43 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +          mp3s = []  # если относится к циклу 'with', то нет 4 пробела, иначе 2 лишних пробела относительно 'def'
Маленькое уточнение: with - не цикл. Это оператор менеджера контекста. Мы про него тоже поговорим.

2023-09-02 11:43 UTC, IlyaOrlov commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +from time import *  # такой импорт может привести к конфликту между именами в модуле 'time' и именами в коде
Отличное наблюдение!!!

2023-09-02 17:37 UTC, RemoSet commented on Practice/amarinin/Modul_2/modul2_lesson2_3.py
> +          mp3s = []  # если относится к циклу 'with', то нет 4 пробела, иначе 2 лишних пробела относительно 'def'
Поправил, и сделал зарубочку по поводу ':' - если стоит в конце, значит точно следующая строчка + 4 пробела.
Как то раньше не акцентировалась такая явная  схема.

2023-09-03 08:00 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-03 08:01 UTC, merged