Домашнее задание 1
IlyaOrlov/PythonCourse2.0_September23 pull request #3
Opened 2023-08-24 17:37 UTC by mtvtanic

2023-08-24 18:19 UTC, IlyaOrlov requested changes
Хорошо. Одно небольшое замечание.

2023-08-24 18:19 UTC, IlyaOrlov commented on Practice/ermakova/task1.py
> +print(c)
Надо убрать "кирпич" в конце файла, добавив одну пустую строку!

2023-08-24 20:16 UTC, mtvtanic commented on Practice/ermakova/task1.py
> +print(c)
Исправила, спасибо!

2023-08-25 07:30 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-08-25 07:30 UTC, merged