Zadanie1
IlyaOrlov/PythonCourse2.0_September23 pull request #33
Opened 2023-08-31 10:33 UTC by Ar87tem123456789101112

2023-08-31 18:53 UTC, IlyaOrlov requested changes
Есть замечания!

2023-08-31 18:53 UTC, IlyaOrlov commented on Practice/amarkov/task.pytest
Этот файл надо удалить!

2023-08-31 18:53 UTC, IlyaOrlov commented on Practice/amarkov/task1.1py
У это файла надо поправить название: вместо "task1.1py" должно быть, например, "task1.py" или "task1_1.py"

2023-08-31 18:53 UTC, IlyaOrlov commented on Practice/amarkov/task 1.1 py
У этого файла надо поправить название.

2023-08-31 18:53 UTC, IlyaOrlov commented on Practice/amarkov/task 1.1 py
> +name = input( "иван" )
Код, вероятно, должен быть другим:
```python
name = input("Как тебя зовут? ")
print(name)
```
input - это когда компьютер что-то спрашивает у пользователя. В скобочках после input мы формулируем вопрос, который задаёт компьютер. Поэтому input( "иван" ) выглядит нелогично.

2023-09-01 14:07 UTC, Ar87tem123456789101112 commented on Practice/amarkov/task 1.1 py
> +name = input( "иван" )
name = input("Как тебя зовут? ")
print(name)

2023-09-01 14:08 UTC, Ar87tem123456789101112 commented on Practice/amarkov/task 1.1 py
> +name = input( "иван" )
и через push тоже отправил, закомител вначале.. Тут продублировал на всякий случай.

2023-09-01 15:15 UTC, IlyaOrlov commented on Practice/amarkov/task1_1.py
> +print(name)
В этом файле надо добавить ещё пустую строку в конце, чтоб "кирпич" убрать.

2023-09-01 15:16 UTC, IlyaOrlov commented on Practice/ermakova/task1.py
А это чужой файл! Здесь надо вернуть всё как было и тоже сделать Commit и Push.

2023-09-01 16:06 UTC, Ar87tem123456789101112 commented on Practice/ermakova/task1.py
свой код с чужого файла убрал, сделал комит и пуш

2023-09-01 16:19 UTC, Ar87tem123456789101112 commented on Practice/amarkov/task1_1.py
> +print(name)
вроде там всё пропало в конце, если правильно понял что от меня требовалось.

2023-09-02 10:36 UTC, Ar87tem123456789101112 commented on Practice/amarkov/task1_1.py
> -print(name)
разобрался, не верно понял ваше замечание вчера. Строку оставил одну пустой. Кирпич должен исчезнуть.

2023-09-02 11:50 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-02 11:50 UTC, merged