Nskorokhodova first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #34
Opened 2023-08-31 14:26 UTC by nsa3108

2023-08-31 18:55 UTC, IlyaOrlov requested changes
Хорошо. Но есть замечания.

2023-08-31 18:55 UTC, IlyaOrlov commented on Practice/nskorokhodova/task1.py
> +a = input("введите ф:")
Может, "введите a"? А то пользователь удивится:)

2023-08-31 18:55 UTC, IlyaOrlov commented on Practice/nskorokhodova/task1.py
> +c=100500
Вокруг = должно быть по пробелу.

2023-09-04 10:20 UTC, nsa3108 commented on Practice/nskorokhodova/task1.py
> +a = input("введите ф:")
Done

2023-09-04 10:21 UTC, nsa3108 commented on Practice/nskorokhodova/task1.py
> +c=100500
Done

2023-09-04 10:23 UTC, nsa3108 commented on Practice/nskorokhodova/task1.py
> +print(c)
Здесь тоже что-то надо отредактировать?

2023-09-04 13:22 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-04 13:22 UTC, merged