Tanya sh
IlyaOrlov/PythonCourse2.0_September23 pull request #38
Opened 2023-09-01 20:50 UTC by titatatia

2023-09-02 04:27 UTC, Tetrackon requested changes
Всё хорошо, но последнее задание хотелось бы подправить немного :)

2023-09-02 04:27 UTC, Tetrackon commented on Practice/tshyregena/encryption2.py
> +    print(f"Неверный ключ")
На будущее: Если Вы планируете обрабатывать переменную, только в том случае, если выполнится условие, то лучше всего перенести обработчик под if. Я имею ввиду вот эту строчку :
res2 = res ^ key
В рамках обучения, подобное не страшно, но представьте если у Вас запускается функция, которой на исполнение нужно 5 минут? Вы ждёте выполнения функции, потом вводите неверное значение, и то что обработала функция - просто выкидывается, а Вы в пустую прождали 5 минут.

2023-09-02 11:48 UTC, IlyaOrlov requested changes
Ещё одно небольшое замечание.

2023-09-02 11:48 UTC, IlyaOrlov commented on Practice/tshyregena/rectangle.py
> +result = int(a) * 2 + int(b) * 2
Общий множитель стоит вынести за скобки;)

2023-09-04 12:12 UTC, titatatia commented on Practice/tshyregena/encryption1.py
> +p = input("Введите пароль: ")
Исправила

2023-09-04 12:15 UTC, titatatia commented on Practice/tshyregena/encryption2.py
> +    print(f"Неверный ключ")
Исправила. Надеюсь правильно) Не совсем поняла почему есть вероятность долгого выполнения.

2023-09-04 12:17 UTC, titatatia commented on Practice/tshyregena/rectangle.py
> +result = int(a) * 2 + int(b) * 2
Исправила. Надо открывать учебник за первый класс)

2023-09-04 13:06 UTC, IlyaOrlov requested changes
Давайте уточним логику того, что делается в файлах [encryption1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/38/files#diff-2758ef2f154964c0fc380dc2d5673ef3588b08a8ce2e05aa25aa6d6f28581f21) и [encryption2.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/38/files#diff-72bd0af63b7b071aa5a191238c3738a3afd591d72ef7158929f28c48ca012ef8).
В 1-м файле пользователь вводит пароль, который шифруется ключом, и результат res - зашифрованный пароль - выдаётся пользователю (наверное, print всё-таки нужен).
Во 2-м файле пользователь должен ввести зашифрованный пароль из первого файла, чтоб программа его дешифровала тем же ключом и выдала исходный пароль. В принципе, в стр.1-4 это самое и делается. Но что за ключ запрашивается потом...?

2023-09-06 12:08 UTC, titatatia commented
> 

Я не понимаю суть замечания. Запрашивается ключ у пользователя. Я не верно поняла задание?

2023-09-06 12:23 UTC, titatatia commented
> 

Это две абсолютно одинаковые программы!

2023-09-06 12:46 UTC, IlyaOrlov commented
> > 
> 
> Это две абсолютно одинаковые программы! Но мне кажется я поняла.

Да, практически одинаковые. И это нормально. Интерфейс схожий, потому что и при шифровании, и при дешифровании надо вводить данные. Алгоритм одинаковый, потому что оператор XOR умеет и шифровать, и дешифровать данные. 
На практике подобные программы будут находиться на разных компьютерах, подключенных к сети: на одном компьютере мы шифруем данные и пересылаем их на другой компьютер, где выполняется расшифровка.
Т.к. отправку данных по сети с помощью Python мы ПОКА не проходили, реализуем только ту часть системы обмена зашифрованными сообщениями, которую можем:)

2023-09-06 18:08 UTC, IlyaOrlov commented on Practice/tshyregena/a.py
> +# Написала с if что бы сервер не "падал", если я правильно поняла.
Он и так не упадёт:) Упал бы, если бы использовали метод index().

2023-09-06 18:10 UTC, IlyaOrlov commented on Practice/tshyregena/pole.py
> +p = input("Введите слово строчными буквами: ")
Хорошее ограничение:) А если пользователь введёт слово из разных букв (прописных/строчных) и получит неправильный ответ, будем считать, что он сам виноват?)

2023-09-06 18:11 UTC, IlyaOrlov requested changes
Замечаний нет. Но есть вопрос и уточнение. На понимание.

2023-09-07 15:05 UTC, titatatia commented on Practice/tshyregena/pole.py
> +p = input("Введите слово строчными буквами: ")
> Хорошее ограничение:) А если пользователь введёт слово из разных букв (прописных/строчных) и получит неправильный ответ, будем считать, что он сам виноват?)

Да) Мне его переосмыслить?

2023-09-07 19:25 UTC, IlyaOrlov commented on Practice/tshyregena/pole.py
> +p = input("Введите слово строчными буквами: ")
Если знаете, как обойтись без такого ограничения, то можно оставить, как есть)

2023-09-10 20:40 UTC, titatatia commented on Practice/tshyregena/pole.py
> +p = input("Введите слово строчными буквами: ")
Исправила

2023-09-11 06:47 UTC, IlyaOrlov requested changes
Хорошо. Но есть замечания!

2023-09-11 06:47 UTC, IlyaOrlov commented on Practice/tshyregena/fissbuss.py
> +    if start % 15 == 0:  # Не поняла почему, если ставить ещё раз elif, не работает
Потому что, если число кратно 15, то оно кратно и 5, и 3 (ибо 15 = 3 * 5). Надо просто первым поставить `if start % 15 == 0`, а потом через elif проверять кратность 3 и 5.

2023-09-11 06:47 UTC, IlyaOrlov commented on Practice/tshyregena/choice.py
> +while not i.isdecimal() == num:
Некорректное сравнение: сравниваем результат логического выражения i.isdecimal() (которое будет True или False) со строкой num.
Тут достаточно `while not i.isdecimal()`, а в цикле после стр.11 стоит добавить break. Тогда и `i = input("Попробуйте ещё раз: ")` можно будет не повторять дважды, а просто написать один раз в конце цикла.

2023-09-11 12:04 UTC, titatatia commented on Practice/tshyregena/choice.py
> +while not i.isdecimal() == num:
У меня теперь просто ничего не работает без этого сравнения. Пишет "Вы ввели не число"

2023-09-11 12:40 UTC, IlyaOrlov commented on Practice/tshyregena/choice.py
> +while not i.isdecimal() == num:
Тогда поправочка: `while i.isdecimal():`

2023-09-12 15:30 UTC, IlyaOrlov requested changes
Есть замечания по новым заданиям.

2023-09-12 15:30 UTC, IlyaOrlov commented on Practice/tshyregena/stop.py
> +    if p.isalpha():
Если пользователь введёт, например, точку или запятую, то isalpha() будет False. Поэтому проверку на число лучше выполнять с использованием isdecimal().

2023-09-12 15:30 UTC, IlyaOrlov commented on Practice/tshyregena/stop.py
> +        p = input("Введите число: ")
А здесь мы **p** уже не проверяем, сразу в **s** добавляем?

2023-09-12 15:30 UTC, IlyaOrlov commented on Practice/tshyregena/пятизначный.py
> +p1 = p[0]
Лишняя операция

2023-09-16 20:24 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-16 20:24 UTC, IlyaOrlov approved these changes

2023-09-16 20:25 UTC, merged