Домашнее задание 1-3 по 3 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #39
Opened 2023-09-02 14:32 UTC by Ekaterinka11

Прошу проверить домашнее задание 1-3 по 3 лекции

2023-09-02 17:05 UTC, IlyaOrlov requested changes
Хорошо. Но есть пара нюансов.

2023-09-02 17:05 UTC, IlyaOrlov commented on Practice/Kashintseva/task3_4.py
> +wr = w.replace("а", "*")
А это русская "а" или английская?

2023-09-02 17:05 UTC, IlyaOrlov commented on Practice/Kashintseva/task3_5.py
> +y = x[::-1]
Надо предусмотреть случай, когда введённое слово начинается с большой буквы. Например, "Топот" тоже является палиндромом.

2023-09-02 19:19 UTC, Ekaterinka11 commented on Practice/Kashintseva/task3_4.py
> +wr = w.replace("а", "*")
Исправила код с учетом русской и английской "а"/"А".

2023-09-02 19:19 UTC, Ekaterinka11 commented on Practice/Kashintseva/task3_5.py
> +y = x[::-1]
Исправила.

2023-09-03 07:54 UTC, IlyaOrlov commented on Practice/Kashintseva/task3_4.py
> +wr = w.replace("а", "*")
Супер! На самом деле, можно было и одним выражением записать:
```python
wr = w.replace("a", "*").replace("A", "*").replace("а", "*").replace("А", "*")
```
Покороче, но тоже, конечно, выглядит неизящно. Чуть позже мы пройдём библиотеку регулярных выражений **re**. Она позволяет описать то же решение ещё короче и изящней.

2023-09-03 07:54 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-03 07:54 UTC, merged