:)
IlyaOrlov/PythonCourse2.0_September23 pull request #46
Opened 2023-09-04 19:02 UTC by RemoSet

2023-09-05 05:03 UTC, Tetrackon submitted a review, later dismissed
Всё отлично! Мне особенно понравилось забавное решение в третьей задачке. Оно не неправильное, но какое-то излишне сложно-читаемое. Эдакая машина Голдберга на минималках))) Есть небольшие рекомендации.

2023-09-05 09:38 UTC, IlyaOrlov requested changes
Всё замечательно! Есть только предложения по оптимизации.

2023-09-05 09:38 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/modul4_lesson4_3.py
> +        if number.isdecimal() is False and number != 'stop':
[PEP8](https://peps.python.org/pep-0008/#:~:text=Don%E2%80%99t%20compare%20boolean%20values%20to%20True%20or%20False%20using%20%3D%3D) рекомендует не сравнивать с True или False явно. Т.е. с точки с\зрения стиля корректней переписать это выражение как:
```python
if not number.isdecimal() and number != 'stop':
```

2023-09-05 11:52 UTC, RemoSet commented
Вот, пока не вошло в привычку посмотреть комментарии а уже потом что то шкодить. Исправлюсь )))

2023-09-05 12:26 UTC, RemoSet commented on Practice/amarinin/Modul_4/Modul4_lesson4_4.py
Смутило ))), но не повторения, а то что не смог разрешить, пока, эту проблему. Как в Дзене, лучше что-нибудь, чем ни чего.

2023-09-06 11:39 UTC, IlyaOrlov requested changes
Всё супер! Есть комментарии по мелочам и предложения по оптимизации.

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_4.py
> +        i += 1
Если пропустить else, то на втором и последующих циклах вопросов будет пропускаться respond1.
Как только i станет равна 0 в стр.13, сразу же на следующей строке она увеличится на 1.

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/modul4_lesson4_3.py
> +            incorrect_input = ""
Как вариант, в стр.6 сделать цикл **while True:**, а по условию в стр.10 выполнить **break**.

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +def verification_str_int (input_str):
Ещё пустая строка сверху.

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +    if input_str.isdecimal() is False:
`if not input_str.isdecimal():`

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +        print("\033[7mвведено не понятно что, игра окончена!\033[0m")
С цветами, конечно, красиво. Но для большей ясности кода я бы вынес управляющие последовательности в константы и их бы уже подставлял, куда нужно. Это ещё пригодится, чтоб централизованно одним исправлением менять цвет под желание заказчика во всем тексте.
Например:
```python
import random


ERR_START = "\033[7m"
ERR_END = "\033[0m"

MSG_START = "\033[31m"
MSG_END = "\033[0m"


def verification_str_int (input_str):
    if not input_str.isdecimal():
        print(f"{ERR_START}введено не понятно что, игра окончена!{ERR_END}")
        exit()
    return int(input_str)


if __name__ == "__main__":
    stop_word = ""
    print(f"Поиграем?! Если надоест, введи {MSG_START}любимое{MSG_END} слово\nВведи границы числового интервала :")
...
```

```

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +        exit()
Безусловное завершение программы из вложенных функций, конечно, допустимо с точки зрения синтаксиса. Но такую программу будет сложно отлаживать. Представьте, что Вы вводите в смартфоне или на каком-нибудь сайте некорректные данные (например, логин/пароль), Вам выдаётся сообщение об ошибке, после которого смартфон или компьютер автоматически выключаются.
Лучше, чтоб решения о завершении программы принимались только в основном коде. Функции же могут передавать в основной код сообщения об ошибках через возврат значений или механизм исключений, о котором мы поговорим отдельно.

2023-09-06 11:39 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +    while  number != wunder_number:
Лишний пробел после while.

2023-09-06 16:01 UTC, RemoSet commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +        print("\033[7mвведено не понятно что, игра окончена!\033[0m")
Честно говоря, не возникла такая мысль, хотя она выглядит естественной и логичной :(

2023-09-06 16:03 UTC, RemoSet commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +        exit()
А..... это уже пока недоступный для меня уровень программирования, я имею в виду, постановку кода, или как то это по другому называется )

2023-09-06 16:05 UTC, RemoSet commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +    while  number != wunder_number:
Конечно... "все супер...", но мелочи иногда убивают ))))

2023-09-06 18:19 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/Modul4_lesson4_5.py
> +        exit()
Это называется Best Practicies (лучшие практики, лайфхаки). Т.е. можно решить задачу по-разному, но некоторые решения окажутся более практичными в будущем:)

2023-09-09 21:28 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-09 21:28 UTC, IlyaOrlov commented on Practice/amarinin/Modul_4/modul4_lesson4_3.py
> +        if number == 'stop':  # не получается через if not stop, не разобрался пока :( по всякому пробывал.
А что значит `if not stop`? stop - у Вас переменная, которая на самом деле по ходу цикла не меняется (т.е. в стр.6 мы фактически имеем while True), поэтому здесь мы сравниваем number со строкой "stop". Вроде всё корректно:)

2023-09-09 21:29 UTC, merged