modul2_2_1.py
IlyaOrlov/PythonCourse2.0_September23 pull request #48
Opened 2023-09-05 12:21 UTC by Ar87tem123456789101112

2023-09-05 12:53 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-09-05 12:53 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_1.py
> +
Здесь нужна ещё одна пустая строка.

2023-09-05 12:53 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_1.py
> +if
А куда пропало условие?

2023-09-05 12:53 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_1.py
> +    print(f"Площадь круга: {result}")
Почему здесь вместо площади выводится введенный пользователем радиус?

2023-09-05 13:03 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_1.py
> +if
исправлю

2023-09-11 09:37 UTC, IlyaOrlov requested changes
Ещё есть замечания.

2023-09-11 09:37 UTC, IlyaOrlov commented on Practice/amarkov/mod_2_2_1.py
> +if
Либо этот if надо убрать совсем, либо написать `if __name__ == ""__main__:`, иначе смысла нет.

2023-09-11 09:37 UTC, IlyaOrlov commented on Practice/amarkov/mod_2_2_1_py
Лишний файл. Надо удалить.

2023-09-11 09:37 UTC, IlyaOrlov commented on Practice/amarkov/mobil2_2_2.py
> +result = diff / distance
distance надо обернуть в int

2023-09-11 09:37 UTC, IlyaOrlov commented on Practice/amarkov/m _2_2_1.py
Тоже некорректный файл. Лучше его удалить и доделывать этот [mod_2_2_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/48/files/d02e5516120913abf67e399f8d865afedb929671..4d78de7e019ad9dacb825ef863c5f9812f705161#diff-529d22581066de27fdfc7df163a86a64ab216926eb9ac5eda0d85a3886a3f415)

2023-09-11 10:01 UTC, Ar87tem123456789101112 commented on Practice/amarkov/mod_2_2_1.py
> +if
уберу. Писал полностью if _name_ ==""_main_: он мне подчёркивает всё красным.

2023-09-11 10:32 UTC, IlyaOrlov commented on Practice/amarkov/mod_2_2_1.py
> +if
Надо смотреть, что конкретно ему не понравилось.

2023-09-11 18:41 UTC, IlyaOrlov requested changes
Есть файлы:
[m _2_2_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/48/files#diff-8b7b621707350a583adf47b039c1ebea5fdf7abe1ebbb8e60dca521d654e4b2c)
[m_2_2_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/48/files#diff-26877f051fb8296c25f79d30a1eb5a3883b03a4850dafa4661839cacde7ea6aa)
[mod_2_2_1_py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/48/files#diff-e4a5c47f873d6ba4db8720c8da628a6eff2389a629ce9dc5544daef1b9d5b404)
Все с ошибками. Стоит оставить какой-то один файл итоговый, и я по нему уже оставлю замечания.

2023-09-12 15:05 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_3.py
> +        self.map = {} # в конце инструкции ставится двоеточие ?
Нет. Двоеточие ставится, только когда какой-то блок кода начинается: условие (if), цикл или функция.

2023-09-12 15:05 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_3.py
> +        mp3s = [] # конец инструкции двоеточие должно быть?
Тоже нет. Двоеточие ставится, только когда какой-то блок кода начинается: условие (if), цикл или функция.

2023-09-12 15:06 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_3.py
> +# отступ между блоками две строки, а не три как тут.
Так а тут вроде как раз две пустые строки: 7-я и 8-я

2023-09-12 15:06 UTC, IlyaOrlov commented on Practice/amarkov/modul2_2_3.py
> +    for root, directories, files in os.walk(dirname): # должна быть ";" между инструкциями, на одной строке они не должны все располагаться
Это всё одна инструкция! Так задаётся цикл for. ";" здесь быть не должно.

2023-09-12 16:16 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +# отступ между блоками две строки, а не три как тут.
исправлено

2023-09-12 16:26 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +        self.map = {} # в конце инструкции ставится двоеточие ?
исправлено

2023-09-12 16:30 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +        mp3s = [] # конец инструкции двоеточие должно быть?
исправлено

2023-09-12 16:57 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +    parser = argparse.ArgumentParser() #не хватает двоеточия в конце
в строке 34-35, между if и for должен быть отступ в две строки? if это условие (один блок) а for это цикл (другой блок)

2023-09-12 17:07 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +    parser = argparse.ArgumentParser() #не хватает двоеточия в конце
разобрался, кажется. for производит объединение файлов под условием if
if определяет условие, которое необходимо for, чтобы объединить файла в целое.

2023-09-13 08:59 UTC, Ar87tem123456789101112 commented on Practice/amarkov/modul2_2_3.py
> +    parser = argparse.ArgumentParser() #не хватает двоеточия в конце
спасибо.

2023-09-14 12:17 UTC, IlyaOrlov requested changes
Хорошо. Но есть одно замечание!

2023-09-14 13:19 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-14 13:19 UTC, merged