Домашнее задание 1
IlyaOrlov/PythonCourse2.0_September23 pull request #5
Opened 2023-08-24 17:38 UTC by lvladimirova

2023-08-24 18:23 UTC, IlyaOrlov requested changes
Хорошо. Есть несколько замечаний.

2023-08-24 18:23 UTC, IlyaOrlov commented on Practice/lvladimirova/1.4.py
> +name = input ("Введите город:")
Здесь и в остальных файлах надо убрать пробелы между именем функции и скобкой согласно [PEP8](https://peps.python.org/pep-0008/#:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call)
Ну и от "кирпичей" в конце файлов тоже лучше избавиться.

2023-08-25 14:42 UTC, lvladimirova commented on Practice/lvladimirova/1.4.py
> +name = input ("Введите город:")
Замечания исправлены. Проверьте, пожалуйста

2023-08-25 21:27 UTC, IlyaOrlov approved these changes

2023-08-25 21:28 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-08-25 21:28 UTC, merged