Practice_Lec_2
IlyaOrlov/PythonCourse2.0_September23 pull request #51
Opened 2023-09-06 09:19 UTC by nsa3108

2023-09-06 09:23 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task3.py
Нашла еще одну ошибку
class_ shuffler:

2023-09-06 11:50 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-09-06 11:50 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
Так можно её в коде комментарием и отметить.

2023-09-06 11:50 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +#Определение функции отделяется двумя пустыми строками
Функции, находящиеся внутри класса (что они внутри, можно понять по отступам и специфическому названию их первого аргумента - self) - это не простые функции. Они называются методами. К ним - [отдельные требования](https://peps.python.org/pep-0008/#blank-lines:~:text=Method%20definitions%20inside%20a%20class%20are%20surrounded%20by%20a%20single%20blank%20line.): отделять одной пустой строкой.
А вот функции parse_arguments (стр.44) и main (стр.56) - это обычные функции. Их-то и надо двумя строками отделять.

2023-09-06 11:50 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task2.py
> +start = int(input("Топлива было: ")); end = int (input("Топлива осталось: "))
В этом коде надо исправить ошибки!

2023-09-06 11:50 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task1.py
> +def square(r):
Вокруг функции
```
def square(r):
    return math.pi * r ** 2
```
должно быть две пустые строки.

2023-09-06 12:44 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task1.py
> +def square(r):
Done

2023-09-06 12:44 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +#Определение функции отделяется двумя пустыми строками
Исправления сделала

2023-09-06 13:12 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +#Определение функции отделяется двумя пустыми строками
Комментарии тоже надо убрать и лишние строки: 10, 12, 15, 30.

2023-09-06 18:06 UTC, IlyaOrlov requested changes
Остались замечания по [Practice_lec_2_task3.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/51/files#diff-11da42c3c4596a1eda09c8c56f531dc4b3a44b69d7b1810def02d6fa62d1ea0a)

2023-09-06 18:06 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
Ошибочные комментарии в файле убрали - это хорошо. Но ещё какие-то комментарии о найденных ошибках должны присутствовать! Ну и пустые строки вокруг методов лишние появились - это уже нехорошо.

2023-09-08 22:48 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task3.py
1. Разделение импорта от блока функции и от основновного кода разделяется двумя строками ( строки 7-8, 41-42, 54-55, 68-69)
2. вокруг "=" должны быть пробелы ( стр 38)

2023-09-09 08:12 UTC, IlyaOrlov requested changes
Комментарий про "=" некорректен. И лучше в этом заданий комментарии по найденным ошибкам писать прямо в коде через #

2023-09-09 08:12 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +def generateName(self, seed = time()):
Нет. Когда "=" используется в списке аргументов функции, пробелов вокруг быть не должно (см. [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Don%E2%80%99t%20use%20spaces%20around%20the%20%3D%20sign%20when%20used%20to%20indicate%20a%20keyword%20argument%2C%20or%20when%20used%20to%20indicate%20a%20default%20value%20for%20an%20unannotated%20function%20parameter%3A))

2023-09-11 06:35 UTC, IlyaOrlov requested changes
Ожидается исправление замечаний по файлу [Practice_lec_2_task3.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/51/files#diff-11da42c3c4596a1eda09c8c56f531dc4b3a44b69d7b1810def02d6fa62d1ea0a)
Надо прописать **в коде** корректные комментарии.

2023-09-11 12:33 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task3_.py
неверный вариант, буду удалять

2023-09-11 19:04 UTC, IlyaOrlov requested changes
Добавил несколько замечаний.

2023-09-11 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_3_task1.py
> +x = input ("Введите длину прямоугольника: ")
Здесь и в других файлах: лишний пробел между input и скобкой.

2023-09-11 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Pep8task.py
Лишний файл

2023-09-11 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +# метод отделяеся одной строкой
Замечание по методами обсудили на занятии.

2023-09-11 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_3_task1.py
> +print(f"Периметр прямоугольника: {result}")
Здесь и в других файлах стоит добавить одну пустую строку в конце файла, чтоб гитхаб не рисовал эти "кирпичи".

2023-09-11 22:16 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_2_task3.py
> +# метод отделяеся одной строкой
изменения внесла, спасибо

2023-09-12 08:12 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-12 08:12 UTC, merged