Platonova2
IlyaOrlov/PythonCourse2.0_September23 pull request #53
Opened 2023-09-06 22:24 UTC by yilya21q

Домашнее задание по 2 уроку

2023-09-07 09:57 UTC, IlyaOrlov requested changes
Хорошо, но есть небольшие замечания.

2023-09-07 09:57 UTC, IlyaOrlov commented on Practice/platonova/q_3_3.py
> +def square(r):
Сверху и снизу от определения функции должно быть по две пустые строки:
```python
import math


def square(r):
    return math.pi * r ** 2


radius = input("Введите радиус: ")
```

2023-09-07 09:57 UTC, IlyaOrlov commented on Practice/platonova/q_3_4.py
> +result = int(diff) / int(distance)
diff - и так число, потому что определяется как разность чисел. int к ней применять не нужно.

2023-09-08 02:24 UTC, yilya21q commented on Practice/platonova/q_3_3.py
> +def square(r):
Исправила :)

2023-09-08 02:24 UTC, yilya21q commented on Practice/platonova/q_3_4.py
> +result = int(diff) / int(distance)
Исправила :)

2023-09-08 07:35 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-08 07:35 UTC, merged