Домашнее задание к лекции 4 (1-3)
IlyaOrlov/PythonCourse2.0_September23 pull request #57
Opened 2023-09-08 14:51 UTC by Ekaterinka11

ДЗ к лекции 4 (частично)

2023-09-08 21:08 UTC, IlyaOrlov requested changes
Хорошо. Но есть замечания.

2023-09-08 21:08 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_1.py
> +for i in range(start, end):
range будет возвращать числа в диапазоне start <= i < end, т.е. end не попадет в итоговый вывод. Поэтому, чтоб перебрать числа от 1 до 100 включительно, надо указать end = 101.

2023-09-08 21:08 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_2.py
> +    for i in range(len(x)):
Надо определиться: либо мы сами инициализируем и увеличиваем i, либо это делает цикл for i in range.
Второе, конечно, предпочтительней.

2023-09-08 21:08 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_2.py
> +        print(f"{i} цифра равна {x[i]}")
Тут есть нюанс: при выводе счёт надо начинать с 1-цы, а не с нуля.

2023-09-08 21:08 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_3.py
> +    print(x)
В задании требуется не просто вывести введённое пользователем число, но собрать из нескольких таких чисел одно большое число.
Т.е. программа должна работать, например, так:
1) Пользователь ввёл 5 - это числовой символ, запомнили его в некоторой строковой переменной.
2) Пользователь ввёл 7 - это числовой символ, добавили его в переменную к 5 (получилось 57).
3) Пользователь ввёл q - это не числовой символ, отругали пользователя.
4) Пользователь ввёл 8 - это числовой символ, добавили его в переменную к 5 и 7 (получилось 578).
5) Пользователь ввёл stop - выводим 578 и завершаем программу.

2023-09-09 14:08 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_1.py
> +for i in range(start, end):
Исправила.

2023-09-09 14:13 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_2.py
> +    for i in range(len(x)):
Добавлено в цикле i += 1

2023-09-09 14:16 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_2.py
> +    for i in range(len(x)):
В 8 строке было указано увеличение i на 1 в цикле. Или я не так поняла?

2023-09-09 14:16 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_2.py
> +        print(f"{i} цифра равна {x[i]}")
Поправила.

2023-09-09 14:46 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_2.py
> +    for i in range(len(x)):
Так а зачем нам самим увеличивать i, если у нас цикл `for i in range`? Это цикл в отличие от while сам умеет менять переменную цикла (т.е. i).

2023-09-09 15:12 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_2.py
> +    for i in range(len(x)):
Поняла, исправила.

2023-09-09 21:13 UTC, IlyaOrlov requested changes
Всё хорошо, но можно сделать ещё лучше!

2023-09-09 21:13 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_4.py
> +        i = 0
Если мы хотим сбросить i в 0, то в этом случае делать i += 1 излишне. Поэтому лучше применить if ... else: если i < 2, то плюсуем единичку, иначе i = 0.

2023-09-09 21:13 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_3.py
> +        print(y)
Лишний print. Нам требуется только финальный вывод.

2023-09-09 21:13 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_2.py
> +        print(f"{i+1} цифра равна {x[i]}")
А если вместо `for i in range` применить `for i, n in enumerate(x, 1)`, то и плюсовать к i единицу не нужно будет, и вместо индексирования (x[i]) можно будет сразу n написать.

2023-09-10 14:24 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_2.py
> +        print(f"{i+1} цифра равна {x[i]}")
Поняла, поправила.

2023-09-10 14:31 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_4.py
> +        i = 0
Поняла, исправила.

2023-09-10 14:33 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_3.py
> +        print(y)
Но ведь у нас 2 случая вывода большого числа: в случае введения числового символа и при слове stop. Получается, без одного print эти 2 случая не выполнятся. Нужно по-другому написать цикл, правильно понимаю?

2023-09-10 16:53 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_3.py
> +        print(y)
Конкретно про вывод числа при каждом вводе числового символа в задании ничего не говорится. Требовался только финальный вывод. Но согласен, задание допускает разные варианты трактовки. Так что ОК, можно оставить, как есть.

2023-09-10 16:57 UTC, IlyaOrlov requested changes
Есть одно небольшое замечание.

2023-09-10 16:57 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_5.py
> +while (x := input("Угадайте целое число: ")) != str(num):
Стоит запомнить строковое представление num перед циклом: `s_num = str(num)`, чтоб не выполнять эту операции на каждой итерации цикла (при каждой проверке).

2023-09-11 07:59 UTC, IlyaOrlov requested changes
Всё хорошо! Есть одно предложение по оптимизации (следуя принципу "меньше кода - меньше ошибок").
Кстати, если вдруг захотите организовать игру не человек-человек, а человек-компьютер, достаточно заменить один из вводов на `u2 := random.choice(("k", "n", "b"))`

2023-09-11 07:59 UTC, IlyaOrlov commented on Practice/Kashintseva/task4_8.py
> +    u1 = input(f"{name1}, выберите k (камень), n (ножницы) или b (бумагу): ")
Код по вводу данных повторяется. Стоит оптимизировать. Можно так:
```python
name1 = input("Введите имя первого игрока: ")
name2 = input("Введите имя второго игрока: ")
while ((u1 := input(f"{name1}, выберите k (камень), n (ножницы) или b (бумагу): ")) 
       == (u2 := input(f"{name2}, выберите k (камень), n (ножницы) или b (бумагу): "))):
    print("Ничья. Сделайте новый выбор!")
```
или даже так:
```python
def choice(name):
    return input(f"{name}, выберите k (камень), n (ножницы) или b (бумагу): ")

name1 = input("Введите имя первого игрока: ")
name2 = input("Введите имя второго игрока: ")
while (u1 := choice(name1)) == (u2 := choice(name2)):
    print("Ничья. Сделайте новый выбор!")
```

2023-09-11 11:21 UTC, Ekaterinka11 commented on Practice/Kashintseva/task4_8.py
> +    u1 = input(f"{name1}, выберите k (камень), n (ножницы) или b (бумагу): ")
Первый вариант почти получился. Поняла, где ошиблась.
Второй вариант реализовала, разобралась.
Спасибо большое!

2023-09-11 11:33 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-11 11:33 UTC, merged