Домашнее задание 1
IlyaOrlov/PythonCourse2.0_September23 pull request #6
Opened 2023-08-24 17:38 UTC by AnutaShiranova

rerere

2023-08-24 18:24 UTC, IlyaOrlov requested changes
Небольшое замечание.

2023-08-24 18:24 UTC, IlyaOrlov commented on Practice/AShiranova/test1.py
> +b= input("Введите b: ")
Нужны пробелы после b и c согласно [PEP8](https://peps.python.org/pep-0008/#:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side%3A%20assignment%20(%3D)%2C%20augmented%20assignment%20(%2B%3D%2C%20%2D%3D%20etc.)%2C%20comparisons%20(%3D%3D%2C%20%3C%2C%20%3E%2C%20!%3D%2C%20%3C%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20in%2C%20not%20in%2C%20is%2C%20is%20not)%2C%20Booleans%20(and%2C%20or%2C%20not).).

2023-09-10 18:32 UTC, IlyaOrlov commented on Practice/AShiranova/test_pytest.py
> +import pytest
Лишний файл

2023-09-10 18:32 UTC, AnutaShiranova commented on Practice/AShiranova/test_pytest.py
> +import pytest
исправлю

2023-09-10 18:36 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-10 18:36 UTC, merged