Ermakova first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #67
Opened 2023-09-11 15:01 UTC by mtvtanic

2023-09-11 18:46 UTC, IlyaOrlov requested changes
Супер! Есть пара замечаний по мелочи.

2023-09-11 18:46 UTC, IlyaOrlov commented on Practice/ermakova/control4.8.py
> +comp = random.choice(igra)
Предлагаю выбор предмета компьютером внести в цикл, иначе это нечестно по отношению к компьютеру:)

2023-09-11 18:46 UTC, IlyaOrlov commented on Practice/ermakova/control4.8.py
> +                      "финиш: ")).lower() != "финиш".lower():
"финиш".lower() - как-то странно выглядит. "финиш" и так строчными буквами написан.

2023-09-11 20:23 UTC, mtvtanic commented on Practice/ermakova/control4.8.py
> +                      "финиш: ")).lower() != "финиш".lower():
Намудрила) конечно не надо, исправила))

2023-09-12 08:09 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-12 08:09 UTC, merged