Задания 1-5
IlyaOrlov/PythonCourse2.0_September23 pull request #68
Opened 2023-09-12 05:41 UTC by lvladimirova

2023-09-12 05:43 UTC, lvladimirova commented
Задания под лозунгом "Понять и простить")) Я честно очень старалась

2023-09-12 08:18 UTC, IlyaOrlov requested changes
Хорошо. Но есть несколько замечаний.

2023-09-12 08:18 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_2.py
> +                continue
continue здесь лишний

2023-09-12 08:18 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_2.py
> +            if s[i].isdecimal():
Может, просто в стр.3 проверить сразу `if len(s) == 5 and s.isdecimal():`?

2023-09-12 08:18 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_2.py
> +        for i, x in enumerate(s):
Если написать `for i, x in enumerate(s, 1):`, то в стр.7 можно к i не добавлять 1.

2023-09-12 08:18 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_2.py
> +                print(f"{i + 1} цифра равна {s[i]}")
Если пользуетесь enumerate, то вместо **s[i]** можно писать просто **x**, который у Вас указан в стр.5.

2023-09-12 08:18 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_4.py
> +    while (x := input("Спрашивай или сдавайся: ")). lower() != "хватит":
Лишний пробел между точкой и lower.

2023-09-12 17:32 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_4/4_2.py
> +                continue
Постаралась исправить замечания и добавила ещё два задания

2023-09-13 08:25 UTC, IlyaOrlov requested changes
Есть пара комментариев к новым заданиям.

2023-09-13 08:25 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_6.py
> +print(funsr(a, b))
Вопрос на понимание: что выведет на экран этот print?

2023-09-13 08:25 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_8.py
> +        if computer == "бумага" and user == "камень":
Сейчас даже если computer == user, все последующие if всё равно будут проверяться. А зачем нам проверять, чему равны computer и user, если мы уже выяснили, что они равны между собой? Что не делать лишних проверок, надо заменить if в стр.13,15,17,19,21,23 на elif.
Но это ещё не вся возможная оптимизация. Обратите внимание, в стр.13 и в стр.15 мы дважды проверяем computer == "бумага". Но можно обойтись и одной проверкой:
```python
        if computer == user:
            print("Ничья, давай ещё!")
        elif computer == "бумага":
            if user == "камень":
                print("Я победил тебя! Бумага заворачивает камень")
            else:  # если user не равен computer ("бумага") и не равен "камню", то остается один вариант - "ножницы"
                print("Ножницы разрезали бумагу! Ой-ой, тебе просто повезло!")
        elif computer == "ножницы":
        .    ...
```

2023-09-13 09:10 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_4/4_6.py
> +print(funsr(a, b))
Если ничего не путаю, то выведет большее число и None, потому что это функция, которая ничего не возвращает, значит по умолчанию считается, что возвращает None

2023-09-13 09:33 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_4/4_6.py
> +print(funsr(a, b))
Да, всё верно. Только уточню, что большее число выведет сама фyнкция funsr (точнее один из print'ов внутри неё). А этот print всегда будет выводить None. Нужен ли этот None? Если нет, то достаточно было просто написать здесь funsr(a, b).
Ошибки тут нет. Так что, если понятно, к чему был мой вопрос, можно ничего не исправлять.

2023-09-13 09:37 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_4/4_6.py
> +print(funsr(a, b))
Понятно. Я долго с этим return мучилась. Переслушиваю лекцию с понедельника и в голове прояснилось)) Теперь вот поняла с этим навязчивым None

2023-09-15 05:42 UTC, lvladimirova commented on Practice/lvladimirova/Lecture_4/4_8.py
> +        if computer == "бумага" and user == "камень":
Всё поправила, добавила декоратор. Теперь вроде все задания по этому блоку. Голова закипела по новым заданиям, поа есть проблемы с пониманием списков

2023-09-15 08:04 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-15 08:04 UTC, merged