Last task for lecture 4(task4_7)
IlyaOrlov/PythonCourse2.0_September23 pull request #70
Opened 2023-09-12 10:54 UTC by JulMakarova

2023-09-12 15:12 UTC, IlyaOrlov requested changes
Есть пара замечаний.

2023-09-12 15:12 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +    def decor():
Создавать отдельную функцию ради одного print - это как-то слишком) Тем более лишний вызов функции - это тоже, пусть небольшие, но накладные расходы.

2023-09-12 15:12 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
Если этот декоратор повесить на функцию, возвращающую результат, то она перестанет возвращать результат. Лучше, чтоб декоратор был универсальным.

2023-09-12 16:31 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +    def decor():
Я пока не понимаю, где эта "тонкая грань" так называемого плохого "повторяющегося кода" и необходимости создавать отдельную функцию/переменную для однотипного вывода.

2023-09-12 16:31 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +    def decor():
Исправила.

2023-09-12 16:32 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
Исправила. Хотя не считаю, что допустила ошибку в написании "своего" декоратора)

2023-09-12 18:24 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +    def decor():
В данном случае всё очевидно:) Стало ли меньше кода после создания функции? Нет, наоборот. А чем меньше кода -  тем лучше.
Есть, правда, ещё один нюанс - потенциальные изменения. Если заказчик в дальнейшем попросит выводить вместо "====" что-то другое, проще сделать изменения в одном месте (в функции), чем в двух. Но и этот нюанс можно учесть без создания функции - можно задать переменную, отвечающую за вывод (например, OUTPUT = "======") и в обоих принтах выводить её.

2023-09-12 18:54 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +    def decor():
Но как я поняла, Вас устраивает и просто вывод через 2 print-а (такие варианты кода вы замержили), до такого варианта я исправила,в чем замечание сейчас не очень понимаю.

2023-09-12 18:56 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
Ну уж давайте не будем нагнетать, какие коллеги удивятся от моего данного декоратора?! Это смешно.
То что декоратор должен быть универсальным я поняла и исправила, опять же в чем сейчас замечание не понимаю.

2023-09-12 18:58 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
И да, я так поняла, что инициатива наказуема, лучше брать все напрямую из лекции, все примеры, которые разбираете Вы, а не стараться сделать самому. Так меньше так называемых замечаний, И это обидно.

2023-09-12 19:05 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +    def decor():
Это не замечание. Это объяснение, как понять , где та самая тонкая грань.

2023-09-12 19:07 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
И даже в той статье, которую Вы скинули сегодня про декораторы (на tproger.ru), даны примеры декораторов без возвращаемых значений, так что. как я понимаю, такой вариант тоже допустим.

2023-09-12 19:17 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
Инициатива не наказуема, а приветствуется. Но если инициатива привела к ошибке - это не повод про эту ошибку не написать. Иначе зачем все эти проверки домашнего задания нужны? Вы предлагаете своё решение, я пишу, что конкретно в нём может быть некорректно. Не ставлю оценок, не отвергаю решение безапелляционно, не говорю "это не то, смотрите примеры", а вникаю в детали Вашего решения и пишу замечания по этим деталям.
Я стараюсь оставлять комментарии объективные и аргументированные. Если есть возражения и контраргументы, пожалуйста, их приведите. 
Насчет удивления коллег. Удивятся коллеги, совместно с которыми Вы будете работать над общим кодом. Потому что предсказуемое поведение кода - залог его качества.
Замечаний к коду у меня сейчас нет. Я просто отвечаю на Ваши комментарии.

2023-09-12 19:22 UTC, IlyaOrlov commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
> И даже в той статье, которую Вы скинули сегодня про декораторы (на tproger.ru), даны примеры декораторов без возвращаемых значений, так что. как я понимаю, такой вариант тоже допустим.

Там есть и декораторы без аргументов. Просто в статье о возможностях декораторов рассказывается поэтапно и в конце приводятся уже полноценные примеры.

2023-09-12 19:28 UTC, IlyaOrlov commented
Если Ваш код слишком хорош, чтоб его комментировать, можете его просто сюда не загружать, а сразу отправлять на Антитренинги. Для получения сертификата этого будет вполне достаточно.

2023-09-12 20:09 UTC, JulMakarova commented on Practice/julmakarova/task4_7.py
> +def decor_fun(fun):
Про универсальность декоратора услышала и приняла.
Про то, что "мой код слишком хорош" я так не считаю, поэтому и пришла учиться и готова слышать замечания и советы. И сертификат тут не главное, хочется выйти с данного курса именно с пониманием языка и возможностью дальнейшего роста в этом направлении. 
Если показалась наглой или неблагодарной, прошу прощения.

2023-09-13 08:25 UTC, IlyaOrlov approved these changes
Отлично. Замечаний нет.

2023-09-13 08:25 UTC, merged