a_marinin_modul5
IlyaOrlov/PythonCourse2.0_September23 pull request #72
Opened 2023-09-12 20:41 UTC by RemoSet

2023-09-13 10:20 UTC, IlyaOrlov requested changes
Замечательно! Добавил информацию к размышлению. Код в [modul5_lesson5_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/72/files#diff-7d652634fc7b9eb669b876a3da19517893df8d45b85cef86993da90487e4fe2a) желательно оптимизировать.

2023-09-13 10:20 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_2.py
Здесь тоже очень хорошее решение! Можно оставить, как есть. Но не могу не подкинуть информации к размышлению:)
Решение этой задачи можно сделать оптимальным либо по времени, либо по памяти. Этот нюанс можно либо уточнить у заказчика, либо определять по условиям предметной области.
Чтоб получить решение, оптимальное по времени, не считаясь с памятью, нужно создать ещё один контейнер, куда будем складывать все просмотренные элементы (как мы узнаем на грядущем занятии, лучший тип для такого контейнера - множество). 
Чтоб получить решение, оптимальное по памяти, надо для каждого элемента искать аналогичный среди предыдущих в **том же** списке. Вроде бы данное решение как раз и является оптимальным по памяти, но есть нюанс: срез lst[:i] - это уже новый список, полученный из старого. Т.е. выигрыша по памяти мы тоже не получаем. Получили бы, если б решение было таким:
```python
    for i, relapse in enumerate(lst):
        if lst.index(relapse, 0, i + 1) != i:
            return relapse
    return "повторов нет"
```
Здесь мы ищем relapse в том же списке, с 0-го элемента по i+1-й (НЕ включительно). Да, метод index позволяет задать такие границы поиска. Делаем поиск до i-го элемента включительно, чтоб гарантированно что-то нашлось (иначе index выбросит исключение, которое завершит программу). Если повторов нет, то результат index будет равен i (выйдем сами на себя). А если есть - то найдётся индекс предыдущего элемента, который != i.

2023-09-15 07:38 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_2.py
> +        if lst.index(relapse, 0) < i:
Замечательно! Он ведь в любом случае дальше i не пойдёт!

2023-09-15 07:56 UTC, IlyaOrlov requested changes
Замечательно! Но ещё есть, что поправить!

2023-09-15 07:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
Супер! Придерусь только к именам переменных: str, min - зарезервированные слова для вызова соответствующих функций. Не рекомендуется их использовать для именования переменных.

2023-09-15 07:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
> +        lst_i = lst[i:]
Не замечание, но комментарий: нужно иметь в виду, что lst[i:] - это создание нового списка со всеми вытекающими.

2023-09-15 07:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
str - зарезервированное слово для вызова соответствующей функции. Не рекомендуется его использовать для именования переменных.

2023-09-15 07:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +def matrix_print_beautiful(matrix=[]):
Указывать объект изменяемого типа в качестве значения по умолчанию небезопасно. PyCharm это тоже подсвечивает. Дело в том, что это "объект с историей" - он сохраняется от вызова к вызову функции. Попробуйте для интереса выполнить следующий код:

```python
def fun(lst=[]):
    lst.append(100)
    return lst


print(fun())
print(fun())
```
Ожидается, что в обоих случаях напечатается `[100]`. Ан, нет!
В данном случае, т.к. содержимое matrix не меняется, в качестве значения по умолчанию можно указать кортеж (matrix=()).

2023-09-15 07:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +def delete_post_matrix(lst=[], num=7):
Здесь аналогичная проблема с указанием объекта изменяемого типа в качестве значения по умолчанию. Т.к. lst меняется по ходу программы, можно задать его так:
```python
def delete_post_matrix(lst=None, num=7):
    if lst is None:
        lst = []
```
Это позволит при каждом новом вызове delete_post_matrix без указания списка создавать новый пустой список по умолчанию.

2023-09-15 19:07 UTC, RemoSet commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
> +        lst_i = lst[i:]
Долго думал про " lst[i:] - это создание нового списка", подвох почувствовал, но все же сдался, посмотрел как умные девочки решают, красиво.....

2023-09-15 19:08 UTC, RemoSet commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
да, буду повнимательнее

2023-09-15 19:11 UTC, RemoSet commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +def matrix_print_beautiful(matrix=[]):
попробовал, мина настоящая )

2023-09-15 19:14 UTC, RemoSet commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +def delete_post_matrix(lst=[], num=7):
да... вся жизнь, сплошные нюансы

2023-09-15 19:56 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
> +        lst_i = lst[i:]
Здесь на самом деле всё непросто. С одной стороны, если у нас в lst миллион элементов, то тут мы каждый раз будем создавать список из миллион - 1, миллион - 2 и т.д. элементов.
Но с другой стороны, это позволяет нам обходить новый список, используя enumerate без операции индексирования. Хотя, открою секрет, для списков это не так уж страшно, потому что устроены они умнее, чем я рисовал на схемах (указатели не разбросаны хаотично по памяти, а собраны в динамический массив).
Выбирая меньшее из двух зол, я бы шёл по элементам исходного списка, используя цикл while (или for i in range).

2023-09-16 18:27 UTC, IlyaOrlov requested changes
Классная идея и реализация замера времени выполнения!
Но осталось ещё несколько замечаний на пути к идеальному коду.

2023-09-16 18:27 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
> +        for index, min_slices in enumerate(lst[i:]):
Не совсем честно по отношению к этому способу. Новый список создаётся дважды: в стр.23 и стр.26
Справедливей так:
```python
        lst1 = lst[i:]
        first = lst1[0]
        index_min = 0
        min_lst = first
        for index, min_slices in enumerate(lst1):
```
У меня получилось, что sort_lst_2 всё равно выигрывает, хотя и не с таким большим отрывом, как в исходном варианте (была целая секунда):
sort_lst_1 => 8.401607275009155
sort_lst_2 => 8.226769208908081

2023-09-16 18:27 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_1.py
> +def speed(func):
Замечательная идея!

2023-09-16 18:27 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +def delete_post_matrix(test_lst=None, nums=7):
Не соглашусь. Наличие значения по умолчанию вроде как допускает вызов этой функции без аргументов: `delete_post_matrix()`. Но тогда мы получим ошибку времени выполнения в стр.17 (можете проверить). Вариант, как в функции matrix_print_beautiful, **здесь** больше подходит. Тогда как в функции matrix_print_beautiful я бы задал по умолчанию - () - кортеж, чтоб подсказать пользователю, что эта функция не меняет переданную матрицу.

2023-09-16 18:27 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_4.py
> +    return lst
Здесь, наверное, тоже test_lst имелся в виду.

2023-09-19 17:45 UTC, IlyaOrlov approved these changes
Отличная работа! Замечаний нет!

2023-09-19 17:45 UTC, merged