Домашнее задание 4-5 лекции
IlyaOrlov/PythonCourse2.0_September23 pull request #75
Opened 2023-09-14 10:44 UTC by Ekaterinka11

Прошу проверить 7 задачу 4 лекции и 1, 2 из 5 лекции

2023-09-14 12:27 UTC, IlyaOrlov requested changes
Хорошо, но есть пара замечаний.

2023-09-14 12:27 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_1.py
> +    x = arr.index(min(arr[i::]))
Минимум ищется по подсписку arr[i::], а индекс определяется в рамках всего списка. Поэтому, если в списке будут повторы, результат получится некорректный. Попробуйте на таком примере: `arr = [2, 1, 1]`.
И ещё min бежит по списку в поисках минимума, index опять бежит по списку в поисках индекса этого минимума. Тогда как и минимум, и его индекс можно получить за один проход по списку (сразу отмечая индексы просмотренных элементов), но для этого надо написать свою функцию.

2023-09-24 15:53 UTC, IlyaOrlov requested changes
Хорошо. Но есть, что улучшить!

2023-09-24 15:53 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_1.py
> +                arr[i], arr[x] = arr[x], arr[i]
Не нужно делать перестановки для каждого элемента меньшего, чем arr[i]. В этом вложенном цикле надо найти минимальный элемент и только его поменять местами с arr[i]. Для этого перед вложенным циклом определяем x = i и дальше сравниваем arr[n] с arr[x], меняя только x.

2023-09-24 15:53 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_2.py
> +            return s[i]
Можно вернуть сразу n. Это быстрее, чем s[i], т.к. не нужна лишняя операции доступа по индексу.

2023-09-25 06:56 UTC, Ekaterinka11 commented on Practice/Kashintseva/task5_1.py
> +                arr[i], arr[x] = arr[x], arr[i]
Поняла, исправила.

2023-09-25 06:57 UTC, Ekaterinka11 commented on Practice/Kashintseva/task5_2.py
> +            return s[i]
Ой, точно. Поправила. Спасибо.

2023-09-25 16:32 UTC, IlyaOrlov requested changes
Есть ещё замечания.

2023-09-25 16:32 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_1.py
> +                arr[i], arr[x] = arr[x], arr[i]
Хорошо. Осталось эту строку с перестановкой вынести из вложенного цикла и добавить проверку против самоприсваивания, чтоб получилось:
```python
    for n in range(i+1, len(arr)):
        if arr[n] < arr[x]:
            x = n
    
    if x != i:  
        arr[i], arr[x] = arr[x], arr[i]
```

2023-09-25 16:32 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_5.py
> +            f.read().replace("\t", "    ")
Метод replace действительно выполняет замену символов в строке и возвращает результат - новую строку, которую надо связать с переменной. Иначе мы не видим результата замены.

2023-09-25 16:32 UTC, IlyaOrlov commented on Practice/Kashintseva/task5_5.py
> +    return file
Вместо `return file` надо заново открыть этот файл (уже на запись) и записать туда строку полученную в стр.4 или 6.

2023-09-30 11:46 UTC, Ekaterinka11 commented on Practice/Kashintseva/task5_1.py
> +                arr[i], arr[x] = arr[x], arr[i]
Поняла теперь, как работает. Поправила.

2023-09-30 11:47 UTC, Ekaterinka11 commented on Practice/Kashintseva/task5_5.py
> +            f.read().replace("\t", "    ")
Разобралась, поправила.

2023-09-30 11:47 UTC, Ekaterinka11 commented on Practice/Kashintseva/task5_5.py
> +    return file
Добавила, разобралась. Спасибо.

2023-09-30 17:13 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-30 17:13 UTC, merged