Д\з по лекции №4 ( задачи 1-5)
IlyaOrlov/PythonCourse2.0_September23 pull request #78
Opened 2023-09-15 12:14 UTC by nsa3108

2023-09-15 14:18 UTC, IlyaOrlov requested changes
Прекрасно! Один нюанс только надо учесть.

2023-09-15 14:18 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_4_task1.py
> +        elif x % 15 == 0:
Кратность 15 стоит проверять первой, иначе до этой проверки интерпретатор не дойдёт (то, что кратно 15 - априори кратно 3 и 5).

2023-09-20 13:36 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_4_task1.py
> +        elif x % 15 == 0:
поправила

2023-09-20 18:36 UTC, IlyaOrlov requested changes
Почти готово;)

2023-09-20 18:36 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_4_task1.py
> +            print("Fizz")
Ну и в случае кратности числа 15 должно выводиться "FizzBuzz", а в случае кратности 3 - "Fizz". Т.е. строки 4 и 8 тоже надо поменять местами.

2023-09-20 18:49 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_4_task1.py
> +            print("Fizz")
Конечно же, вы правы, все поправила

2023-09-20 18:51 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-20 18:51 UTC, merged