Mtroshin first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #79
Opened 2023-09-16 07:00 UTC by TroshinMike

Добавлены задания по 4 лекции.

2023-09-16 15:22 UTC, IlyaOrlov requested changes
Хорошо, но есть некоторые замечания.

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.2_5zna4noe_chislo.py
> +while (len(ch) != 5) or (ch.isdecimal() == False): # почему-то числа с буквами пропускает всеравно
Это какие, например, числа с буквами пропускаются?
Кстати, сравнивать с False через == не рекомендуется. Надо либо `is False` (is сравнивает адреса, это быстрее, чем значения, и False в программе всегда существует в единственном экземпляре, под одним адресом), либо просто `not ch.isdecimal()`.

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.3_stop.py
> +    if symbol.isdecimal() != True:
Лучше `if not symbol.isdecimal():`

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.3_stop.py
> +        ch = ch + symbol
ch += symbol

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.3_stop.py
> +while symbol.lower() != "stop":
Вместо стр.1 и стр.9 можно написать прямо здесь:
`while (symbol := input("Введите число: ")).lower() != "stop":`

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.2_5zna4noe_chislo.py
> +    for i in range(0, 5):
Если 5 вынести в отдельную константу (например, LEN = 5) и везде писать именно LEN, а не конкретно 5, то программу, при необходимости, легко будет настроить на любую длину строки.

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.4_sporshik.py
> +while zapros != "хватит":
Вместо стр.1 и стр.16 можно написать прямо здесь:
`while (zapros := input("Введите ваш запрос: ")) != "хватит":`

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.5_ugadai_chislo.py
> +    if answer.isdecimal() == False:
Поздно проверять answer.isdecimal(): строкой ранее мы уже пытаемся привести answer к типу число.

2023-09-16 15:22 UTC, IlyaOrlov commented on Practice/mtroshin/lesson_6/6.6_function.py
> +def mini(a, b):
В обоих функциях требуется найти наибольшее число. Только в одной надо вернуть его при помощи return (это сделано верно), а в другой - вывести на экран при помощи print.

2023-09-17 06:14 UTC, TroshinMike commented on Practice/mtroshin/lesson_6/6.2_5zna4noe_chislo.py
> +while (len(ch) != 5) or (ch.isdecimal() == False): # почему-то числа с буквами пропускает всеравно
Это я изначально допустил ошибку и использовал вместо OR - AND и работало не корректно. Не получилось откатить коммит, не актуальные тоже отправились. 

Спасибо за уточнения! Круто!

2023-09-21 17:56 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-21 17:56 UTC, merged