Lvladimirova first branch
IlyaOrlov/PythonCourse2.0_September23 pull request #81
Opened 2023-09-17 08:03 UTC by lvladimirova

Лекция 6

2023-09-17 08:08 UTC, lvladimirova commented
Первые два задания

2023-09-17 11:47 UTC, IlyaOrlov commented
> Первые два задания

Класс! А где файлы?)

2023-09-17 12:29 UTC, lvladimirova commented
Почему-то с первого раза файлы не вошли. Ещё раз прикрепила

2023-09-17 14:44 UTC, IlyaOrlov requested changes
Супер! Один момент можно ещё улучшить.

2023-09-17 14:44 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_6/6_1.py
> +        s[i], s[min_i] = s[min_i], s[i]
Здесь можно добавить проверку на самоприсваивание: `if min_i != i:`

2023-09-20 16:05 UTC, lvladimirova commented
Не очень поняла для чего, если я изначально задаю, что min_i = i. Объясните, пожалуйста)

2023-09-20 18:34 UTC, IlyaOrlov commented
> Не очень поняла для чего, если я изначально задаю, что min_i = i. Объясните, пожалуйста)
Всё верно. Изначально Вы задали min_i = i - индекс предполагаемого минимума. Затем в цикле:
```python
        for x in range(i+1, len(s)):
            if s[x] < s[min_i]:
                min_i = x
```
min_i может поменяться на x, если найдётся меньшее число (реальный минимум). Но может и не поменяться, и останется равным i. А если min_i так и остался равным i, то зачем делать перестановку `s[i], s[min_i] = s[min_i], s[i]`?

2023-09-24 15:46 UTC, IlyaOrlov requested changes
Добавил замечания по мелочи.

2023-09-24 15:46 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_6/6_3.py
> +s = ("Часы работы:\n 13-17 - Mon, Thu, Fri\n 9-13 - Tue, Wed")
Зачем брать строку в скобки?

2023-09-24 15:46 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_6/6_4.py
> +    for i in range(len(matrix)):
Зачем в этом и вложенном цикле идти по индексам? Можно же сразу идти по элементам:
```python
for i in matrix:
        for j in i:
            print(j, end=' ')
```
Доступ к элементу по индексу - вовсе не обязательная в этом случае операция.

2023-09-24 15:46 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_6/6_5.py
> +r = input("Выберите действие с файлом (свернуть или развернуть табуляцию): ")
А где вызов fun_zamena?

2023-09-24 15:46 UTC, IlyaOrlov commented on Practice/lvladimirova/Lecture_6/6_4.py
> +def fun_zamena(matrix):
Название функции как-то не особо отражает то, что эта функция делает;)

2023-09-24 17:54 UTC, lvladimirova commented
К заданию 6_4. Почему-то у комментариев упорно Pending. Долго мучилась с матрицей, читала в интернете. Код получился рабочий, но в голове остались неясности. Матрица - это набор списков внутри списка. x - это как раз внутренний список матрицы. Мы начинаем обход списков, если находим, что в списке элемент с индексом y (x[y]) = заданному числу, то удаляем во всех вложенных списках элементы с данным индексом y. Это я правильно поняла?

2023-09-24 17:55 UTC, lvladimirova commented
Главная моя неясность, я никак не пойму, почему код работает, когда while y != len(x). Почему именно не равен? Индекс не равен длине вложенного списка.. Меня стала смущать эта строка, именно неравенство

2023-09-24 17:57 UTC, IlyaOrlov commented
> К заданию 6_4. Почему-то у комментариев упорно Pending. Долго мучилась с матрицей, читала в интернете. Код получился рабочий, но в голове остались неясности. Матрица - это набор списков внутри списка. x - это как раз внутренний список матрицы. Мы начинаем обход списков, если находим, что в списке элемент с индексом y (x[y]) = заданному числу, то удаляем во всех вложенных списках элементы с данным индексом y. Это я правильно поняла?

Про Pending написал в чате.
Да, про удаление поняли правильно.

2023-09-24 18:00 UTC, IlyaOrlov commented
> Главная моя неясность, я никак не пойму, почему код работает, когда while y != len(x). Почему именно не равен? Индекс не равен длине вложенного списка.. Меня стала смущать эта строка, именно неравенство

А если интерпретировать это выражение так:
```
Пока **y** НЕ стал равен len(x):
    делаем всякое и двигаем **y**
```
?

2023-09-24 18:56 UTC, lvladimirova commented
> > Главная моя неясность, я никак не пойму, почему код работает, когда while y != len(x). Почему именно не равен? Индекс не равен длине вложенного списка.. Меня стала смущать эта строка, именно неравенство
> 
> А если интерпретировать это выражение так:
> 
> ```
> Пока **y** НЕ стал равен len(x):
>     делаем всякое и двигаем **y**
> ```
> 
> ?

Никак не пойму до конца физику процесса, в каком случае этот пресловутый y может быть равен len(x)

2023-09-25 16:19 UTC, IlyaOrlov commented
Чтоб Pending-комментарии опубликовались надо нажать эту кнопку (рисунок может немного отличаться):
![image](https://github.com/IlyaOrlov/PythonCourse2.0_September23/assets/14909169/296c4044-0cfd-4a40-9770-b5a77a802c27)

2023-09-25 16:25 UTC, IlyaOrlov commented
> > > Главная моя неясность, я никак не пойму, почему код работает, когда while y != len(x). Почему именно не равен? Индекс не равен длине вложенного списка.. Меня стала смущать эта строка, именно неравенство
> > 
> > 
> > А если интерпретировать это выражение так:
> > ```
> > Пока **y** НЕ стал равен len(x):
> >     делаем всякое и двигаем **y**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> Никак не пойму до конца физику процесса, в каком случае этот пресловутый y может быть равен len(x)

Вот же внутри цикла while в ветке else **y** увеличивается на 1. Так он постепенно станет равен len(x).
```python
def fun_matrix(matrix, element):
    for x in matrix:
        y = 0
        while y != len(x):
            if x[y] == element:
                for lst in matrix:
                    lst.pop(y)
            else:
                y += 1
    return matrix
```
Хороший способ отследить изменения **y** в цикле - запустить этот код в режиме отладчика.

2023-09-26 18:14 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-09-26 18:14 UTC, merged