modul5 task5
IlyaOrlov/PythonCourse2.0_September23 pull request #83
Opened 2023-09-20 13:31 UTC by RemoSet

2023-09-20 18:41 UTC, IlyaOrlov requested changes
Всё классно! Замечаний нет. Но есть маленькое примечание;)

2023-09-20 18:41 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_5.py
> +    replace_char_file("my_f.txt", "    ", "\\t")
Символ табуляции "\t" экранировать не нужно. А чтоб он вывелся на печать не как табуляция, а именно как "\t", нужно обернуть вывод в функцию repr. Например, в стр.3 можно написать: `print(repr(f.read()))`

2023-09-21 16:32 UTC, RemoSet commented on Practice/amarinin/Modul_5/modul5_lesson5_5.py
> +    replace_char_file("my_f.txt", "    ", "\\t")
Посмотрел, запомнил, добавил ). Функция похожа на  "сырую" строку.

2023-09-21 18:03 UTC, IlyaOrlov commented on Practice/amarinin/Modul_5/modul5_lesson5_5.py
> +    replace_char_file("my_f.txt", "    ", "\\t")
Да. Верно. str() позволяет получить из объекта строку для красивого вывода, repr() тоже позволяет получить строку, но, как правило, не для красоты, а для удобства отладки. Мы в Продвинутой части курса ещё поговорим, про методы, которые стоят за этими функциями.

2023-09-21 18:04 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-09-21 18:04 UTC, merged