Д\з по лекции №4 ( задачи 6-8)
IlyaOrlov/PythonCourse2.0_September23 pull request #85
Opened 2023-09-21 19:27 UTC by nsa3108

2023-09-22 19:04 UTC, IlyaOrlov requested changes
Хорошо, но некоторые замечания всё же есть.

2023-09-22 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_4_task8.py
> +user = str
Наверное, имелось в виду `user = str()`, иначе это не создание пустой строки, а создание "псевдонима" для стандартной функции str. Ну а вообще эта инициализация не нужна: переменная user связывается со значением в следующей же строке, у неё и так нет шансов остаться непроинициализированной)

2023-09-22 19:04 UTC, IlyaOrlov commented on Practice/nskorokhodova/Practice_lec_4_task8.py
> +computer = random.choice(xyz)
В чём смысл этого выбора, если сразу же (в строке 9) делается перевыбор?

2023-09-25 11:20 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_4_task8.py
> +user = str
ага, получается не нужна

2023-09-25 11:20 UTC, nsa3108 commented on Practice/nskorokhodova/Practice_lec_4_task8.py
> +computer = random.choice(xyz)
Это ошибка, поправила, так как это не логично, юзер не должен видеть выбор компьютера до своего выбора, либо надо убрать было принт

2023-09-25 16:34 UTC, merged