Platonova 6
IlyaOrlov/PythonCourse2.0_September23 pull request #93
Opened 2023-10-01 02:43 UTC by yilya21q

2023-10-01 10:11 UTC, IlyaOrlov requested changes
ОК. Есть некоторые замечания.

2023-10-01 10:11 UTC, IlyaOrlov commented on Practice/platonova/lec_4_6.py
Нужно всё-таки стиль соблюсти: определение функции должно быть выше основного кода и отделяться от него двумя пустыми строками.

2023-10-01 10:11 UTC, IlyaOrlov commented on Practice/platonova/lec_4_6_2.py
То же замечание по стилю, что и для [lec_4_6.py](https://github.com/IlyaOrlov/PythonCourse2.0_September23/pull/93/files#diff-ace5b5ae06c0e55ad01dcaa6516b31cde67bf0aac9ae7d5e91b16aa30bb7586f). Ну и, согласно заданию, здесь функция должна сама выводить результат на экран, а не возвращать его.

2023-10-02 04:17 UTC, yilya21q commented on Practice/platonova/lec_4_6.py
Скорректировала код

2023-10-02 04:17 UTC, yilya21q commented on Practice/platonova/lec_4_6_2.py
Скорректировала код

2023-10-02 11:27 UTC, IlyaOrlov commented on Practice/platonova/lec_4_6_2.py
А где здесь вывод на экран?
Предполагалось, что здесь внутри функции будет print(a) и print(b) вместо return.

2023-10-02 13:11 UTC, yilya21q commented on Practice/platonova/lec_4_6_2.py
изменила, а return не использовать в решении этой задачи?

2023-10-03 07:47 UTC, IlyaOrlov commented on Practice/platonova/lec_4_6_2.py
При желании можно и return добавить) Но print должен быть обязательно, т.к. в задаче требуется, чтоб функция выводила результат на экран.

2023-10-03 07:48 UTC, IlyaOrlov requested changes
Осталось небольшое замечание по стилю.

2023-10-03 07:48 UTC, IlyaOrlov commented on Practice/platonova/lec_4_6_2.py
> +        print (a)
Здесь и в стр. 5 лишние пробелы между print и скобкой.

2023-10-04 08:05 UTC, yilya21q commented on Practice/platonova/lec_4_6_2.py
> +        print (a)
Спасибо, исправила

2023-10-04 19:11 UTC, IlyaOrlov requested changes
Один нюанс по новому заданию!

2023-10-04 19:11 UTC, IlyaOrlov commented on Practice/platonova/lec_5_1.py
> +        arr[minimum], arr[i] = arr[i], arr[minimum]
Если в цикле (стр.4-6) minimum так и не поменялся (остался равен i), то наверное, перестановку (получается, самоперестановку) делать не стоит.

2023-10-07 08:03 UTC, yilya21q commented on Practice/platonova/lec_5_1.py
> +        arr[minimum], arr[i] = arr[i], arr[minimum]
Внесла изменения

2023-10-07 16:56 UTC, IlyaOrlov requested changes
Добавил существенное замечание.

2023-10-07 16:56 UTC, IlyaOrlov commented on Practice/platonova/lec_5_2.py
> +def fun_find_dup(lst):
Это решение позволяет найти первый **повторяющийся** элемент (т.е. 1), а не первый **повторившийся** (т.е. 2), о котором говорится в задании.
Казалось бы, повтор и повтор - какая разница?) Но проблема ещё в том, что такой подход к поиску этого повтора имеет повышенный класс алгоритмической сложности - O(N^2). Тогда как можно было бы обойтись сложностью O(N).

2023-10-08 13:45 UTC, yilya21q commented on Practice/platonova/lec_5_2.py
> +def fun_find_dup(lst):
Внесла изменения

2023-10-08 14:57 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-08 14:57 UTC, merged