Домашнее задание Лекция 5. Задания 1 и 2).
IlyaOrlov/PythonCourse2.0_September23 pull request #97
Opened 2023-10-06 12:47 UTC by TroshinMike

2023-10-06 16:23 UTC, IlyaOrlov requested changes
Есть замечание по эффективности решения.

2023-10-06 16:23 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_5/2.py
Решение хорошее, но не оптимальное. Алгоритмическая сложность данного решения в худшем случае O(n^2), а можно вполне обойтись O(N), если просмотренные элементы складывать во множество.

2023-10-13 11:32 UTC, IlyaOrlov requested changes
Добавил ещё замечание.

2023-10-13 11:32 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_5/4.py
> +        for d in i:
Конкретно в этом цикле всё-таки стоит идти по индексам. 
Во-первых, метод index() вызывать не придётся.
Во-вторых, решение получится правильное. Иначе сейчас для списка lst1 = [[1, 2, 2], [4, 3, 6], [7, 8, 9]] при удалении столбцов, содержащих 2, один столбец упускается.

2023-10-16 10:28 UTC, TroshinMike commented on Practice/mtroshin/Lecture_5/4.py
> +        for d in i:
А как идти по индексам для списка списков?:)

2023-10-16 12:56 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_5/4.py
> +        for d in i:
Примерно так:)
```python
    n = int(s)  # чтоб не преобразовывать в цикле на каждой итерации
    for i in lst1:
        j = 0
        while j < len(i):
            if n == i[j]:
                for t in lst1:
                    t.pop(j)
            else:
                j += 1
```

2023-10-16 19:53 UTC, TroshinMike commented on Practice/mtroshin/Lecture_5/4.py
> +        for d in i:
Спасибо, Илья! Понял:)

2023-10-17 14:30 UTC, IlyaOrlov approved these changes
Ещё пара замечаний по мелочи.

2023-10-17 14:30 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_5/2.py
> +    mnogestvo = set('')
Можно просто: `mnogestvo = set()`

2023-10-17 14:30 UTC, IlyaOrlov commented on Practice/mtroshin/Lecture_5/2.py
> +            print(arr[i])
Т.к. нам нужен только первый повторяющийся элемент, логично после этого вывод сделать break (ну или return, как в Вашем предыдущем решении).

2023-10-18 08:43 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-10-18 08:44 UTC, merged