modul6
IlyaOrlov/PythonCourse2.0_September23 pull request #98
Opened 2023-10-06 16:00 UTC by RemoSet

2023-10-06 16:28 UTC, IlyaOrlov requested changes
Есть небольшое замечание)

2023-10-06 16:28 UTC, IlyaOrlov commented on Practice/amarinin/Modul_6/modul6_lesson6_2.py
> +        return True if self.weight < other.weight else False
Здесь и в других методах можно проще: `return self.weight < other.weight`. И так будет True или False.

2023-10-06 16:28 UTC, IlyaOrlov commented on Practice/amarinin/Modul_6/modul6_lesson6_2.py
> +        super_duck = Duck("КАДАВР", self.weight + other.weight)
:))))))

2023-10-06 21:21 UTC, RemoSet commented on Practice/amarinin/Modul_6/modul6_lesson6_2.py
> +        return True if self.weight < other.weight else False
Поправил ),  уже третий раз забыл про это выражение.

2023-10-07 08:56 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет!

2023-10-07 08:56 UTC, merged